MessengerProj/src/main/res/values-ru/strings.xml

- The "FromSelf" string is just upside-down: it says "For me" - that is "Мне" in Russian, instead of "Я" - "Me" in English.
- All other corrections are rather cosmetical - but the punctuation.
/Ilya

Russian translation correction

---

MessengerProj/src/main/java/com/b44t/messenger/WelcomeActivity.java

"Account not configured" was shown instead of the configured mail address.

Update the Notification after import

---

MessengerProj/jni/cyrussasl/include/sasl/config.h

Enable STATIC_LOGIN mech to make it possible to use the authentication-type PLAIN
With this change it was possible to log in to Office365 SMTP server, see #168

enable STATIC_LOGIN mech

---

MessengerProj/src/main/res/values-de/strings.xml

This commit fixes a typo and removes a wrong space from the german strings.xml file.

Fix typo and spacing in strings.xml

---

MessengerProj/src/main/java/com/b44t/messenger/ChatActivity.java
MessengerProj/src/main/java/com/b44t/messenger/Components/AvatarUpdater.java
MessengerProj/src/main/java/com/b44t/messenger/LaunchActivity.java
MessengerProj/src/main/java/com/b44t/messenger/WallpapersActivity.java
MessengerProj/src/main/res/values/strings.xml

At least on my phone (Android 7.0) the ACTION_IMAGE_CAPTURE and ACTION_VIDEO_CAPTURE Intents silently fail if the app does not have the camera permission. (#319).
I use the same code like it is used on other places to request for that permission if it is not granted.
I tested it and it works as expected.

Request permissions to use the Camera before starting Capture

---

MessengerProj/src/main/java/com/b44t/messenger/Cells/TextInfoCell.java
MessengerProj/src/main/java/com/b44t/messenger/SettingsAccountFragment.java
MessengerProj/src/main/res/values-da/strings.xml
MessengerProj/src/main/res/values-de/strings.xml
MessengerProj/src/main/res/values-es/strings.xml
MessengerProj/src/main/res/values-eu/strings.xml
MessengerProj/src/main/res/values-fr/strings.xml
MessengerProj/src/main/res/values-hu/strings.xml
MessengerProj/src/main/res/values-it/strings.xml
MessengerProj/src/main/res/values-nb/strings.xml
MessengerProj/src/main/res/values-nl/strings.xml
MessengerProj/src/main/res/values-pl/strings.xml
MessengerProj/src/main/res/values-pt/strings.xml
MessengerProj/src/main/res/values-ru/strings.xml
MessengerProj/src/main/res/values-sq/strings.xml
MessengerProj/src/main/res/values-uk/strings.xml
MessengerProj/src/main/res/values/strings.xml

This PR adds a GMail specific text with links to `enable less secure apps` or `create an app password` to the setup dialog, if the E-Mail adress is recognized as GMail (`@gmail.` or `@googlemail.`).
It addresses #20 (#178).

Add Gmail specific info in setup.

---

MessengerProj/src/main/java/com/b44t/messenger/KeepAliveService.java

Fix #362. You can reproduce #362 by changing the "configuration", e.g. by rotating the screen (Delta Chat does not need to be in foreground for this).
However, my fix adds a dependence from KeepAliveService to ApplicationLoader. Also, now, KeepAliveService "knows" that the permanent notification is only shown when the screen is off. Therefore, in case you want to change this, you will have to remember to change KeepAliveService as well. 
A better solution may be a "isForegroundTaskRunning()" method somewhere else, but I do not know where.

Do not try to update the permanent notification when the screen is on, fix #362

---

res/layout/attachment_type_selector.xml

the swap results in two buttons in the first fow - camera and gallery - and the other stuff in the second row; no gaps.
looks much better imho.
also, when we re-enable the location button, it get's a first-class function as placed in the first row then :)

swap hidden-location and file button for a smoother layout

---

build.gradle

if there is no ~/.gradle/gradle.properties or DC_DEBUG_STORE_FILE or DC_RELEASE_STORE_FILE is not set there, the gradle script uses the defaults as before 0.100.0

use defaults if gradle.properties does not set the DC_* keystore values

---

res/layout/group_create_activity.xml

the buttons should now ... 
- allow multiple lines (good for longer text in different languages)
- be of the same height
- use the available width better
closes #657

tweak buttons in the add-group activity

---

src/org/thoughtcrime/securesms/CreateProfileActivity.java
src/org/thoughtcrime/securesms/util/Prefs.java

reading the displayname from the application-preferences works only for a single installation and works not when data are imported.
so, there is no reason to save these information twice; therefor this pr also stops saving the displayname to the application-preferences at all.
closes #423 
@angelo-fuchs @Boehrsi @florianhaar i think, that pr not requested to review by a special person can be reviewed/merged by the first person that offers some time to comment and/or thinks the pr can be merged.
i think adding reviewers by name is only needed if the pr-review should _really_ be assigned to a special person or maybe when one knows the person is online or the pr is urgent or so.
therefore i added no one as reviewers to the pr :)

read display-name from the database, not from the application-preference

---

src/org/thoughtcrime/securesms/ConversationListItem.java

this pr hide the group-indicator for the contact- and messages-search-result; it was displayed accidentally if the view was used by a group-chat before (views are recycled).
closes #669

fix group-indicator display on searching for contacts and messages

---

src/org/thoughtcrime/securesms/GroupCreateActivity.java

Fixes #698 part 1 and 2.
The problem in part 2 was, that a new group is created before the QR code is shown. If one goes back, the group members list in GroupCreateActivity is not updated from the new group. It therefore stays empty and if the GroupCreateActivity is closed, the group is updated from the, still empty, members list, so all members are deleted from the group. I would think this is also the case when someone scans the QR code and joins the group, but I couldn't test it as I don't have a second phone with delta chat at hand.
On top of rereading the members list (this pr) one could also think about initialising the members list with the "Me" contact, since it will later be added automatically. This would make it more transparent to the user.

Group Create Issues #698

---

src/org/thoughtcrime/securesms/ConversationItem.java

Linkify.ALL includes Linkify.MAP_ADDRESSES which is deprecated on oreo (android 8) and causes exceptions.

avoid ClassNotFoundException

---

src/org/thoughtcrime/securesms/notifications/AbstractNotificationBuilder.java
src/org/thoughtcrime/securesms/notifications/MultipleRecipientNotificationBuilder.java
src/org/thoughtcrime/securesms/notifications/SingleRecipientNotificationBuilder.java

it's a bit odd, the NotificationChannels should provide all the power of our notification settings, however, they don't. it is not possible to change an led color nor the sound.
so we still need out settings, however, applying them is getting harder with the NotificationChannels which do not allow programmatic changes and, even worse, have a higher precedence as parameters passed to the Notification.Builder.
we hack around this by using a channelId that includes some settings - if the user eg. changes the led color, this results in a new channel and the old channel is deleted.
signal seems to do basically the same in https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/notifications/NotificationChannels.java
closes #709

allow changing led, vibration, sound on NotificationChannels

---

build.gradle

We should use the Google repositories at first in the order to resolve dependencies, as sometimes the sync between Googles repos and Maven.org / MavenCentral ones fails and builds will fail. E.g. right now for me with _Could not find manifest-merger.jar (com.android.tools.build:manifest-merger:26.0.1)_).

Use Googles repositories first

---

res/values/strings.xml
src/org/thoughtcrime/securesms/BaseActionBarActivity.java
src/org/thoughtcrime/securesms/ConversationListActivity.java
src/org/thoughtcrime/securesms/RecipientPreferenceActivity.java
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
src/org/thoughtcrime/securesms/preferences/AppProtectionPreferenceFragment.java
src/org/thoughtcrime/securesms/preferences/ChatBackgroundActivity.java
src/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java

Should fix #649:
- Cleanups 
- Call super.onActivityResult(requestCode, resultCode, data) where needed to avoid problems
- Hide UI on stop and only show it if no screen lock is active or if the screen lock was successfully unlocked
- Fixed some cases where the screen lock wasn't applied
- Fixed one case where the screen lock was applied after initial activation, but it shouldn't
I tried to test on new and old devices and hope every edge case is now fixed. But it would be great if some tests on new and old device would be performed by the reviewer before merging.

Lock pattern security issues #649

---

res/values/strings.xml
src/org/thoughtcrime/securesms/database/loaders/BucketedThreadMediaLoader.java

@r10s I could use some unpedantic pragmatism here. Current wording is confusing (at least to me & @adbenitez ).
Problem: In the Media Gallery "Today" means "The last 24 hours". In the Conversation view it means "Since 00:00.00" Similar for "Yesterday". Then they diverge even more: Conversation stays in the "Day" segmentation, Gallery changes to "This week" which means 7*24 h - 5*24 h timespan, and "This month" which is everything after that until 30*24h.
How would you name the tags & what timeframe do you think is good for it?

#685 date alignment in media gallery

---

src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java

For android SDK versions 23 and below `startActivity` throws a RuntimeException if called from a context other then an activity. To circumvent this, the flag FLAG_ACTIVITY_NEW_TASK has to be added to the intent.
Edit: I've just seen there has just been #740 opened at last partly on this. The corresponding [forum thread](https://support.delta.chat/t/unrecognized-attachments/279) describes the exactly same behaviour a friend of mine had and the mentioned devices (Samsung Note 2..5) all run android versions older than SDK 23, so I think this one fixes this.

Open files via intent didn't work for old android versions.

---

src/org/thoughtcrime/securesms/components/ThumbnailView.java

the disk cache of the glide module seems to use some hashes or so.
just got the situation that a completely different image was shown in the chat. enlarging the image, the correct one was shown.
by disabling the disk cache (the memory cache is still active), the problem gone away.
i think we do not need the disk cache as all images are already locally, nothing gets downloaded from the ui side.
therefor this pr disables the disk cache (as already done for most other load processes) and avoids such problems.
might be related to https://github.com/bumptech/glide/issues/3544
caching is considered harmful.

disable glide disk cache

---

jni/dc_wrapper.c
res/layout/preference_divider.xml
res/layout/preference_right_summary_widget.xml
res/values/arrays.xml
res/values/strings.xml
res/xml/preferences_advanced.xml
res/xml/preferences_appearance.xml
res/xml/preferences_chats.xml
res/xml/preferences_notifications.xml
res/xml/recipient_preferences.xml
src/com/b44t/messenger/DcContext.java
src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/ConversationListActivity.java
src/org/thoughtcrime/securesms/ConversationListAdapter.java
src/org/thoughtcrime/securesms/ConversationListFragment.java
src/org/thoughtcrime/securesms/ConversationTitleView.java
src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
src/org/thoughtcrime/securesms/connect/DcHelper.java
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java
src/org/thoughtcrime/securesms/preferences/widgets/ListPreferenceWithSummary.java
src/org/thoughtcrime/securesms/util/Util.java

this pr will improve the interaction between chats and email
todo:
the option should be handled by the core, proposed name is `show_emails`.
@hpk42 wrt the default, meanwhile i also tend to not show emails but replies to chats by default.

email interactions

---

res/values/arrays.xml
res/xml/preferences_advanced.xml
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
src/org/thoughtcrime/securesms/util/BitmapUtil.java
src/org/thoughtcrime/securesms/util/Prefs.java

this pr adds an experimental feature that introduces a much higher compression for jpeg images to save some bandwidth.
while the compression is still okay-ish for many images, eg. for photos containing text, the text typically gets less readable so that i would not change the defaults for "balanced" currently.
the real resulting image size always depends a bit on the content, however, the example above is a typical one; most images i've tried with the new settings are about 50K, however, there may be some that are still larger, jpeg does not give you an guarantee here.

add an experimental feature for high image compression

---

AndroidManifest.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/ShareActivity.java

Bigger changes than expected ahead:
- Added an intent filter for sharing of multiple files to the manifest
- Added strings for the required dialogs ("permissions" and "should send multiple files")
- Added handling for sharing via file paths (that's what e.g. Amaze does @r10s)
- Added permission handling if sharing via file paths is used, instead of content providers (otherwise the app would crash here)
- Added sharing of multiple files to the ShareActivity (a dialog comes up, asking the user if it's fine to send the files right away, as we can't show a preview / draft for multiple files at once)
- General separation between one / multi file handling added
- Logic added for message creation and message sending
- Cleanup for the resolving of attachements
In general i tried to keep all the …

sharing files does not work #434

---

src/org/thoughtcrime/securesms/ApplicationContext.java
src/org/thoughtcrime/securesms/preferences/AppearancePreferenceFragment.java
src/org/thoughtcrime/securesms/util/DynamicLanguage.java

currently, the selected locale is updated for all activities calling DynamicLanguage.onResume
however, some strings are also needed by the core and the ApplicationContext that is not always bound to an activity.
this pr sets the locale of the ApplicationContext on startup and on locale changes.
(in the past, the locale was wrong only if the selected language was _not_ the system language, so, this bug was not really "in the face" :)

also update locale of ApplicationContext

---

src/org/thoughtcrime/securesms/RecipientPreferenceActivity.java

Just added the "New chat" entry to the list of removed preference items when in a group context.

Unused "New chat" option on groups's profile #754

---

src/org/thoughtcrime/securesms/ApplicationPreferencesActivity.java
src/org/thoughtcrime/securesms/ConversationFragment.java

via the "invite" activity, mainly phone-number-based-apps will be reached - there is no need to access email-based-apps as these can be contacted with delta directly.
however, as users may not have their email-credentials in mind, pushing them to switch from phone- to mail-based messengers directly, may cause more harm than success.
also, there is also the footer that already defaults to "hey, let's use delta chat".

disable invite activity for now

---

src/org/thoughtcrime/securesms/notifications/MessageNotifier.java

Replaced record.isMms(), which always returned false, with record.hasFile(). Also added some handling if we can specify the type of the media message more closely. So now images should produce "Image" and so on. If no summary is available the default notify_media_message text is used. This text is also used if the message contains media and text.

Empty notification for voice and image messages #821

---

src/org/thoughtcrime/securesms/MediaPreviewActivity.java

I adjusted the forwarding of media view items, to be handled like forwarding is done on other screens (based on the message id).

Forwarding image from image viewer doesn't work #805

---

src/org/thoughtcrime/securesms/LogViewFragment.java

Improve the log view - as reported in #857
Edit: Tested with Android 4.4.2 where date+time was not shown before, but now is.

Logcat with date+time for all Android versions

---

src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java

MimeTypeMap.getFileExtensionFromUrl() doesn't handle white spaces correctly (which is kind of hilarious). I thought about ditching the method and writing one myself, but the easiest and safest solution is probably to just remove white spaces from the path string. As the string is only used for parsing the extension is does not matter that the replaceAll call changes the string in general.

Attachments with spaces in file name are not handled correctly #854

---

src/org/thoughtcrime/securesms/ApplicationContext.java
src/org/thoughtcrime/securesms/map/MapActivity.java

the current calls to mapbox seems to send some data to the mapbox-server as reported at https://support.delta.chat/t/end-of-privacy/393/7
this pr targets this issue by:
- initializing Mapbox only as needed
- calling functions to tell Mapbox not to send telemetry data
seems as if this is respected by Mapbox, however, if not, it might be needed to swich totally. there are a bunch of options, eg. at https://wiki.openstreetmap.org/wiki/Frameworks#Displaying_interactive_maps however, probably not all are _better_ options.

init mapbox only as needed and disable mapbox-telemetry

---

src/org/thoughtcrime/securesms/geolocation/LocationBackgroundService.java

as we've stopped to get locations from the NETWORK_PROVIDER a few days ago, it's probably also useless to check them.
@cyBerta however, i'm not sure, just came over that.
feel free to close or merge :)

do not check location-provider we've not requested

---

src/org/thoughtcrime/securesms/providers/PersistentBlobProvider.java

just had this situation in an emulator, this commit fixes the issue. i think it cannot harm much as it is executed only if the first attempt fails (instead of throwing an error).
however, apart from that, the PersistenBlobProvider needs some more love anyway, see eg. #901

use cacheDir if externalCacheDir is not available

---

res/values/strings.xml
src/org/thoughtcrime/securesms/QrShowActivity.java

- Added a toast when entering / reentering the view
- Changed the hint text to inform about the network requirement (only if no internet connection is available)
- Added a connection listener to adjust the hint text if the connection type changes while in the view 
- Tested for general and group QR view

show a hint that qr-verification cannot be done without network #756

---

build.gradle

i think 1.0 is fine as well :)
currently, i am not up for further investigations, however, also others apps are still using 1.0.x so at least we're not alone :)

revert the mp4-parser-upgrade

---

src/org/thoughtcrime/securesms/components/SearchToolbar.java

- Changed the icon (from "search" to "ok")
- Keyboard is closed if "ok" is pressed
- The current search stays intact
- Tested on Android 6 and 9

close search-keyboard on click on ok #910

---

src/org/thoughtcrime/securesms/RecipientPreferenceActivity.java
src/org/thoughtcrime/securesms/components/AvatarImageView.java
src/org/thoughtcrime/securesms/notifications/SingleRecipientNotificationBuilder.java
src/org/thoughtcrime/securesms/preferences/widgets/ProfilePreference.java

Sadly I wasn't able to reproduce neither the group image problem nor the "me" image problem. But I found some Glide caching stuff (https://bumptech.github.io/glide/doc/caching.html#skipping-the-cache) which could produce those problems. I disabled the disk caching as DCC provides the images anyway "on disk" and we don't need additional caching there. I kept the in memory caching as this definitely speeds up the repeated loading of images in our use case. @r10s could you check if these adjustments are fixing the problem?

Wrong group picture shown in group settings #817

---

src/org/thoughtcrime/securesms/ConversationFragment.java

closes #731
this pr also restores the just disabled scrollToLastSeenPosition() function as this did not get the desired effect. in fact, the app never _really_ scroll down on incoming messages, but the position was disturbed what, of course, is also annoying :)

do not scroll down on list updates

---

res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationListFragment.java
src/org/thoughtcrime/securesms/LogViewFragment.java
src/org/thoughtcrime/securesms/components/reminder/OutdatedReminder.java

Added the mentioned feature:
- A reminder (not dismissable) is shown in the chat list. It's marked with a special error color defined by the reminder class
- The reminder is only added if no other reminders are applied. I implemented it this way to avoid blocking of other reminders, as this one isn't dismissable
- It's shown only for apps where no installerPackageName is set and if the app wasn't updated within the last 90 days (I think this is a good value inbetween the suggested two vs. six months)
- If the user taps on the reminder a dialog is shown which allows the user to directly go to F-Droid or the Google Play store
Feel free to change the time frame value or the added strings. Please see the screenshots for more information.

Let manually downloaded and not updated APKs expire #885

---

src/org/thoughtcrime/securesms/mms/AttachmentManager.java
src/org/thoughtcrime/securesms/mms/MediaConstraints.java
src/org/thoughtcrime/securesms/mms/PushMediaConstraints.java
src/org/thoughtcrime/securesms/profiles/ProfileMediaConstraints.java

there was an old signal limit that disallows sending videos of more than 100 MB. 
as delta chat recodes videos, however, even larger files can be sent.
there were similar limits for other file types.
this pr removes these limits and does a generic check to avoid trying to recode/process files that are really huge (1 gb chosen by random)

allow sending large files and videos

---

AndroidManifest.xml
src/org/thoughtcrime/securesms/ProfileSettingsFragment.java

this pr changes be behavior of a tap on a member in the chat-profile.
instead of asking whether to start a new chat, the member-profile is shown. from there, with a second tap, a new chat can be started.
this behavior-change allows to "browse around" while still allowing starting new chats easily enough (the second tap is always on the same place, no scrolling or so required)
cc @hpk42 :)

access member-profiles from chat-profine

---

src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/components/InputAwareLayout.java
src/org/thoughtcrime/securesms/components/KeyboardAwareLinearLayout.java

* workaround for #959 (buggy KeyAwareInputLayout update mechanism leads to false back button behavior)

keyboard aware layout bugfix (not working back button fix)

---

res/values/styles.xml

replaces #970 
we cannot use more lines without getting problems or limited functionality on displays smaller 4 inches.
so using 6 or even 10 lines or resizable field (i think i would not really like that, too fiddly) would require some larger refactoring. maybe we can also use smaller padding atop and abottom of the field, however, also this is out of scope for a "fast fix today"

make input field 25% larger :)

---

src/org/thoughtcrime/securesms/GroupCreateActivity.java
src/org/thoughtcrime/securesms/contacts/ContactSelectionListAdapter.java
src/org/thoughtcrime/securesms/contacts/ContactSelectionListItem.java
src/org/thoughtcrime/securesms/util/SelectedRecipientsAdapter.java

fixes #833
!!! This PR doesn't allow to remove yourself from any multiselect contact list !!!
- this means using the "add members" item in profile -> group tab will not allow the user anymore to leave a group
- leaving a group is restricted to the corresponding menu item "Leave group"

don't allow to remove yourself from the multiselect contact list, 

---

src/org/thoughtcrime/securesms/ShareActivity.java

Fix for #996
- Changed the extra type to char sequence to cover String and SpannableString
- Added a null check to avoid crashes

Sharing from special app crashed #996

---

src/org/thoughtcrime/securesms/RegistrationActivity.java

As requested in #1012, disabled the toggles if the client is already configured.

Disable password visibility toggle if isConfigured #1012

---

src/org/thoughtcrime/securesms/components/ComposeText.java

closes #1015, see also https://support.delta.chat/t/enabling-system-side-emojis-it-blocks-the-possibility-to-use-the-entry-button-in-default-aosp-keyboard/540

allow multi-line-messages when system-emojis are enabled

---

src/org/thoughtcrime/securesms/notifications/MultipleRecipientNotificationBuilder.java
src/org/thoughtcrime/securesms/notifications/SingleRecipientNotificationBuilder.java

In Delta Chat 0.510 the order of the text body of notifications starts from the oldest on top to the newest at the bottom. 
This results in invisible latest messages if there are many unread messages in one chat. The last incoming messages got cut off by Android's system components.  
With this PR I propose to change that behavior to the opposite - the newest message is on top, older ones are below.
I'll attach some images to show the state of the PR.

change text body order back to latest text body on top

---

src/org/thoughtcrime/securesms/NewConversationActivity.java

Fixed by performing the initial mapping (body=content / subject=content) on the encoded string loaded from the URI and decoding the already mapped values afterwards.
Also verified against https://github.com/deltachat/deltachat-android/issues/937 that all cases provided within that issue are still working.

Mailto still partly broken #1005

---

src/org/thoughtcrime/securesms/ConversationActivity.java

when forwarding a message to a one-to-one-chat,
it is useful to see the email address
as there may be various chats with the same user having the same name.

show email address on forwarding

---

res/layout/conversation_list_item_view.xml
res/values/attrs.xml
res/values/themes.xml
src/org/thoughtcrime/securesms/ConversationListItem.java

the group-icon (the two small ppl) was not really used consistently inside the app - it was shown the in chatlist but it was not shown in the group title and on other places.
same on desktop, where it is additionally shown too small compared to the font.
ios did never show it anywhere.
@Jikstra and me came to the conclusion that it is better to not use a group icon at all:
- it is pretty clear to the user, what is a group and what not
- less noise on the screen
- also, many users use an emoticon as the fist character in a group name, this now looks better
- one thing less to explain
- the other icons stand out more, eg. the verification-icon
- it is some work to maintain a group icon for all situations, this can be better spent for other things
- also, neither telegram, nor signal, nor …

remove group icon from chatlist

---

res/values/strings.xml
res/xml/preferences_advanced.xml
src/org/thoughtcrime/securesms/connect/DcHelper.java
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java

this pr adds an option to the "Advances settings" dialog that allows to set the bcc_self option in the core.
this allows users to _not_ send messages to theirself which may be useful in some situations (eg. safe traffic, avoid double notifications)
screenshot:

add a switch to set the bcc_self option

---

AndroidManifest.xml
build.gradle
src/org/thoughtcrime/securesms/components/camera/QuickAttachmentDrawer.java
src/org/thoughtcrime/securesms/connect/KeepAliveService.java

this pr targets issues related to android9 and targetSdk29
with chance, both issues are done. i could reproduce the problem in the emulator, startForeground() throws an exception as the corresponding permission was not granted using android9. this is fixed by this pr.
on android8, probably, the foreground was not started at all, not sure though.
closes #1064
closes #1008

upgrade targetSdkVersion

---

src/org/thoughtcrime/securesms/notifications/AbstractNotificationBuilder.java

Enable heads-up notification and fix notification delay on android 9 (if device is muted)

Changed Notification level for Android8+

---

jni/dc_wrapper.c

add missing includes to jni, without them, args default to int which fails on 64bit. for whatever reason, the android compiler does not throw a warning.
a testing apk is at https://testrun.org/deltachat-gplay-release-0.930.2.apk
good catch, @link2xt :)

add missing includes to jni

---

res/values-sw360dp-v13/values-preferences.xml

found at https://stackoverflow.com/questions/51518758/preferencefragmentcompat-has-padding-on-preferencecategory-that-i-cant-get-rid/52960668#52960668

apply a hack that removes the padding from the settings screens

---

AndroidManifest.xml
build.gradle
jni/Android.mk
jni/Application.mk
jni/dc_wrapper.c
ndk-make.sh

because of issues as https://github.com/deltachat/deltachat-android/issues/1116 , but also to not use too outdated libraries, we have to change the used ndk from the used r14b or so to the most recent r20b.
this requires some adaptions:
- r20b does support a minimal sdk16 only, so we can no longer got for minSdkVersion=14
- 64bit supports minSdkVersion=21, not sure if that can be mixed
- there is no longer a script to install a toolchain, instead r20b comes with some predefined toolchains
- r20b seems to look in AndroidManifest.xml for minSdkVersion, not sure, however.
- clang is used as linker, c++_static as standard library
so, currently, we're using minSdkVersion=21 everywhere - which makes things compiling and working. this would drop support for android4 (ice cream sandwich, jelly …

adapt to ndk r20b

---

src/com/b44t/messenger/DcContext.java

the issue was that the java-part of the wrapper function was declared as `int` where it should be `long`.
moreover, this pr moves `checkQrCPtr()` to the private part together with the other CPtr functions.
closes #1128

fix qr-code scanning on 64bit andoird

---

jni/dc_wrapper.c
src/com/b44t/messenger/DcContext.java
src/org/thoughtcrime/securesms/ConversationListActivity.java
src/org/thoughtcrime/securesms/components/reminder/DozeReminder.java
src/org/thoughtcrime/securesms/notifications/MessageNotifier.java

todo:
once things are settled on android, it should be pretty easy to port them to ios and desktop
later on, we can add also move the the old-version-thingie as well as the battery-question to the device-msg.
needs https://github.com/deltachat/deltachat-core-rust/pull/854 and https://github.com/deltachat/deltachat-core-rust/pull/856 and https://github.com/deltachat/deltachat-core-rust/pull/939 to be merged first.

add device msgs

---

src/org/thoughtcrime/securesms/search/SearchRepository.java

when a query is given to getChatlist(), DC_GCL_NO_SPECIALS is not needed

remove unneeded flag

---

AndroidManifest.xml

this pr removes the probably unneeded [SET_WALLPAPER](https://developer.android.com/reference/android/Manifest.permission.html#SET_WALLPAPER) permission that seems to be needed for [setWallpaper()](https://developer.android.com/reference/android/content/ContextWrapper#setWallpaper(android.graphics.Bitmap)) only, which, however, is not used by delta currently - and there are also no plans to do so - esp. as the mentioned function is already deprectated ... ;)
cmp https://github.com/deltachat/deltachat-pages/pull/217

remove unused SET_WALLPAPER permission

---

src/org/thoughtcrime/securesms/profiles/AvatarHelper.java

android currently use a cached file of the avatar that is the same as in the core (by some refactoring, we could use the same files, however, this is out of scope of this pr)
in the past, the filename of the avatar was the email address, so sth. as foo@example.org - which the results in avatar.org with unknown mime type.
this pr just adds the extension .jpg - this may result in core having a different file, however, _currently_ the core waits for a call to dc_set_config(selfavatar) before acutally sending files out, so things will be in sync then. the selfavatar is currently never _read_ from the core.
fixes #1156

fix avatar extension

---

res/values/strings.xml
src/com/b44t/messenger/DcContact.java
src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/ConversationListFragment.java
src/org/thoughtcrime/securesms/components/reminder/DozeReminder.java
src/org/thoughtcrime/securesms/util/Prefs.java

this pr moves the doze-reminder from a system-thing that users typically click away fast to a device-message.
this way, the user can come back to the information when the problem actually arise for them.
also, things are re-doable this way (the user can change the setting several times)
maybe the text needs some adaption, however, as the current text is already translated in most languages and we're close to a release, i do not change that.
also, it may make some sense to link to https://dontkillmyapp.com if the message is clicked although background-things are already allowed.
closes #1152

move doze reminder to device-chat

---

ndk-make.sh

CPATH needs to be set in order to compile deltachat iOS whareas deltachat android builds fail if CPATH is set
@r10s can you please verify that this change has no effect on mojave?

fix builds for MacOSX Catalina

---

src/org/thoughtcrime/securesms/connect/NetworkStateReceiver.java

theoretically, dc_maybe_network() can be called from the main thread and returns at once,
however, in reality, it does currently halt things for some seconds.
this is a workaround that make things usable for now.
closes #1176

call dc_maybe_network() from a worker thread.

---

src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/ProfileDocumentsFragment.java
src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java

fixes #1154 by force using an Activity-context. this seems to be needed for Android 9, tried opening a pdf in an emulator with Android 9 and this works - without this fix it fails as described in #1154
i am unsure if FLAG_ACTIVITY_NEW_TASK is still needed for SDK <= 23 (Android 6, Marshmallow), the documentation is unclear to me here, https://developer.android.com/reference/android/content/Intent.html#FLAG_ACTIVITY_NEW_TASK, and it was introduced for some reasons at https://github.com/deltachat/deltachat-android/pull/741 ,  however, probably it is fine. but i will try to test this explicitly.

use Intent.ACTION_VIEW from an Activity-context

---

src/org/thoughtcrime/securesms/ConversationActivity.java

do not try to recode videos when attached as files; esp. if the detection with isVideoType() fails (videos may be images with wrong extension/mimetype), this gets annoying
closes #1174

do not recode when attaching files

---

src/org/thoughtcrime/securesms/notifications/MultipleRecipientNotificationBuilder.java
src/org/thoughtcrime/securesms/notifications/SingleRecipientNotificationBuilder.java

just that we do not forget about that when we rework the notification issues.
setNumber() does the trick with the badges on newer androids, see https://github.com/deltachat/deltachat-android/issues/1189

add comment about badge-count hint

---

ndk-make.sh
src/org/thoughtcrime/securesms/ConversationActivity.java

This change causes a save of the current draft in the 'onPause' event.
I can't see an unwanted side effect.

Fix743lost draft on pause

---

src/org/thoughtcrime/securesms/notifications/MessageNotifier.java

fix #1197 
When the uri comes in with a `null` state the ringtone sometimes is build but with an internal ­­­­broken uri.
So this fix removes the creation and call to the ringtone altogether if it is null to begin with.
Should have no side effects.

Fix not trying to play a sound when -no sound- has been selected.

---

res/layout/group_create_activity.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/GroupCreateActivity.java

this pr adds a small text that explains what is a "verified group". up to now, this was completely missing.
moreover, as there may be os-stores that do not allow beta/experimental stuff, we removed the string "experimental" from the main option, it lives on, a bit tuned down, in the explanation.
cc @hpk42

add verified group hint

---

src/org/thoughtcrime/securesms/ConversationActivity.java

this is an addition to #1192:
by calling processComposeControls() twice, in onPause() and on Destroy(),
the seccond call gets an empty draft.
as onDestroy() is not guarateed to be executed anyway -
this was the intent of the move in pr #1192 -
we just remove this call and rely on onPause().
see https://developer.android.com/reference/android/app/Activity.html
for lifecycles and killable events.
closes #1220

fix saving drafts

---

build.gradle
jni/Application.mk
ndk-make.sh

this pr lowers the sdk to 16 so that Android 4.1 Lollipop becomes fully available again (before, we target sdk18 (android 4.3, also Lollipop). in between, the change was needed because of some rust libraries that were use, however, they have been replaced by sth. else so that this is no longer a target. we cannot go lower than sdk16 as this is no longer supported by the used devlopment tools.
this should only be merged if there are no problems, esp. on newer androids (which are >90% compared to 3% this pr will gain in additiony)
targets #1212

lower sdk to 16

---

res/values/strings.xml
src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java

after discussing with @Simon-Laux, @Jikstra and others, we decided on renaming 'new chat' in the profile view to 'send message'. 'new chat' (and also 'open chat' on desktop) is a bit misleading as the corresponding chat may or may not exist.
also, the wording 'send message' in the profile is also used on other messengers eg. in telegram.

rename 'new chat' to 'send message'

---

src/com/b44t/messenger/DcContext.java
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationListActivity.java
src/org/thoughtcrime/securesms/ConversationListFragment.java

this pr streamlines the ui, by removing some superfluous alerts and by re-ordering the forward-dialog so that "saved messages" is always one of the first entries.
the pr relies on https://github.com/deltachat/deltachat-core-rust/pull/1336 , so that should be merged before and the core should be updated afterwards.
closes #1007

less clicks on save-message and start-chat

---

CHANGELOG.md

4.1 codename is "Jelly Bean", not Lollipop

Fix Android codename in the changelog

---

src/org/thoughtcrime/securesms/ConversationListActivity.java

I found it out.
How to reproduce:
- uninstall and re-install Delta Chat
- login
- click "Share" in another app
- select "Saved Messages"
We now have a code duplicate (in onNewIntent and in onCreate), but I was unsure if both codes should go into another method and how it should be called. `refresh`? `init`?(also, the codes of these were already very similar before this PR).

Fix #1028, make sharing directly to a chat work always

---

res/menu/conversation.xml
res/menu/conversation_muted.xml
res/menu/conversation_unmuted.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationAdapter.java
src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/mms/AttachmentManager.java

closes #1217 and closes #1284 (not really related, but as the menu is reworked in this pr, it makes sense here to avoid merge conflicts)

in chat search

---

res/menu/conversation.xml
res/menu/local_help.xml
src/org/thoughtcrime/securesms/BaseActionBarActivity.java
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/LocalHelpActivity.java

the result counters are shown as `12/34` beside the arrows to loop through the result. for "no result", `0/0` is shown and for "no search", the counter is hidden.

add result counters to in-chat and local-help searches

---

res/layout/registration_activity.xml
res/values/strings.xml

improve wording to make more clear, this is sign-in, not-sign up.
this pr changes the text "password" to "existing password".
the idea was also to change the text below the field to "Please login to your e-mail server using your existing e-mail address and password" or - however, this would at least partly only repeat the headline and the labels. also the existing hint seems to be important and, we're talking about ppl that do not really read hints, so adding more of them is maybe not helpful
so, i think, we can maybe just go for the small change and see if this already helps. it is also not that we get tons of complains to that - but i think the "no delta servers" actually helped to avoid scaring people.

sign-in vs. sign-up

---

res/layout/profile_preference_view.xml

fix is needed only for the first settings item, that is owner-drawed.
the other standard items were already correct.
closes #1293

force right-to-left item on right-to-left locales

---

Dockerfile

In https://github.com/deltachat/deltachat-core-rust/pull/1398, the rust toolchain was changed back to 2020-03-12, but the Android Dockerfile even missed the update to 2020-04-10 in between.
We realized this when the Android Nightlies stopped building.
On this branch, the build on b1.delta.chat works again.

updated docker toolchain

---

src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java

discard (accidental) taps outside the autodel-confirmation dialog

---

src/org/thoughtcrime/securesms/connect/AccountManager.java

in the account switcher, do nothing if switching no new account was selected
prevent switching accounts if the currently selected account was tapped,
just close the dialog in this case.
(ux wise, it is better to show the current account - to get some overview
and also to easily see what the current account is)

tweak "switching" to already selected account

---

src/org/thoughtcrime/securesms/ConversationListFragment.java

Just by chance, I got DC to crash. I must somehow have long-pressed an item while it was finishing. Anyway, I found the responsible line in the logs and this should not happen anymore with this fix.

Fix Null-Pointer-Exception

---

src/org/thoughtcrime/securesms/CreateProfileActivity.java
src/org/thoughtcrime/securesms/contacts/avatars/LocalFileContactPhoto.java
src/org/thoughtcrime/securesms/contacts/avatars/MyProfileContactPhoto.java
src/org/thoughtcrime/securesms/profiles/AvatarHelper.java

Ask the core for the selfavatar directory, fix https://github.com/deltachat/deltachat-core-rust/issues/1381 backup export/import loses self-avatar
The problem was: DC-Android did not care about what the core said about the self-avatar, it just put a file with the own email address into a folder called "avatars". Of course, this folder was not backed up. Also, we had the self avatar multiple times, once in the blobs directory and once in the directory called "avatars" (probably a leftover of the Signal code).

Ask the core for the selfavatar directory, fix "backup export/import loses self-avatar"

---

jni/dc_wrapper.c
src/com/b44t/messenger/DcContext.java
src/org/thoughtcrime/securesms/WelcomeActivity.java
src/org/thoughtcrime/securesms/connect/AccountManager.java
src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java

this pr stops threads and call close() on switching account.
the imap-/mvbox-/sentbox-/smtp-threads needs to be terminated before dc_close() can be called successfully.
if this is not done, the threads are hanging around, and, even worse, if an account is opened _again_, there are now two threads working on the database which lead to duplicated messages.
note, that this issue is only related to duplicated messages if ever an account was selected, which, however, might be the same as the current.
fixes https://github.com/deltachat/deltachat-core-rust/issues/1404
EDIT: the last few commits move the account switching to an async task

stop threads when switching between mupltiple accounts

---

src/org/thoughtcrime/securesms/ConversationListFragment.java
src/org/thoughtcrime/securesms/connect/AccountManager.java
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java

File.delete() only delete empty directories, this was not considered before.
moreover, this pr shows a toast, when deletion fails (there were some reports that databases are not deleted, maybe this helps to figure that out)

fix blobdir-deletion on account-deletion

---

res/values/strings.xml
res/xml/preferences_notifications.xml
src/org/thoughtcrime/securesms/LogViewFragment.java
src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
src/org/thoughtcrime/securesms/connect/KeepAliveService.java
src/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java
src/org/thoughtcrime/securesms/util/Prefs.java

successor of https://github.com/deltachat/deltachat-android/pull/1302 - in fact, there were still some conditions in the code left.
now, the permantent-notification is really always shown, however, we also add a switch to override this. the wording of the switch, however, makes pretty clear that this is not encouraged:

show permanent notification unconditionally and add a switch to override this

---

src/org/thoughtcrime/securesms/ApplicationContext.java
src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java

The IncomingMessageNotifier was not initialized again after switching accounts.
This now also contains Björn's PR in the hope of having no merge conflicts.
~Code style might need improvements.~
Update: DC_EVENT_INCOMING_MSG is now handled directly in handleEvent().
sendToObservers() made sure not to execute it on a background thread but updateNotification() does this, too, so everything is fine. (and no, I won't use fallthrough for this :wink:)

Fix #1328 Missing notifications: initializeIncomingMessageNotifier() in ApplicationDcContext, not ApplicationContext

---

res/values/strings.xml

this pr tweaks the device-message that explains the permantant-notification, esp. it point out that it also acts as an indicator that things may not work as expected and make the link to dontkillmyapp.com clearer.
if we can merge this is quickly, there are changes that it gets translated :)

tweak device-msg that explains the permantent-notification

---

src/org/thoughtcrime/securesms/contacts/ContactAccessor.java

this pr makes sure, dc_add_address_book() does not get names or mail addresses with lineends.
if, for whatever reason, this happend in the past, name and mails could get ot of order, fixes #1334

fix calling dc_add_address_book()

---

src/org/thoughtcrime/securesms/notifications/MessageNotifier.java

I looked around in the code a bit to see what implications my change might have.
The only one I found is that `NotificationState.removeNotificationsForChat(int)` is not called and `NotificationState.notificationCount` is not decreased. This should be just fine because `notificationCount` is used to show an unread message count. Here, it is expected behavior that the unread message count does not decrease just because the message was swiped away.

Fix #999 swiping a notification away should not mark things as "noticed"

---

src/org/thoughtcrime/securesms/ConversationActivity.java

Fix #1305 An object (image), "shared" to Delta Chat once, appears again forever in Chat editors until app is closed
The problem was that the intent still had the share flag and data. When opening a new chat, DC thought that we had just shared something.
A draft is now initialized (and stays) so that the user can return to sending later.
Also fixes #1317 (just tested it, don't think it's worth debugging why it fixes this)

Fix #1305 An object (image), "shared" to Delta Chat once, appears again forever in Chat editors until app is closed

---

src/org/thoughtcrime/securesms/notifications/MessageNotifier.java

Reverts deltachat/deltachat-android#1277
closes https://github.com/deltachat/deltachat-android/issues/1353
reopens https://github.com/deltachat/deltachat-android/issues/999 
i think the original behavior was better, the reappearing is pretty annoying and not intended, esp. as the messages reappear _at once_ when another chat is opened.
this is because of the re-adding of all notifications instead, which was needed for some needed hacks on the notification-channels. i will to a general cleanup.

Revert "Fix #999 swiping a notification away should not mark things as "noticed""

---

build.gradle

Changes exoplayer Version from 2.9.1 to 2.9.6. Most current is 2.11.4, but I didn't invest time to figure out if we need any of the new features.
exoplayer Release notes contain also this line:
2.9.3 Fix regression where some audio formats were incorrectly marked as being
unplayable due to under-reporting of platform decoder capabilities
There are also some other fixes that might be beneficial to us, even if we didn't encounter them yet.

bump exoplayer version to 2.9.6 becaus of some fixes that apply to us

---

jni/dc_wrapper.c
src/com/b44t/messenger/DcChat.java
src/com/b44t/messenger/DcContext.java
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationListItem.java
src/org/thoughtcrime/securesms/ConversationTitleView.java
src/org/thoughtcrime/securesms/MuteDialog.java
src/org/thoughtcrime/securesms/ProfileActivity.java
src/org/thoughtcrime/securesms/components/FromTextView.java
src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
src/org/thoughtcrime/securesms/database/model/ThreadRecord.java
src/org/thoughtcrime/securesms/notifications/MessageNotifier.java
src/org/thoughtcrime/securesms/notifications/MessageNotifierPreApi23.java
src/org/thoughtcrime/securesms/util/Prefs.java

Fix #1338.
Muting and unmuting now takes about 0.1s while it was instantly before, but I guess it's not worth improving this. And maybe it is improved by https://github.com/deltachat/deltachat-core-rust/pull/1492.
Du you think that I should inline the Prefs.*mute*() functions?

Use the mute functions of the core

---

src/org/thoughtcrime/securesms/ConversationListItem.java

this bug was introduced some days ago at adce890bef0d54cdacdcb6eddc46afc67a653fb2
by declaring chatId as "int" instead of "long", which is formally correct,
however, int many parts of the code, the chatId is "long" -
as for the set of selected chats:
checking that set for an "int" always returns false ...
i first wanted to change all the sets to use int instead of long,
however, this would require lots of lines to be change -
keeping in mind that this seems to be very sensitive,
and use "long" for the chatId in ConversationListItem.
doing a larger refactoring of Long to Int has the potential to introduce more bugs,
things are not that intuitive in this area -
i would also not have exected that i cannot query a set of longs using an integer,
when using primitives (i know, they are …

fix showing selected chats

---

src/org/thoughtcrime/securesms/ConversationFragment.java

closes #1380 
before, messages were only maked as seen after the chat was entered
or after some scrolling takes place.
if a user was inside a chat, reading the last incoming message,
that did not sent out markseen (unless, some scrolling was done,
which, honestly, is often the case)
this commit starts the markseen-bouncer also when the chatlist is reloaded
(true eg. on incoming messages) - but this is not done when the
list is paused (eg. screen is off or some other fragment/dialog above)

fix marking incoming message as being seen

---

ndk-make.sh

really use the toolchain defined in the core-rust-submodule

---

src/com/b44t/messenger/DcContact.java
src/com/b44t/messenger/DcMsg.java

fixes #1071 
The issue there is that batchSelected in ConversationItem is a HashSet. Then we use the 'contains' function of it to see if the item that should currently be displayed is within the selected set.
HashSet.contains does not check the equals function, but just memorizes the hash code.
As hashCode must have the same behavior as equals I added the check for id=0.
If we can create an assertion that id is never 0 we should strip the check in equals and hashCode.
This change could change the behavior of all sorts of places where HashSet/HashMap of DcMsg is used, not just the one we are in right now. I did a quick check and everything looked fine but I think this change should be put to longer beta testing in a nightly before being rolled out.
There is a secondary finding that takes …

Implementing hashCode in DcMsg.

---

res/layout/conversation_activity.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/preferences/ChatBackgroundActivity.java

I mirrored the activity of the ImageView on the Background setting view (as it was working there properly) in the conversation activity.
Then I modified the transformation during Background setting to create an image that is scaled down to the larger sides of the screen (so the scaling is indifferent at this stage to portrait/landscape).
When active the users will need to set his background image once so that the old image (that was cropped too much) is removed and a new one is set.
It could be a good idea to inform the user in the system messages about that change.
fixes #466

Background image no longer distorted.

---

res/layout/registration_activity.xml
res/values/arrays.xml

the option 'accept invalid hostnames' does not longer exist, see https://github.com/deltachat/deltachat-core-rust/pull/987

remove option 'accept invalid hostnames'

---

res/layout/profile_activity.xml
res/menu/profile_chat.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/CreateProfileActivity.java
src/org/thoughtcrime/securesms/MediaPreviewActivity.java
src/org/thoughtcrime/securesms/ProfileActivity.java

fixes #1228
Tap on the avatar in a profile to see a large version of it. Tap the large one to make it small again.
Should be discussed if the size of the overlay is proper.
I also noticed that I cannot modify a contacts avatar (as we can with their name). We might want to allow to at least intentionally delete / suppress it.

Allow enlarge of avatar

---

src/org/thoughtcrime/securesms/util/DynamicLanguage.java

Fixes #1209
To reproduce the bug this fixes the App needs to START with a Language that is not the System default. In doubt restart your phone after selecting a non-default language.
Code wise this change modifies the way the system default language is read. Currently `Locale.getDefault()` is used but this returns the locale the app was started in (and I suspect that it is the same it terminated the last time).
The new code is from here https://stackoverflow.com/a/28498119/881272

Switching to "Default" Language behaves as it should be

---

res/menu/media_preview.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/CreateProfileActivity.java
src/org/thoughtcrime/securesms/GroupCreateActivity.java
src/org/thoughtcrime/securesms/MediaPreviewActivity.java
src/org/thoughtcrime/securesms/ProfileActivity.java

fix opening avatar-preview, getBaseContext() is not needed and led to…crashes on some android versions as this context might not be an Activity
moreover, this pr streamlines some things:
- open enlarge-avatar-view on title-bar-tap (not only avatar-tap) - this is the way we also open the profile-view
- add an edit-button to the  enlarge-avatar-view
- use the wording already present, in use and translated.
- revert Glide change (see commit history for further explanations)
still unsolved is what happens when there is no avatar to enlarge - currently the empty view opens, with the option to edit. this can be improved (maybe show fallback, maybe show some hints, maybe do not enlarger at all), however, i think this should be part of a follow up.
fixes #1399

fix opening avatar-preview

---

src/org/thoughtcrime/securesms/ConversationListFragment.java

The problem was that the list was not always updated before and after
sharing. Now it always correctly shows or does not show the devicetalk.
@r10s

initializeListAdapter() in ConversationListFragment.onNewIntent()

---

src/org/thoughtcrime/securesms/ConversationListFragment.java

Reverts deltachat/deltachat-android#1402
the call is expensive. it forces a reloading of the chatlist everytime, the user hits "back" from inside a chat and led to a half-second-delay and a flickering.
i think we have to solve the share-update a bit smarter.

Revert "initializeListAdapter() in ConversationListFragment.onNewIntent()"

---

src/org/thoughtcrime/securesms/ShareActivity.java

so that the conversations list is correctly updated before and after
sharing. Now it always correctly shows or does not show the devicetalk.
Second try after
https://github.com/deltachat/deltachat-android/pull/1402.
@r10s I tried again :wink:. 
I got to the idea because with forwarding everything worked fine and with forwarding startActivityForResult() is used:
private void handleForwardMessage(final Set<DcMsg> messageRecords) {
Intent composeIntent = new Intent(getActivity(), ConversationListActivity.class);
int[] msgIds = DcMsg.msgSetToIds(messageRecords);
setForwardingMessageIds(composeIntent, msgIds);
startActivityForResult(composeIntent, REQUEST_RELAY);
getActivity().overridePendingTransition(R.anim.slide_from_right, R.anim.fade_scale_out);
}
In my tests everything worked fine.

start ConversationListActivity with startActivityForResult()

---

AndroidManifest.xml
src/org/thoughtcrime/securesms/ConversationListActivity.java
src/org/thoughtcrime/securesms/notifications/MarkReadReceiver.java
src/org/thoughtcrime/securesms/notifications/NotificationCenter.java

this pr creates a normally invisible summary-notification; this is needed to let android7+ let respect the group set by setGroup()
todo:
- ~~we have to dismiss the summary manually when we cancel notifications on our own by entering a chat~~ EDIT: done
- taping on the summary should open the chatlist
setting a correct title/text seems not to be needed as this is not displayed anyway.
using the summary on android<7 - i have not tested that, however, the system does not group much there anyway, so maybe things are already fine (enough).
in theory, we could _only_ show the summary on android<7 to have less notifications at all, however, of course, this would require setting the correct text/title and this can be part of another pr.
closes #1413

improve notification grouping

---

jni/Application.mk
ndk-make-fast.sh
ndk-make.sh

Sorry for the click-bait title, but it fitted too well :wink: :tada: 
Anyway, I added the possibility to ndk-make.sh to compile only for one
arch.
In my tests, if I also set the optimisation level to 0 (default is 3),
the compilation time went down from 3:30 to 1:20. Not sure if this is
worth it because I remember a comment stating that this makes generating
keys take forever. Maybe I should do some measurements and experiment
with levels 1 and 2 but that's for another PR.
What do you think?
Also - NO MORE WAITING 20MIN FOR COMPILATION TO FINISH!!!!!!!!!!!!!!!! :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: …

You won't believe how this makes the compilation 4x faster!

---

res/layout/conversation_activity.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/preferences/ChatBackgroundActivity.java

this pr reverts #1372 and fixes the new bug #1417 -by that, #466 gets reopened.
i think, the jumping background image on opening/closing is worse than having a calm background image with maybe bad aspect ratio.
in other words, this pr makes things as good or as bad as in the current releases.
of course, in a subsequent pr, both things will be fixed, however, that is not that simple as it appears first.

quick-fix background jumping

---

src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java

this is needed with the new async-core
counterpart of https://github.com/deltachat/deltachat-ios/pull/805
should be merged once https://github.com/deltachat/deltachat-core-rust/issues/1647 is fixed.

restart-io when watch-settings are changed

---

src/org/thoughtcrime/securesms/connect/AccountManager.java

account-database-names have the format messenger*.db -
only checking for the extension will offer eg.
mapbox cachefiles in the account switcher (mbgl-offline.db)
fixes #1440

more accurate check of account-database-names

---

res/drawable/emoji_variation_selector_background_light.xml

in light mode, input field and emoji popups are both white,
therefore opening the emoji popup (used eg. for diversified emojis)
in the first line looks weird, you do not really know
if the display is part of the emoji picker or of the input field.
fixing that by adding a small border around the popup.
in dark mode, things are already fine.

improve layout of emoji popups

---

src/org/thoughtcrime/securesms/components/emoji/EmojiKeyboardProvider.java

Fixes #1438 - tapping the same emoji position twice results in the same emoji now, also on the recent tab.
This reverts commit 6aec743e4dfb907b9cc667a0969ffceb98e24fe4 (including its POSITION_NONE behavior, that may led to performance issues as this always says "this item is no longer valid, please recreate) and synchronizes the corresponding code to the signal upstream.
wrt the original issue, that some emojis are not added instantly (https://github.com/deltachat/deltachat-android/pull/1410#pullrequestreview-430162678) - this seems to be a minor issue compared to #1438 - esp. as the list is always updates onces the keyboard is reopened (the same issue is upstream, btw).

Revert "fix recent emoji updates"

---

jni/dc_wrapper.c

dc_array_get_raw API prevents Rust code from storing IDs in other format
than an array of uint32_t.
iOS code and node bindings (see `dc_array_to_js_array`) already use `dc_array_get_id` loops, Android client is the only user of this API.

jni: use dc_array_get_id instead of dc_array_get_raw

---

res/menu/conversation.xml
res/values/arrays.xml
res/values/strings.xml
res/xml/preferences_advanced.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/EphemeralMessagesDialog.java
src/org/thoughtcrime/securesms/util/Prefs.java

on top of #1457 
* simple UI to select ephemeral messages
* experimental feature switch in settings
* show ephemeral messages only if feature switch was enabled or ephemeral messages was already enabled (e.g. from another device)
Closes #1458

Ephemeral messages ui

---

res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationListFragment.java
src/org/thoughtcrime/securesms/util/RelayUtil.java
src/org/thoughtcrime/securesms/util/SendMessageUtil.java
src/org/thoughtcrime/securesms/util/SendRelayedMessageUtil.java

Fix #1340.
Also, I did extensive testing of message relaying:
- I. share and II. forward
- a. text
b. text and one image
c. 2 images
d. 1 file (unknown type)
e. 2 files (unknown type)
- to:
1. 1 chat (just tap on it)
2. If applicable: go back and forth a bit to test drafts
3. 2 chats (multi-relaying)
and some of the bugs I found and fixed were probably already there before, although I did not test this.
After fixing things, I went through this list again and everything worked.
Seems like at some places in the UI the chatId is saved as a long, which seems not to make much sense because the core saves them as int. Anyway, I had to cast them.

Relay to multiple contacts, rework message relaying

---

res/values/arrays.xml
src/org/thoughtcrime/securesms/EphemeralMessagesDialog.java

Selecting 1 minute actually set timer to one hour and there was no
"one hour" option in the menu.

Fix mismatch between ephemeral options and strings

---

res/menu/conversation.xml
res/values/strings.xml
res/xml/preferences_advanced.xml
src/org/thoughtcrime/securesms/EphemeralMessagesDialog.java

- For chat menu item, use already translated auto-delete string.
- For experimental setting, use untranslatable hard-coded string.
- Introduce a new translatable string for ephemeral dialog title

Update strings used for ephemeral messages

---

src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationListFragment.java

fixes #1472 
I found some more issues on current master, partly introduced by #1341 
* when forwarding messages the Activity stack order was broken, multiple Activity List views could appear ( fixed by
20189fd )
* when forwarding is finished, the user always returns to the original chat a it was intended before #1341
* when sharing images, they couldn't kept as drafts (now fixed by 69b587c ) 
* 69b587c also now disallows to go the following path: share menu -> conversation list -> chat a -> back to conversation list -> back b, it caused troubles in the pre #1341 implementation while the fix in #1341 introduced the above mentioned draft bug. Instead the user can only jump into one chat or select mulitple chats from the chat list by long press on the list conversation items, going back will …

Fix mailto links

---

res/values/arrays.xml
res/values/strings.xml
res/xml/preferences_chats.xml
src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java

This change makes it clear which messages are deleted, so this setting
can't be confused with Ephemeral-Timer header, configured per chat.

Rename "Auto-delete messages" into "Delete old messages"

---

src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/notifications/NotificationCenter.java

for https://github.com/deltachat/deltachat-core-rust/pull/1613 (we might also have to do this for Desktop and IOS)

Generally show device message notifications, open password settings if the user clicks on a "wrong pw" message

---

res/drawable/ic_timer_gray_18dp.xml
res/layout/conversation_title_view.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationTitleView.java

just a small hint, a first step :) the icon appears and reappears when ephemeral state is changed either locally or remotely.
i decided to tune the icon down to:
- not to be too annoying when ephemeral mode is enabled "always" with large timeouts, in this case, an always appearing "warning" seems to be too annoying
- the mode should not be too outstanding - as we cannot guarantee that things are delete on other devices at all
- there will be an additional icon beside each message as well, maybe even animated as on signal - that will also be very obvious
i also played around an icon in the chat (as for location), however, decided against that, for reasons mentioned above and also because the idea of the location being part of the chat window is that actually messages are emmited when this …

show ephemeral state in title

---

src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
src/org/thoughtcrime/securesms/connect/NetworkStateReceiver.java

instead, when receiving the first network-error when being offline,
the text is substituted to "No network"
and all subsequent network-errors are ignored -
until NetworkStateReveiver reports being online again,
then the state is reset.
in fact, in the last versions not network-errors were reported at all (but normal errors were - and some of them were network-errors). reason was that android relied on the first-network-error flags, that, however, does not exist since some time, see documentation changed in the linked rust-pr.
successor of https://github.com/deltachat/deltachat-core-rust/pull/1740, closes https://github.com/deltachat/deltachat-android/issues/1490

do not show series of network errors while offline

---

res/layout/activity_select_chat_background.xml
res/layout/conversation_activity.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/components/ScaleStableImageView.java
src/org/thoughtcrime/securesms/preferences/ChatBackgroundActivity.java

continues where #1429 left off due to rebase issues.
fixes #466
When finished needs to:
-   Keep aspect ratio of background image in landscape and portrait orientation in the chat view
-   Fill screen with image (no empty borders)
-   Maintain position when the keyboard is opened.
@cyBerta Your suggestion to move the `measureViewSize` call after the early return is included.

background image scaling good without jumping (2)

---

res/layout/dialog_extended_options.xml
src/org/thoughtcrime/securesms/EphemeralMessagesDialog.java

successor of https://github.com/deltachat/deltachat-android/pull/1503
headline and buttons have about 20dp padding,
the the same for left/right,
adapt top/bottom to look good in combination with headline and buttons.

tweak padding of disappearing messages options

---

src/org/thoughtcrime/securesms/connect/AccountManager.java

The context contains the proper translations to be used by the core ("stock translations")
After a context switch they are unset.
This change sets them so they are of the appropriate language again.
fixes #1502

setting stock translations after context switch

---

src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/NewConversationActivity.java
src/org/thoughtcrime/securesms/mms/AttachmentManager.java

proposal to simplify the code. Since we're saving drafts to the database while `handleSharing()` and do `immediatelyRelay` for all cases we do forwarding  (see ConversationActivity for the details) all we need to do is to distinguish between sendto: links or loading drafts from the database in `initializeDraft()`
@Hocuri Unfortunately I lost my phone so I don't have telegram or whatsapp. Signal/wire doesn't allow to share both text and images. Could you please try if sharing both works with this PR?
I also removed the AsyncTask which was only there to load a message object. I don't think this is needed and it seems to be a relict from old Signal code.

Fix sharing again 2

---

src/org/thoughtcrime/securesms/components/ScaleStableImageView.java

Almost fix #1544 image rotation not working sometimes.
I did not find any better way to do this. Now it is not crashing anymore but it jumps again.

Almost fix #1544 image rotation not working sometimes

---

res/menu/conversation_unarchive.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationListArchiveActivity.java

fixes #1557 
* moreover it removes the intent extra `IS_ARCHIVED_EXTRA` that gets set when sending the activity intent. Instead we're using the core's chat visibility function `dc_chat_get_visibility` in order to distinguish beween archived and unarchived chats.

update archive menu option, rely on core for chat visibility

---

src/org/thoughtcrime/securesms/components/camera/QuickAttachmentDrawer.java

fixes #1549 
it is 'inspired' by the way the Flip button works: https://github.com/deltachat/deltachat-android/blob/master/src/org/thoughtcrime/securesms/components/camera/CameraView.java#L264
however the aspect ratio is still awful (at least on my device), but that's an unrelated issue.

reinitialize camera on orientation change

---

src/org/thoughtcrime/securesms/NewConversationActivity.java

* removes leading and trailing empty spaces from email adresses, so that rust core will consider email adresses as valid
* replaces call to deprecated url decode method

Improve mailto link parsing

---

res/values/strings.xml

removing unneeded strings makes work of translators easier
and also, in sum, saves some amount of data.
checked by ./tools/grep-string.sh that the strings are not in use by other os.
as checking is some work, i only targeted low hanging fruits,
there may be some more strings unused.

remove unused strings

---

src/org/thoughtcrime/securesms/WelcomeActivity.java

the startIo() call after scanning a burner account was just missing,
putting the app for a second to background fixes the issue,
so it was maybe not that visible.
the issue was probably introduced on the switch to async,
before, startIo() was not existant.
fixes #1598

connect immediately after burner account scan

---

src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/util/LongClickCopySpan.java

unfortunately, auto-linking such as Linkify.addLinks(WEB_URLS...)
replaces custom-links set before by Linkify.addLinks(custom-pattern).
calling custom-linking after auto-linking may be too inaccurate
as in case of bot-commands such as /xkcd_123456
are treated partly as a phone number.
skipping auto-linking is hard as there are lots of things to do to get a
similar experience, see #1600.
finally, we solve the problem by replacing URLSpan by some other span after.
in fact, we do that anyway to get a different long-click behaviour.
the only important thing is that the span-replacement
must not be derived from URLSpan.
fixes #1600
reverts the pattern-approach of #1567 and targets https://github.com/deltachat/deltachat-android/pull/1570#pullrequestreview-468412214

use auto-linkify together with custom-linkify

---

CHANGELOG.md
build.gradle

bugfix-release, core is the same, but the fixed android4 notifications are probably worth an update.

prepare 1.12.5

---

src/com/b44t/messenger/DcContext.java
src/org/thoughtcrime/securesms/RegistrationActivity.java
src/org/thoughtcrime/securesms/connect/DcHelper.java

this pr splits server_flags into server_flags/mail_security/send_security.
by coincident (?), the DC_SOCKET values are equal to the ones used as index in the popups, so there is not much to do with the values :)
the pr also intentionally contains the updated submodule and can be merged if we do not get bad reports about 1.12.5 "soon" ;)
closes #1569 
counterpart to https://github.com/deltachat/deltachat-ios/pull/910

split server flags

---

build.gradle
res/layout/activity_map.xml
src/org/thoughtcrime/securesms/map/AddPoiView.java
src/org/thoughtcrime/securesms/map/MapActivity.java
src/org/thoughtcrime/securesms/map/MarkerView.java
src/org/thoughtcrime/securesms/map/MarkerViewManager.java

the map feature needed some love <3
* when adding a poi on the map, the corresponding AddPoiView gets centered on the map. This way the sent button is always reachable without scrolling.
* when the AddPoiView appears on the map, the keyboard layout automatically appears too, no need to tap another time into the EditText view to write the POI message
* if the AddPoiView gets cancelled, the keyboard disappears, too 
* sometimes the AddPoiView didn't show up at the right position on the map or it didn't move together with map movements. This has been fixed.
* updates map sdk (needed for centering feature)

Add POI improvements

---

AndroidManifest.xml
src/org/thoughtcrime/securesms/WelcomeActivity.java
src/org/thoughtcrime/securesms/connect/KeepAliveService.java
src/org/thoughtcrime/securesms/notifications/NotificationCenter.java
src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java
src/org/thoughtcrime/securesms/service/GenericForegroundService.java
src/org/thoughtcrime/securesms/service/NotificationController.java

used for import export 🚛 🚛 🚛 
closes #1447 
changes in Signals NotificationController and GenericBackground service:
* removed AutoCloseable Interface from NotificationController because it is only supported from API 19+
* instead we assure that the service connection to the GenericBackgroundService gets explicitly closed  in close()
* added possibility to add a contentText of a notification. It is used to display and update the percentage in the notification.

generic foregroundservice

---

res/values/strings.xml
res/xml/preferences_notifications.xml
src/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java

the switch fires the intent to request-ignore-battery-optimization the intent for opening battery-optimisation-settings (the latter on errors or if ignore-battery is already enabled - there is no direct way to revert ignoring).
targets #1477

add switch to enable/disable battery optimizations

---

res/values/strings.xml
src/org/thoughtcrime/securesms/components/reminder/DozeReminder.java

with #1505 we ask the user directly after configure to allow running Delta Chat in background.
while it is more straight-forward to let the system ask the user directly -
as we do for most other permissions -
this is probably not favorable for requesting ignore-battery-optimization:
- other permissions requests are preceded by a clear user intention -
tap on the camera, record voice etc.
so it is clear to the user why a permission is needed.
this is not true at the moment after installation
(maybe the moment can be improved, btw)
- different systems have completely different text,
partly focusing on "battery drain" - it is not clear to the user
what would be the advantage of that
- some guidelines say, user interaction is needed before querying permission.
there is room for …

add rationale to ignore-battery-optimization request

---

res/menu/conversation.xml
res/xml/preferences_advanced.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/util/Prefs.java

this pr removes the requirement to enable the experimental feature 'disappearing messages' before disappearing messages can finally be used.
the experimental feature is available and is tested since about two months and i think, it can become a normal feature now.
we also hesitated to enable the feature by default to ensure, recipients using Delta Chat actually follow the deletion requests, this is now the case since july and since several updates.
counterpart of https://github.com/deltachat/deltachat-ios/pull/919

make 'disappearing messages' a standard-feature

---

res/values/strings.xml
src/org/thoughtcrime/securesms/DummyActivity.java
src/org/thoughtcrime/securesms/PassphraseRequiredActionBarActivity.java
src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java
src/org/thoughtcrime/securesms/service/GenericForegroundService.java

second attempt of https://github.com/deltachat/deltachat-android/pull/1611
this pr closes many cases of https://github.com/deltachat/deltachat-android/issues/1610, esp. all on onboarding.
~~leaving the issue on export open - this is currently hard to fix as i do not found a way to cancel the intent given to onNewIntent() - before the back stack is modified. all things i've tried raises more problems than it solves. the prober solution would be to decouple things completely from activities, but this is quite some work and maybe not worth the effort. also, the new tar-export has probably a much smaller window where there database is not accessible.~~ EDIT: the export-issue is fixed for now by aborting the export when the app is relauched, to make this clear, a toast is shown.

fix launch if there is an ongoing process

---

src/org/thoughtcrime/securesms/LogViewFragment.java

- having this is the text has the advantage that the hint is
also in place when the log is already exported,
editing is maybe even easier later
- if needed, we can make the hint translatable at a later point,
not sure, however, if this is useful as most of the log is english anyway.
closes https://github.com/deltachat/deltachat-android/issues/1501

prefix log by a hint about sensitive information

---

res/values/strings.xml
src/org/thoughtcrime/securesms/RegistrationActivity.java
src/org/thoughtcrime/securesms/WelcomeActivity.java
src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java

errors that should be shown to the user
come from DC_EVENT_CONFIGURE_PROGRESS(data1=0) as data2 since https://github.com/deltachat/deltachat-core-rust/pull/1905;
there is no need to show the captured error any longer
(which was unreliable and hard to handle from core site).
there is some capturing-code left as needed for other parts,
but it is not used for configuration anymore.

adapt to new dc_configure() error handling

---

res/xml/preferences_app_protection.xml
src/org/thoughtcrime/securesms/ApplicationPreferencesActivity.java
src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
src/org/thoughtcrime/securesms/preferences/AppProtectionPreferenceFragment.java

for various reasons,
screen-lock will be removed completely in one of the next versions.
- if screen-lock was enabled before, add a warning
and keep the options (user can switch screen-lock on and off
until it will be finally removed)
- if screen lock was disabled before,
hide the corresponding options,
(the user will not be able to enable screen-lock anymore)
reasons for removing are:
- hard maintainability on different android versions, see discussions at
https://github.com/deltachat/deltachat-android/issues/1208 and
https://github.com/deltachat/deltachat-android/pull/1319 and offline.
ftr, also the used api createConfirmDeviceCredentialIntent() is deprectated,
so another set of api calls would be needed in the soon future.
- compared to the effort, few security is added,
the function …

tune down usage of screen-lock

---

res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationListActivity.java

when forwarding to "saved messages",
the ui goes back to the chat and the position in the original chat
and shows a short "saved" hint.
this saves at least one tap (cc @hpk42 :)
and makes saving multiple messages easier
as you stay in context.
btw, this is also how telegram handles things
and makes the saving as easy to use as starring eg. in whatsapp.
forwarding messasges to other chats is not changed.

direct forward to "saved messages"

---

src/org/thoughtcrime/securesms/ConversationListItem.java
src/org/thoughtcrime/securesms/notifications/NotificationCenter.java

this pr removes the system-notifications once we know that there are no more unread messages in a chat.
there is currently no event for that, however, it happens implicitly when one _answers_ in a chat on another device - then we get that message and the last message is no longer seen/fresh. the badge was always removed in this case, this pr now also removes the system notification and improves layout.
just _reading_ the chat on another device won't be sufficient, if we really want that, we need probably to do sth. in core. but even in the current state, it seems to be a good improvement :)
as a side-effect, this pr will save some calls to dc_get_fresh_msg_cnt() an may speed up things beyond https://github.com/deltachat/deltachat-core-rust/pull/1881
closes #1646

better multi-device notification removal

---

src/org/thoughtcrime/securesms/ConversationListItem.java
src/org/thoughtcrime/securesms/components/AvatarImageView.java

quickContact means that you get to the contact details screen by
clicking the avatar. In the conversations list this is usually disabled,
just for the search it stayed enabled, which was unexpected
(because it was usually disabled ;-) ).
Even worse, in the search clicking the avatar sometimes got me to the
wrong contact details. No idea why, but I think disabling is better
anyway.

Don't use quickContact in the ConversationListItem

---

src/org/thoughtcrime/securesms/PassphraseRequiredActionBarActivity.java
src/org/thoughtcrime/securesms/components/AvatarImageView.java

it's not a big difference but these are small changes, too.
- Log.i instead of Log.w (seemed to make a difference, maybe only Log.i buffers?)
- Don't set a fallback avatar
if there is no fallbackavatar the error avatar will be shown, which is the same in our case, but this way we don't have to call getFallbackAvatarDrawable twice

Faster conversations list load

---

src/org/thoughtcrime/securesms/audio/AudioSlidePlayer.java

I don't think it is worth it to add support for e.g. m4a but we can let the user open it in another app so that they can still listen to it.

If audio failed to play, open it in external app

---

res/menu/contact_list.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/ContactSelectionListFragment.java

this pr adds an "view profile" info-icon to the action-bar that is shown when a contact is long-tapped.
selecting the icon will open the contact's profile.
successor of #1659, getting the "hack" into a "real feature" :)

open profile from contact list

---

src/org/thoughtcrime/securesms/ConversationActivity.java

disable 'disappearing messages' when a chat is not sendable this is currently the device-chat, but may be others in the future.
the thing did not worked anyway: the icon was displayed in the title, but the info-message was missing. timer was never started.
came over that when writing the device-message for #1689 and though ppl might try that out in the chat they're in :)

no 'disappearing messages' when a chat is not sendable

---

src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ProfileActivity.java

successor of https://github.com/deltachat/deltachat-android/pull/1690
this pr
- hides settings-tab in device-chat (was already hidden in saved-messages)
- hides edit-name in device-chat and saves-messages
- hides block-contact and show-encyption-info in device-chat (was already hidden in saved-messages)
- for saved-messages, remove "mute" from chatview - it was always removed from profile-view. there are not notifications for self-sent- aka saved-messages
#closes #1691

hide special-functions in special-chats

---

res/menu/conversation_context.xml

in the long-tap context-menu, on smaller screens,
functions go to the overflow menu from right to left.
this pr gives the "delete" a higher priority than the
only sometimes available "export" function
- delete is always available on smaller screen -
before, the icon was sometimes there and sometimes not,
which is a bit irritating
- export gets a similar priority as copy
- on/off icons are now functions that are used
less frequently
the change is needed now as, due to quoting, there are more functions in the long-tap context-menu.

priorize delete-function over export/copy

---

src/org/thoughtcrime/securesms/ConversationFragment.java

i also cannot see a usecase for forwarding info-messages as "member added",
so it might also confuse users when the option is offered at all.
as all selected messages are loaded into memory anyway,
this was easy to implement.
tbh, if we would track the selection by message-ids only and
this would have require a larger refactoring or performace issues
(imaging 100 messages to be checked on each new selected message),
i would not have implemented that now :)
i do not think, that sensitive information can be send accidentially this way,
even if Bob can forward an info-message as "Alice invited Claire" -
it is pretty clear to Bob that he forwards exactly that text.
(this is different from adding "Honey" to the group -
where "Honey" is an only locally given name for "Dr. Someone" ;)
closes …

disable forwarding info-messages

---

res/layout/conversation_input_panel.xml
src/org/thoughtcrime/securesms/components/InputPanel.java

Also I have no idea why someone would set UPDATE_EVERY_MS to 173 but with 99 we get a totally smooth counter

Do not display milliseconds when recording a voice message fix #1711

---

src/org/thoughtcrime/securesms/scribbles/ImageEditorFragment.java

For some reason it is not possible to remove `setUri`, when I tried, I
got crashes each time I tried to edit an image.

Fix crash in ImageEditor

---

src/org/thoughtcrime/securesms/ConversationListItem.java
src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
src/org/thoughtcrime/securesms/notifications/NotificationCenter.java

the 'inboxes' value contains the last lines of notification,
however, if the app is restarted for whatever reasons,
but notifications are persisted,
they do not contain all lines.
for the notification display, this is no big deal,
however, this cached value is not suitable
to check if there is a notification or not for a chat.
even if there is a notification, 'inboxes' may be empty,
this 'speed up' check was introduced
for a workaround of notification removal that requires lots of calls.
meanwhile, however, we have DC_EVENT_MSGS_NOTICED,
so we also remove this workaround.
the bug of notifications getting stuck was reported by @adbenitez on irc/dc

do not use cached value to check for notifications

---

ndk-make.sh

ndk-make.sh: use environment variable to control LTO

---

res/layout/autodel_confirm.xml
res/values/strings.xml

this pr changes the wording, not relativize things, underlining the worse impact.
i avoided adding "maybe" or "potentially" here, even if that would be more accurate as in reality fewer messages are deleted (we could add a "Info" link or so at some point, but that is more work and can be done later).
before/after screenshots:

fortify wording in delete-server dialog

---

res/values/strings.xml
src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java
src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java

when server-deletion is enabled, always show a hint about the impact below the option.
the hint is a summary of the conformation-dialog so that the user is more aware of the impact if enabling was some time ago or the option was even enabled by the provider-db.
just came into my mind :) successor of https://github.com/deltachat/deltachat-android/pull/1736

show permanent hint about server-delete impact

---

res/layout/contact_selection_list_fragment.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/BlockedAndShareContactsActivity.java
src/org/thoughtcrime/securesms/ContactSelectionActivity.java
src/org/thoughtcrime/securesms/ContactSelectionListFragment.java

add a hint to the "blocked contacts" activity if there are no blocked contacts.
before, the whole activity was just "white" and it was unclear what can be done here.
moreover, this pr cleans up with unused `SwipeRefreshLayout`.
closes #1287
once merged, we should use the string `blocked_empty_hint` instead of `none_blocked_desktop` also on ios and desktop. (the old string reads "no blocked contacts yet" which does not give a hint who blocks things and also the "yet" feels a bit weird to me - as if this is a goal or so :)

show hint if there are no blocked contacts

---

res/layout/quote_view.xml
res/values/colors.xml
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/components/QuoteView.java

see #1743  for backgrounds and reasoning. this is how it looks like:
i also introduced a "universal" forward color that is is also used for quotes where the sender is unknown for whatever reason (forwarded-messages and unnamed-quotes are quite similar in this regard and it makes sense to use the same color for both)
closes #1743

display forwarded messages also in quotes as such

---

res/layout/image_editor_hud.xml
res/values/colors.xml

It repeatedly annoyed me that I can't recognize the white edit tools on a bright surface. I now added a black half-opaque circle behind each one.
According to StackOverflow (if I understood correctly), selectableItemBackgroundBorderless is supposed to show some animation when pressing the icon but this seems not to have worked anyway, at least I could not recognize any animation.

Put a black circle behind the edit options when editing an image

---

AndroidManifest.xml

Fix #1701 
I am not 100% sure if this is the way to go. On first sight, this seems totally legit: ShareActivity should handle `SENDTO` intents, I mean, why should NewConversationActivity do this? But then, there may be a reason why NewConversationActivity was chosen to do the job.
Of course NewConversationActivity could do the same as ShareActivity does or relay it to ShareActivity, but this seems like very bad code style (it currently does relay to ShareActivity sometimes in `handleIntent()` but then forgets to relay all the extras; that's why the recipient is lost).
I think it's best to ping @flub as he also did sharing-related stuff in the past and then wait until after the release.

Handle sendto intents with ShareActivity, not NewConversationActivity

---

src/org/thoughtcrime/securesms/ConversationItem.java

following common ui expectations,
there must always be at least one "ok" button
in a dialog or alert.
there might be good reasons for doing it differently,
however, i do not see any of them here :)
i've overseen that bit when reviewing https://github.com/deltachat/deltachat-android/pull/1751 :)

add missing button to new error-dialog

---

src/org/thoughtcrime/securesms/audio/AudioSlidePlayer.java

I can't tell if it helps, I personally was able to both play a 60min
audio and to play 32 voice messages after each other. Shouldn't hurt to
release them, though.
I tested my change, and at least it seems not to worsen anything.
Fix maybe https://github.com/deltachat/deltachat-android/issues/1755

Always release the media player before setting it to null

---

res/values-v29/arrays.xml
res/values/arrays.xml
res/values/strings.xml
res/xml-v29/preferences_appearance.xml
res/xml/preferences_appearance.xml
src/org/thoughtcrime/securesms/util/DynamicNoActionBarTheme.java
src/org/thoughtcrime/securesms/util/DynamicTheme.java
src/org/thoughtcrime/securesms/util/Prefs.java

fix maybe #1748. Maybe not, because actually I don't understand why issue #1748 even happened because we don't use the system background for the bubble but an own one, `conversation_item_outgoing_bubble_color`, defined in `themes.xml`. They are retrived in `org.thoughtcrime.securesms.ConversationItem#initializeAttributes` (org/thoughtcrime/securesms/ConversationItem.java:263` and set on our own. The standard background color should be white (see conversation_item_sent.xml:50).
Probably the system is somehow trying to forcefully apply a dark mode, no idea how. Maybe it looks for a combination of "background" and "white" and then sets it to dark, similar to [ForceDark](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#disable-force-dark) (which is opt-in though, and also …

Dark theme / DayNight: Add option to follow system

---

res/layout/autodel_confirm.xml
src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java

Using both `setMessage()` and `setView()` on the same AlertDialog,
on small screens the "OK" and "Cancel" buttons were not be show. So, put the
message into our custom view.

Show controls on small screens

---

.github/workflows/preview-apk.yml

generate APK previews for pull request testing (for faster generation, only architecture armeabi-v7a is compiled, change it before merging, if not convenient)
once the action ends to run, click in details:
then click the artifacts drop-down menu and select the APK file:

add preview-apk workflow

---

src/org/thoughtcrime/securesms/FullMsgActivity.java

AsyncTasks [are deprecated](https://developer.android.com/reference/android/os/AsyncTask), and actually by not using it, the code gets shorter and IMHO more readable. Also, AsyncTask has "inconsistent behavior on different versions of the platform".

Don't use AsyncTask

---

src/org/thoughtcrime/securesms/FullMsgActivity.java
src/org/thoughtcrime/securesms/WebViewActivity.java

this pr adds pinch-to-zoom to the message-html-view and hardens the settings.
i've read through the settings at https://developer.android.com/reference/android/webkit/WebView and https://developer.android.com/reference/android/webkit/WebSettings and https://wiki.sei.cmu.edu/confluence/display/android/DRD02-J.+Do+not+allow+WebView+to+access+sensitive+local+resource+through+file+scheme
successor of #1763

message-html-view: harden settings, add pinch-to-zoom

---

res/values/arrays.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/EphemeralMessagesDialog.java
src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java

Also match unknown options to some known option, not "disabled".

Change list of ephemeral message options

---

res/values/arrays.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/EphemeralMessagesDialog.java

While 4 weeks always fits in a month,
5 weeks (35 days) always covers at least a month,
so it can be used in a situation where messages are required to
be stored for a month.

Replace 4 weeks option with 5 weeks option

---

src/org/thoughtcrime/securesms/ConversationActivity.java

Some people reported that drafts were disappearing, and I found a way to
reproduce it (my interpretation in brackets):
- Open Saved Messages chat, could be any other chat too
- Go to another app and share to DC
- In DC select Saved Messages. Now a draft with the share text is created. Edit the text if you like (but don't put too much effort in it as the draft will vanish :) ). _Don't_ hit the Send button.
- (as sharing is done using startActivityForResult(), a second
ConversationActivity is created without affecting the existing one)
- Leave DC. (The second ConversationActivity will correctly save its
draft to the db)
- Open DC again from the "Recent apps". (this is where my fix comes into play) (The first ConversationActivity
will be loaded. It will not know that there is a newer draft …

Fix disappearing drafts

---

res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/components/QuoteView.java

recent discussions with @adbenitez @flub @Simon-Laux and other on DC, this was also one of the suggestions of @Simon-Laux at https://github.com/deltachat/deltachat-desktop/issues/1977 :

show name of forwarder in groups

---

src/com/b44t/messenger/DcMsg.java
src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/ConversationListFragment.java
src/org/thoughtcrime/securesms/components/QuoteView.java
src/org/thoughtcrime/securesms/notifications/NotificationCenter.java

this is just a very simple approach to move forward.
to mark overridden names, a "~" is prefixed.
the idea with using a dedicated color for these names:
as we do not really know
if the address is a generic sender address or belongs to the user,
it makes sense to keep the color used for the name and do not use a
dedicated grey or so.
i think, it is not even worth to detect that better:
it is pretty nice to have senders in mailinglist marked nicely,
all the time.
currently, the "~" is only added to the bubbles - it is not there
in the chatlist-summary (that would needed to be done in core)
and also not in forwarded by, notifications, clipboard etc. i'd say currently,
this is not needed, however, with the current approach it would be doable
(if we mark possible impersonation by colors or …

mark overridden names by a "~" in the bubbles

---

src/com/b44t/messenger/DcChatlist.java
src/com/b44t/messenger/DcContact.java
src/com/b44t/messenger/DcContext.java
src/com/b44t/messenger/DcMsg.java
src/org/thoughtcrime/securesms/ApplicationContext.java
src/org/thoughtcrime/securesms/BlockedAndShareContactsActivity.java
src/org/thoughtcrime/securesms/ContactSelectionListFragment.java
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/ConversationListFragment.java
src/org/thoughtcrime/securesms/GroupCreateActivity.java
src/org/thoughtcrime/securesms/ProfileActivity.java
src/org/thoughtcrime/securesms/ProfileDocumentsFragment.java
src/org/thoughtcrime/securesms/ProfileGalleryFragment.java
src/org/thoughtcrime/securesms/ProfileSettingsFragment.java
src/org/thoughtcrime/securesms/RegistrationActivity.java
src/org/thoughtcrime/securesms/WelcomeActivity.java
src/org/thoughtcrime/securesms/components/QuoteView.java
src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
src/org/thoughtcrime/securesms/connect/DcEventCenter.java
src/org/thoughtcrime/securesms/map/MapDataManager.java
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java
src/org/thoughtcrime/securesms/qr/QrCodeHandler.java
src/org/thoughtcrime/securesms/qr/QrShowActivity.java
src/org/thoughtcrime/securesms/qr/QrShowFragment.java
src/org/thoughtcrime/securesms/util/Util.java

targets https://github.com/deltachat-bot/echo/issues/9
now, it should be possible to check out the android project and use only the `jni`  and the `src/com/b44t/messenger` directory in combination with plain java, without android.
at some point, we could think over to move the bindings to a separate project, however, i am not in favor of doing that now as this would comes at costs wrt android development. but if it is actually in use independently of android, we can think over it.

remove android dependencies from bindings

---

src/org/thoughtcrime/securesms/components/ThumbnailView.java

fix  #1797
Apparently, we ran into a bug similar to the one described in
https://github.com/bumptech/glide/issues/613#issuecomment-144762087 as
we cropped twice (in addition to the cropping I removed, we also set
`android:scaleType="centerCrop"` in `thumbnail_view.xml`)

Fix the image-is-cropped-too-much-bug

---

build.gradle

See https://github.com/bumptech/glide/issues/3851
Doesn't have to get in before the next release if you say that it's too risky :)
I mean these logs:
```
W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
java.io.IOException: Invalid byte order: ffff8950
at android.media.ExifInterface.readByteOrder(ExifInterface.java:3121)
at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2437)
at android.media.ExifInterface.getMimeType(ExifInterface.java:2315)
at android.media.ExifInterface.loadAttributes(ExifInterface.java:1753)
at android.media.ExifInterface.<init>(ExifInterface.java:1447)
at com.bumptech.glide.load.resource.bitmap.ExifInterfaceImageHeaderPa …
```

Update glide to 4.12 to get rid of annoying stack traces in the log

---

src/org/thoughtcrime/securesms/components/QuoteView.java

if the original author of a quote is shown
and known to be overridden,
that should be marked with the character `~`
as for the normal names,
esp. as they are look very similar otherwise,
eg. also bold, also colored.
the missing `~` looks like a bug here.
successor of #1808
this also aligns display of overridden names with desktop, where the `~` is also added to quotes at https://github.com/deltachat/deltachat-desktop/pull/2132

mark overridden senders in quotes

---

jni/dc_wrapper.c
src/com/b44t/messenger/DcMsg.java
src/org/thoughtcrime/securesms/FullMsgActivity.java

For long subject it's ellipsized (`…`) now, but I think that there is no need to show the full subject somewhere, it usually doesn't contain _that_ important information and can be seen in full in the normal chat view

Use the message subject as the full-msg-view title

---

jni/dc_wrapper.c
res/layout/profile_status_item.xml
res/menu/profile_common.xml
src/com/b44t/messenger/DcContact.java
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/ConversationTitleView.java
src/org/thoughtcrime/securesms/ProfileActivity.java
src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java
src/org/thoughtcrime/securesms/ProfileSettingsFragment.java
src/org/thoughtcrime/securesms/ProfileStatusItem.java
src/org/thoughtcrime/securesms/components/emoji/EmojiTextView.java
src/org/thoughtcrime/securesms/util/LongClickCopySpan.java

this is how it looks like:
pretty neutral, with title (same as in the profile), i think, that should not raise many questions.
on protocol-level, the text comes in the email footer/signature, it can be defined in Delta Chat as "Signature text" in the profile and it can also be defined in nearly all other mua.
some words to the layout changes: the e-mail address went to the header (where it is also displayed in similar layouts); the 'send message' button is atop for simplicity if the footer/status becomes longer (when opening contact-profiles from group-members, this button should always be at the same position and should be easily reachable)
to the wording: as we are not using the wording "status" in the shipped apps and the predefined text is indeed more a footer/signature, i would not …

Show status

---

res/drawable/sticker_missing_background.xml
res/layout/conversation_item_received.xml
res/layout/conversation_item_received_sticker.xml
res/layout/conversation_item_sent.xml
res/layout/conversation_item_sent_sticker.xml
res/layout/sticker_view.xml
res/values/attrs.xml
res/values/dimens.xml
src/com/b44t/messenger/DcMsg.java
src/org/thoughtcrime/securesms/ConversationAdapter.java
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/components/BorderlessImageView.java
src/org/thoughtcrime/securesms/components/QuoteView.java
src/org/thoughtcrime/securesms/components/ThumbnailView.java
src/org/thoughtcrime/securesms/mms/Slide.java
src/org/thoughtcrime/securesms/mms/StickerSlide.java
src/org/thoughtcrime/securesms/util/MediaUtil.java

Sticker picker is not implemented, just receiving(from DC Desktop, bots or future DC versions) and forwarding stickers
(code adapted from Signal)
Feel free to tweak at taste :)

implement sticker visualization

---

src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/MediaPreviewActivity.java
src/org/thoughtcrime/securesms/database/loaders/PagingMediaLoader.java
src/org/thoughtcrime/securesms/mms/AttachmentManager.java

fix #1816
The problem was:
- as @link2xt already wrote, the onclick listener only checks if the mime type is `image/` or `video/`.
- then `PagingMediaLoader` loads all images and videos of the current chat with `context.getChatMedia(msg.getChatId(), DcMsg.DC_MSG_IMAGE, DcMsg.DC_MSG_GIF, DcMsg.DC_MSG_VIDEO)`. We need _all_ images so that the user can swipe back and forth.
- The correct image to be shown can't be found, the MediaPreview is opened anyway. As the correct image can't be shown, the first image in the chat is shown.

Don't open media preview for attachments with file viewtype

---

src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/mms/ImageSlide.java

Since #1834, images were not opened in the media preview again but
opened with an external app, as reported by @adbenitez.
This was because since #1834, only slides that return true on
`hasImage()` are shown in the media preview, i.e. gifs, images and
videos.
Now, the problem was that images were shown as DocumentSlides under
some circumstances, which return `false` for `hasImage()` (naturally).

Bugfix: open images in the media preview again

---

build.gradle

besides support on normal image messages, this means Delta Chat Android will also have "animated stickers" which, btw, already work in Delta Chat Desktop.
Images for testing:
* animated web:
https://isparta.github.io/compare-webp/image/gif_webp/webp/2.webp
* animated png:
https://misc.aotu.io/ONE-SUNDAY/SteamEngine.png

Add APNG and animated webp support

---

src/org/thoughtcrime/securesms/ConversationItem.java

Esp:
- Long-click on a sticker to enter multi-select mode
- click on the sticker again to deselect it
Expected: The sticker is deselected
Actual: Nothing happens

Let stickers handle clicks

---

src/com/b44t/messenger/DcMsg.java
src/org/thoughtcrime/securesms/ConversationItem.java

Adapt to alias support: Always show sender avatar and name on messages if OverrideSenderName is set
See deltachat/deltachat-core-rust#2297

Alias support

---

res/layout/add_poi_view.xml
src/org/thoughtcrime/securesms/map/DataCollector.java

* unlimited message length
* text editor can be up to 5 lines tall (same as the chat's input text editor)
* POI text display is truncated to 16 characters (previous text editor limit was 16 characters)
close #1821

allow to add POI with text of any length

---

src/org/thoughtcrime/securesms/BaseConversationItem.java
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/ConversationUpdateItem.java

close #1882 
:cloud_with_rain: rain of fixes related to system messages: 
* clicks on system messages in the contact requests chat now work, displaying the dialog to accept the contact request (#1882)
* clicks on system messages that failed (`msg.isFailed() == true`) now display a dialog with the error message just like normal message bubbles do
* additionally, now system messages that have `Linkify`-ed text can be selected with long tap, this didn't worked in the past and users had to long-press empty areas close to the message record.

fix clicks on system messages

---

res/menu/profile_context.xml
src/org/thoughtcrime/securesms/MessageSelectorFragment.java
src/org/thoughtcrime/securesms/ProfileDocumentsFragment.java
src/org/thoughtcrime/securesms/ProfileGalleryFragment.java
src/org/thoughtcrime/securesms/ProfileSettingsFragment.java

with #1868 new items were added to `profile_context.xml` menu, which are used by the gallery and documents tabs, it turns out that the settings tab also uses this menu, so unneeded items should be hidden.
Also, in the Gallery menu, would be nice to show the share button directly without having to open the image to share

Improve profile menus

---

src/org/thoughtcrime/securesms/search/SearchFragment.java
src/org/thoughtcrime/securesms/search/SearchRepository.java
src/org/thoughtcrime/securesms/search/SearchViewModel.java

this pr aims to do the global search improvements from https://github.com/deltachat/deltachat-ios/pull/1140 on android.
the speedup is done by the following changes:
- if the query-string is updated while actually performing a search,
the new search is not directly scheduled as before;
instead the flag needsAnotherBgSearch is set;
in the search-thread, the flag is checked
and another search will be performed
this way, searches as skipped, but the most recent is always executed
- if there are already chat- or contact-results and
the query-search has changed meanwhile, search is aborted
and the partial result is used (next search will be executed immediately)
this way, esp. the expensive searchMsgs() search is executed less often
on fast typing
- for a one-letter-search, search for messages …

speedup global search

---

src/org/thoughtcrime/securesms/search/SearchListAdapter.java

by definition, since https://github.com/deltachat/deltachat-core-rust/pull/2366, global-message-search truncates the result at 1000 messages, therefore, if we get 1000 results, that may be a limited result.
cmp. https://github.com/deltachat/deltachat-ios/pull/1166

mark limited results as such

---

src/org/thoughtcrime/securesms/ConversationListFragment.java

contact requests workflow improvements (part 1)

---

res/layout/conversation_item_received.xml
res/layout/conversation_item_update.xml
res/layout/conversation_item_videochat.xml
res/layout/message_details_view.xml
res/layout/profile_create_activity.xml
res/layout/single_line_input.xml
src/org/thoughtcrime/securesms/BaseConversationItem.java
src/org/thoughtcrime/securesms/CreateProfileActivity.java
src/org/thoughtcrime/securesms/MessageSelectorFragment.java

try to use the same emoji style everywhere, if user enables "use system emojis" the system emojis are used without issues, the situation was that with built-in emojis enabled they are mixed with system emojis in quite visible parts of the app like the sender name of incoming messages contrasting with quotes, emojis in message body, etc.

use the same emoji style everywhere across the app

---

res/layout/attachment_type_selector.xml
res/layout/avatar_selector.xml
res/layout/contact_filter_toolbar.xml
res/layout/conversation_item_received.xml
res/layout/conversation_list_activity.xml
res/layout/conversation_list_item_view.xml
res/layout/conversation_title_view.xml
res/layout/image_editor_hud.xml
res/layout/media_view_edit_button.xml
res/layout/media_view_remove_button.xml
res/layout/profile_create_activity.xml
res/layout/profile_preference_view.xml
res/layout/quick_camera_controls.xml
res/layout/quote_view.xml
res/values-es/strings.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/TransportOptions.java
src/org/thoughtcrime/securesms/components/DeliveryStatusView.java
src/org/thoughtcrime/securesms/components/emoji/EmojiPageViewGridAdapter.java

improve app accesibility

---

res/layout/conversation_fragment.xml

this is the text that is show when chat is empty "Send message to X: It is fine if X doesn't use Delta Chat [...]" 
X might have emojis

use current emoji theme in "no_messages_text_view"

---

src/org/thoughtcrime/securesms/LogViewFragment.java

scroll to top/bottom was not working when the `EditText` is not focused.

make log view's scroll to top/bottom work

---

AndroidManifest.xml

for some reason, URLs starting with "OPENPGP4FPR:" are not handled if the custom schema is not specified also in upper case.
in DeltaLab there is markdown support so extracting QR data and creating a nice invitation link is a possibility, also bots might offer this kind of link in html messages taking the QR data provided by core which is in upper case, and it would be nice if it works in upper case

handle URLs starting with OPENPGP4FPR and other case variants

---

res/values/strings.xml

I got the user feedback that it's not clear that this setting only applies for this chat/group and is not a global setting like device/server deletion

Clarify disappearing message hint

---

res/values/strings.xml
src/com/b44t/messenger/DcContext.java
src/org/thoughtcrime/securesms/qr/QrCodeHandler.java

the code-part of this pr is pretty simple, most work was already done in core at https://github.com/deltachat/deltachat-core-rust/pull/2512
what should be reviewed mainly is the wording of the 4 dialogs that appear when a user scans ones own qr codes:
**widthdraw/revive secure join qr codes:**
**widthdraw/revive group joins:**
closes #1962

allow withdrawing and reviving qr codes, add corresponding strings

---

src/org/thoughtcrime/securesms/ConversationActivity.java

Companion for https://github.com/deltachat/deltachat-core-rust/pull/2479, should be merged before to make sure that the compose panel is hidden immediately when the user leaves a group.
- Imediately hide the compose panel when you left the group and
EVENT_CHAT_CHANGED was sent
- Hide the "Leave" button if you are not a member of a group. I solved
this by checking `canSend()`; I could also have checked
`dc_is_contact_in_chat(CONTACT_ID_SELF)`, but this would be more
complexity for now.
When we add the possibility to leave mailing lists, the core will have
to explicitly tell the UI whether it's possible to leave a chat, but
that's not for now.

Hide unnecessary controls if you can't send

---

res/values/strings.xml

in a multi-device-setup,
if deviceB scans ones own setup-contact QR code shown on deviceA,
it is misleading to say that the QR code was withdrawn
and can be revived.
actually, the QR code was never withdrawn by the user.
this is fixed by this pr.
(at some point, we want to sync QR codes across devices,
but even then, there may be siutuations where things are not in sync)
moreover,
the wording is more explicit about what is usually done with the qr code;
this is esp. helpful, when scanning a printed QR code without much context.
i am not fixed to the rewording, but i'd like to have a similar wording on deactivate/activate.
finally, i removed the "your group" wording; we do not use that anywhere else
and a groups does not have an owner (one may imply that by reading "your group")

consider multi-device usage on withdraw/revive QR code wordings

---

res/values/strings.xml

as discussed several times on different channels,
nowadays, it is more usual to use capitalized titles;
fitting better to existing environments.
this pr capitalizes menu entries, buttons and titles;
"titles" include all titles of all settings.
whats left first-character-lowercase (just to have a clear focus):
- states
- values
- whole sentences
- titles mentioned in whole sentences
(nb: there is the rough idea of having something as "Group or Subject"
instead of just "Group" -
this change is also easier with the new capitalisation rules, cc @hpk42  ;)
as this all does not affect other languages
(they have their own rules),
we should be careful not to force re-translations.
cc @Simon-Laux, @Jikstra as we recently discussed that.

capitalize some strings

---

README.md

Podman and docker require the `:z` suffix if running on system where SELinux is enabled (like
Fedora 34). See the following links for more information:
- https://bugzilla.redhat.com/show_bug.cgi?id=1984457
- https://unix.stackexchange.com/questions/651198/podman-volume-mounts-when-to-use-the-z-or-z-suffix
- https://stackoverflow.com/questions/35218194/what-is-z-flag-in-docker-containers-volumes-from-option
Fixes #1981

Fix SELinux build issue with `:z` suffix

---

res/values/strings.xml
src/org/thoughtcrime/securesms/connect/DcHelper.java

- 'Getting new messages…' is not always fitting,
the messages may be old or they are not visible as messags at all
(read receipts, setup-contact, sync).
'Updating…' is better fitting here.
- 'Getting new messages…' is a bit too long and results in
linebreaks on smaller devices.
closes #1983

use 'Updating…' instead of 'Getting new messages…'

---

src/org/thoughtcrime/securesms/ApplicationContext.java

I couldn't measure whether the app actually loads faster, as first-time app load varies a
lot (3.5s-4.5s on my device), but I could see that `getInstance()`
doesn't need 100ms-300ms on the main thread anymore.

Speedup first-time app load a bit

---

res/layout/conversation_list_fragment.xml
res/menu/text_secure_normal.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationListActivity.java
src/org/thoughtcrime/securesms/ConversationListFragment.java
src/org/thoughtcrime/securesms/ConversationListItem.java

that way, ppl may find existing contact requests easier.  
moreover, it is now possible to access 'Archived Chats'
without endless scrolling ;)
targets some points of #1990 - the other points require some more playing around and can be done in another pr.

tweak 'Archived Chats' and  'Requests'

---

src/org/thoughtcrime/securesms/ConversationListFragment.java

fixes #1994 and, as an extra, adds debouncing. chatlist loading should be pretty smart now.
the technique for the debouncing with two booleans is taken from #1884 - however, the first update is not delayed.

fix chatlist anr

---

src/org/thoughtcrime/securesms/ConversationActivity.java

stop observing `DC_EVENT_CONTACTS_CHANGED` events before blocking chat so the compose panel is not made visible in `handleEvent()`
close #1999

avoid showing compose panel when pressing block button

---

src/org/thoughtcrime/securesms/connect/AccountManager.java

postpone selection after the last migration
as migrateAccount() currently selects the migrated account.
before, the selectAccount() call was useless
if another migrateAccount() call follows.
maybe the select-accounts-api would be more intuitive if adding accounts does not select
(that was already discussed),
however, in case we change that, we have to revisit migrate/add anyway.

keep selection when migrating several accounts

---

src/org/thoughtcrime/securesms/ConversationListFragment.java

Steps to reproduce:
- Go to the profile of a contact
- Block the contact
- Press back twice
Expected behavior: The chat is not shown in the list anymore.
Actual behavior: The chat is shown in the list until the app is
restarted (or if you wait some time)

Fix: When blocking a contact from the profile, update the chatlist

---

src/org/thoughtcrime/securesms/ConversationActivity.java

Steps to reproduce the bug:
- Go to a contact request
- Go to the profile
- Block the contact
- Press back
Expected behavior: Only the compose panel is shown, not the request
buttons.
Actual behavior: Both the panel and the request buttons are shown
because the panel visibility is updated, but not the request button's.
I fixed this by always calling `initializeContactRequest()` after
`setComposePanelVisibility()`.

Fix: When returning to chat after blocking it, hide request buttons

---

src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationListArchiveActivity.java

Steps to reproduce the bug:
- Search and select an archived chat
- Press back
Expected: Go back to the search activity.
Actual: Go to the Archived chats list activity. The user has to press
"back" again to get to the search.

Fix: When searching, entering an archived chat, and going back, go back to search

---

src/org/thoughtcrime/securesms/ConversationActivity.java

Fix #2032
The problem was that after returning from the image editor, `doReinitializeDraft` was true and therefore we the draft was reinitialized to the originally shared, unedited image.
This was introduced in https://github.com/deltachat/deltachat-android/pull/1770. I im pretty sure that what I changed this time is fine, but I also was sure when implementing #1770…. We had so many regressions in the past in this area that we should thoroughly test this change before merging (and I'm really looking forward to UI tests in this area).
I extended
https://github.com/deltachat/interface/blob/master/user-testing/mailto-links.md
a bit; before merging this PR we should test that everything there still
works.

Fix "Can't edit shared image"

---

src/org/thoughtcrime/securesms/ConnectivityActivity.java

it is currently just not needed for a dialog-style html-page,
but raises the question what can be searched here.
if it turns out a search function becomes useful,
we can easily re-add it.

hide 'search' option in connectivity view

---

src/org/thoughtcrime/securesms/scribbles/ScribbleActivity.java

These annotations don't actually have an effect, but they lead to an
error (not a warning) being shown in Android Studio. It still compiles
fine, though.
The line `case ScribbleActivity.SCRIBBLE_REQUEST_CODE:` in
ConversationActivity was therefore shown as an error all the time, which
was really annoying.
The alternative would be to suppress the error in ConversationActivity.

Remove RequiresApi(19) annotation on ScribbleActivity

---

res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationListActivity.java

there are still a few bugs to fix before a release, esp. #2017, however, preparing a device message already now makes sense, esp. when it comes to translations :)
this is the current draft:
the blog link will be adapted once there is a blog entry.
corresponding ios pr (which should mostly get the same message, however): https://github.com/deltachat/deltachat-ios/pull/1334

add device message for 1.22

---

src/org/thoughtcrime/securesms/ProfileActivity.java
src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java

the device chat's status contains some useful information
since https://github.com/deltachat/deltachat-core-rust/pull/2613 -
unfortunately, the whole tab was hidden on android.
reminder for myself, again: things are never easy, esp. not the superficial changes ;)
ios and desktop should be fine in this regard.

profile: show tab containing 'status' for device chat

---

CHANGELOG.md
build.gradle

1.22.1 just pulls in new translations - thanks for 9 quick translations of the device message, each for android and ios! - and will hopefully and finally go to the stores then.

prepare 1.22.1

---

res/menu/conversation_context.xml
res/menu/media_preview.xml
res/menu/profile_context.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/MessageSelectorFragment.java
src/org/thoughtcrime/securesms/ProfileDocumentsFragment.java
src/org/thoughtcrime/securesms/ProfileGalleryFragment.java

when selecting multiple messages that contain attachments, for example documents in the "Documents" tab, it was not possible to export all the selected attachments at the same time, user had to select & export one by one, this PR fixes this, allowing to export all selected messages if all of them have attachments

allow to export all selected attachments

---

jni/dc_wrapper.c
res/layout/conversation_item_received.xml
res/layout/conversation_item_sent.xml
res/values/arrays.xml
res/values/strings.xml
res/xml/preferences_chats.xml
src/com/b44t/messenger/DcContext.java
src/com/b44t/messenger/DcMsg.java
src/org/thoughtcrime/securesms/BindableConversationItem.java
src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/components/ConversationItemFooter.java
src/org/thoughtcrime/securesms/components/DeliveryStatusView.java
src/org/thoughtcrime/securesms/connect/DcHelper.java
src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java

this pr allows to not download large messages automatically
- by default, all messages are downloaded automatically, at "Settings / Chats and Media" is an option to set a limit.
- if a message exceeding the limit is received then, the message is assigned to the correct chat. however, instead of the message, just a placeholder text is shown (that should probably be tweaked a bit)
- the "Download" button then replaces the message with the real content.
- the pr requires the core branch [`draft-dl-ffi2`](https://github.com/deltachat/deltachat-core-rust/pull/2631) to be checked out
- there are tons of ideas how a preview can be achieved, and how media types may be detected, however, all of that is out of scope of this pr ;)
so, for testing, things should be fine, however, there are some open …

do not download large messages automatically

---

res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/MediaPreviewActivity.java
src/org/thoughtcrime/securesms/MessageSelectorFragment.java
src/org/thoughtcrime/securesms/ProfileDocumentsFragment.java
src/org/thoughtcrime/securesms/ProfileGalleryFragment.java

it is a bit nitpicking and also a cornercase,
however, yes, it was not correct before.
another option would be to just strike the "... and on your server" which may lead to confusion also on other circumstances - eg. when auto-delete is set to "at once", there is nothing on the server. however, that may raise other issues, we added the "... and on your server" for some reasons, so, i would not change that without further investigations :) - therefore just this pr :)
closes #2058

do not say, device-messages can be deleted from the server somehow

---

jni/dc_wrapper.c
res/layout/group_create_activity.xml
res/menu/profile_common.xml
res/values/strings.xml
res/xml/preferences_advanced.xml
src/com/b44t/messenger/DcChat.java
src/com/b44t/messenger/DcContact.java
src/com/b44t/messenger/DcContext.java
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/ConversationTitleView.java
src/org/thoughtcrime/securesms/GroupCreateActivity.java
src/org/thoughtcrime/securesms/NewConversationActivity.java
src/org/thoughtcrime/securesms/ProfileActivity.java
src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java
src/org/thoughtcrime/securesms/ProfileSettingsFragment.java
src/org/thoughtcrime/securesms/connect/DcContactsLoader.java
src/org/thoughtcrime/securesms/connect/DcHelper.java
src/org/thoughtcrime/securesms/contacts/ContactSelectionListAdapter.java
src/org/thoughtcrime/securesms/contacts/ContactSelectionListItem.java
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
src/org/thoughtcrime/securesms/util/Prefs.java

**requires https://github.com/deltachat/deltachat-core-rust/pull/2707 to be merged first.** you'll also find much more background information there.
~~"profile" and "create" needs to get removed some more options, eg. qr-invite, mute, sound, disappearing-messages and much more does not make sense as nothing can be retrieved. also some more strings need adaption and a little help-text in the broadcast creation screen is also missing.~~ EDIT: done so far.
nb: we should really make the group-creation member/recipient list nicer, they lack the icons, in profile/edit this is much better). [this is an old issue](https://github.com/deltachat/deltachat-android/issues/456), however, and not related to this pr.

broadcasts android ui

---

res/values/strings.xml
src/org/thoughtcrime/securesms/connect/DcHelper.java

moreover, fix the id used for 'Broadcast List' (116 was just wrong here) (some script for extracting things from deltachat.h would avoid these errors, however, we did not really have problems with that yet - even that one would not have been a serious bug when released)

add usage string for connectivity view

---

src/org/thoughtcrime/securesms/ConnectivityActivity.java

I noticed that sometimes the system back button (the one in the lower
left) does not work in the connectivity view. The top bar back button
worked.
This should fix this.
Also, I moved `getSupportActionBar().setTitle(R.string.connectivity)` to onCreate(). It had been in refresh() so that the title could be set to "Connectivity | Connected", "Connectivity | Connecting" and so on. But as we decided not to do this, there is no reason for it to be in refresh().

Fix back button not working in connectivity view sometimes

---

androidTest/com/b44t/messenger/SharingTest.java
androidTest/com/b44t/messenger/TestUtils.java
androidTest/com/b44t/messenger/uibenchmarks/EnterChatsBenchmark.java
androidTest/com/b44t/messenger/uitests/offline/SharingTest.java
androidTest/com/b44t/messenger/uitests/online/OnboardingTest.java
src/org/thoughtcrime/securesms/ConversationListActivity.java
src/org/thoughtcrime/securesms/components/DeliveryStatusView.java

To be reviewed commit-by-commit.
#2031 has to be merged first.
Fix #2040
The problem was that 
if (isDirectSharing(this)) {
openConversation(getDirectSharingChatId(this), -1);
}
was called in refreshTitle(). But refreshTitle() is also called everytime the connectivity changes, so everytime the connectivity changes a new instance of ConversationActivity was opened.
The last three commits are actually independent (but I think uncontroversial) improvements, if you want I can also make a separate PR for this.

Fix shared image being set as draft repeatedly

---

res/values/strings.xml

- the profile hint misses that also the signature
is sent out, together with name and image
- strike the part about that sent information cannot be retracted -
that is pretty clear,
and if we say that here, why not beside every message ;)
not sure where that comes from,
i checked similar settings in other messengers,
there is no comparable hint.

adapt 'self-profile' hint to reality

---

res/layout/group_create_activity.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/GroupCreateActivity.java
src/org/thoughtcrime/securesms/MediaPreviewActivity.java
src/org/thoughtcrime/securesms/NewConversationActivity.java
src/org/thoughtcrime/securesms/ProfileActivity.java
src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java
src/org/thoughtcrime/securesms/ProfileSettingsFragment.java
src/org/thoughtcrime/securesms/util/SelectedRecipientsAdapter.java

this pr adds the button "Create Group or Subject" to the profile of each contact, allowing to easily create a group with that contact. this is useful for:
- create a verified group with that contact (when point 1. of https://github.com/deltachat/deltachat-android/issues/2099 is implemented)
- the group name is used as a subject in normal MUA - this change makes it ux wise more understandable how to create a "normal" email
- of course, this is also handy to create a normal group and to add more members
moreover, this pr cleans up the code a bit.
nb: not sure, which wording we agreed on finally, i find this **New Group or Subject** pretty intuitive, also wrt classic mail. maybe we can also rename the "normal" "New Group" button that way to make it clearer that the group name becomes the …

new group from profile

---

src/org/thoughtcrime/securesms/WelcomeActivity.java

reading captured error has a race with the thread that sets the error.
this is mitigated by sleep().
see https://github.com/deltachat/deltachat-core-rust/issues/2787
for details and a proper solution.

show errors after account scanning failure

---

AndroidManifest.xml
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
src/org/thoughtcrime/securesms/LogViewFragment.java
src/org/thoughtcrime/securesms/MediaPreviewActivity.java
src/org/thoughtcrime/securesms/MessageSelectorFragment.java
src/org/thoughtcrime/securesms/WelcomeActivity.java
src/org/thoughtcrime/securesms/components/AttachmentTypeSelector.java
src/org/thoughtcrime/securesms/components/AvatarSelector.java
src/org/thoughtcrime/securesms/components/RecentPhotoViewRail.java
src/org/thoughtcrime/securesms/database/loaders/RecentPhotosLoader.java
src/org/thoughtcrime/securesms/mms/AttachmentManager.java
src/org/thoughtcrime/securesms/util/MediaUtil.java
src/org/thoughtcrime/securesms/util/SaveAttachmentTask.java
src/org/thoughtcrime/securesms/util/StorageUtil.java
src/org/thoughtcrime/securesms/util/StreamUtil.java

Closes #1849.
Probably best reviewed commit-by-commit and with white-space changes ignored.
To fix this, I had to add a `queries` tag to AndroidManifest.xml. But older versions of Gradle don't support this yet, so I also had to update Gradle. I then also had to update Android Studio as Gradle wouldn't work with my old version anymore. And apparently they made some warning a hard error, so I had to add `tools:ignore="AppLinkUrlError"` four times to AndroidManifest.xml (no the warning was not legit, we did everything fine)
Unfortunately, I did this by copying the backup file to the private storage first, making importing a backup take longer and require more space unnecessarily.
The problem is that native code [can only access files that we created ourselves or that are in our private …

Target SDK/API 30

---

build.gradle

without, there is a warning in gradle7 that says:
"DSL element 'dexOptions' is obsolete and should be removed.
It will be removed in version 8.0 of the Android Gradle plugin.
Using it has no effect, and the AndroidGradle plugin optimizes dexing automatically."
not sure, what the option was about in older gradles.

remove deprecated gradle element 'dexOptions'

---

src/org/thoughtcrime/securesms/ShareActivity.java
src/org/thoughtcrime/securesms/database/loaders/RecentPhotosLoader.java

Fix #2112
- Don't check for write permission when we don't need it
- Revert one of the changes from Signal. I have no idea why they changed this back then, but it prevents all photos from being shown in the recent photo view rail.

Fix photo view rail

---

res/layout/account_selection_list_item.xml

@gerryfrancis complained in the testing group that the check-mark looks too big compared with the avatar size, I was using the size used in Signal but Signal avatars are bigger than in our account selector

reduce selected account's checkmark size a bit

---

AndroidManifest.xml
src/org/thoughtcrime/securesms/WelcomeActivity.java

- Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
was not writable for android10 (older and newer androids are okay)
- the import selectMediaType() showed up,
however never did show the exported file on android10 (also here, older and newer androids are okay)
re-adding the flag `android:requestLegacyExternalStorage="true"` that was removed in #2087
fixed both problems, at least in the emulator.
seems as if the flag is still respected when running on sdk29 even when targeting sdk30;
when running on sdk30, however, the flag is ignored.
at least the following doc does not say that the flag is needless in sdk30:
https://developer.android.com/reference/android/R.attr#requestLegacyExternalStorage
@Hocuri maybe you can have a second look at the docs and confirm or …

fix backups for android10

---

AndroidManifest.xml
res/layout/profile_preference_view.xml
src/org/thoughtcrime/securesms/RegistrationActivity.java
src/org/thoughtcrime/securesms/WelcomeActivity.java
src/org/thoughtcrime/securesms/connect/DcHelper.java
src/org/thoughtcrime/securesms/service/IPCAddAccountsService.java

corresponding yggmail pr: https://github.com/deltachat/AndroidYggmail/pull/15
the goal is to make the interaction as smooth as possible, at best without confirmation, questions etc. the flow is roughly the following:
- start the "provider app", yggmail here, configure account there (just tap "start")
if delta chat is already installed (doesn't need to be running):
- (X) the provider apps sends the new account by a Message object to Delta Chat
if delta chat is not installed:
- the provider app guides the user to downloading Delta Chat (eg. open play store after tapping "start")
if provider app is installed (doesn't need to be running) and delta chat is installed but not yet configured:
- deltachat, when starting unconfigured, sends a broadcast event to possible provider apps
- (X) the …

provider app support

---

src/org/thoughtcrime/securesms/WelcomeActivity.java

rename `chat.delta.AndroidYggmail` to `chat.delta.androidyggmail`
compare: https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

package names should always be lower cased

---

docs/release-checklist.md
scripts/update-core.sh

this is the outcome of recent dc discussions, see commit messages for details.
i already used the changed script for the last core update, see https://github.com/deltachat/deltachat-android/commit/c67e61c12ef06a9eafd91bdbf0621f61ef23e0cf

make tracking core versions easier

---

res/values/colors.xml
src/org/thoughtcrime/securesms/ConversationListItem.java
src/org/thoughtcrime/securesms/accounts/AccountSelectionListItem.java

currently, all three big delta chat uis have different colors for the unread badge:
- desktop is _blue_
- android is _green_
- ios is _red_
esp. for the latter, red seems to be a bad choice as that is easily mixed with error symbols, however, it makes sense to use a similar color for all systems anyway.
in several one-to-one-discussions, there was a majority for _blue_ - so that desktop does not need to do anything to do on that :)
however, blue might also be a good choice as that color is already used on android here and there (headlines etc.) and we were also thinking about chaning the title bar to sth. blueish (however, that is out of scope for now)
i am totally aware that there will ppl that _love_ the current green, these kind of changes are always a matter of taste and cannot be …

synchronize unread-badge-color with desktop

---

CHANGELOG.md
build.gradle
res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationListActivity.java

as this comes shortly after 1.24, as an exception, we keep both device messages:

prepare 1.26.0

---

CHANGELOG.md
build.gradle

(1.26.0 was not released, however, there may be nightlies or other builds around)

bump to 1.26.1

---

src/org/thoughtcrime/securesms/ConversationListItem.java

Probably best reviewed with space changes ignored in the split diff view.
Fix #2163 by making the unread badge visible in the chatlist again. The
user can then go into this chat once in order to mark it as noticed.
Since https://github.com/deltachat/deltachat-core-rust/pull/2861,
the core will prevent the situation "the last message
is outgoing but there are fresh messages" from newly coming up, by
automatically marking the messages as noticed.
This PR removes all the logic that involved some "if the last message is
not fresh|noticed, the unread count should be 0" as this kind of logic
belongs to the core, because otherwise 1) have different behavior on
different platforms 2) issues like #2163 appear.
Now, if the _unread count_ is non-zero, the _unread badge_ is shown.
If the state of the …

Fix unread count: Always show exactly the info that core gives us

---

res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationFragment.java

at #2134 we shortend the hint shown for an empty group massively,
removing greylisting hints and the hint that the recipient can user other mua. also we do not say anything about encryption on group creation.
the result of that shortening is that the creation of a one-to-one chat
is now way too long :)
i suggest shorten the hint in a similar way,
not much would be left then, however, that is maybe not bad :)
suggestions welcome, of course :)
_left: new one-to-one hint in this pr; right: already improved group hint_
EDIT: updated screenshots:

improve wording of one-to-one-chat hint

---

.gitignore
build.gradle
ndk-make.sh
src/org/thoughtcrime/securesms/ConversationListActivity.java

Debug builds of the core (like `ndk-make.sh arm64-v8a`) take about a minute, while
a release bulid (`ndk-make.sh`) takes about 15 minutes.
But as most people seem not to use debug builds regularly because
they are tricky to use, here comes an improvement :) If you gave the wrong argument to `ndk-make.sh`, a warning dialog will now pop up inside the app, telling you what you did wrong and what you should do instead.
`ndk-make.sh` writes its argument into the file `ndkArch`.
`getNdkArch()` in `build.gradle` then reads this file and its content is assigned to
`BuildConfig.NDK_ARCH`. `checkNdkArchitecture()` then checks this.
Maybe in another PR I'll also make DC show a helpful error message if someone is completely new to DC and never ran `ndk-make.sh` at all.

Make ndk-make.sh debug builds (for just one arch) more usable

---

src/org/thoughtcrime/securesms/map/MapActivity.java

a fix for an issue reported by @link2xt  recently in the DC-Android group

don't allow to add POI if user can't send in current chat

---

src/org/thoughtcrime/securesms/ConversationActivity.java

this happens only in rare cases as usually the message is always added
and errors happen far later.
but some conditions are checked very soon (webxdc sizes),
and these let an message not even being added.
note, that this pr only shows the error,
it does not change draft handling or so -
it would eg. be better if the message is re-converted to a draft,
however, that would be a larger refactoring and maybe not worth the effort.
closes #2190

show webxdc errors when sending fails

---

jni/dc_wrapper.c
res/layout/dialog_with_checkbox.xml
res/layout/registration_activity.xml
src/com/b44t/messenger/DcAccounts.java
src/com/b44t/messenger/DcContext.java
src/org/thoughtcrime/securesms/ApplicationContext.java
src/org/thoughtcrime/securesms/RegistrationActivity.java
src/org/thoughtcrime/securesms/WelcomeActivity.java
src/org/thoughtcrime/securesms/connect/AccountManager.java
src/org/thoughtcrime/securesms/crypto/DatabaseSecret.java
src/org/thoughtcrime/securesms/crypto/DatabaseSecretProvider.java
src/org/thoughtcrime/securesms/crypto/KeyStoreHelper.java
src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java
src/org/thoughtcrime/securesms/util/Hex.java
src/org/thoughtcrime/securesms/util/Prefs.java

Depends on ~~https://github.com/deltachat/deltachat-core-rust/pull/2956~~ https://github.com/deltachat/deltachat-core-rust/pull/2980.
Currently:
- Before Android 6 (API 23), there was no KeyStore yet. Currently, you can still create an encrypted account, but the passphrase is stored in clear-text, because that's how Signal is doing things.
- There is no option to manually set the keyphrase or to unlock via fingerprint. This has the advantage that we never need user input for unlocking the accounts and can simply unlock all accounts on startup and the obvious disadvantage that anyone with access to the unlocked device can open DC.
- Each account is encrypted with a different passphrase.
- When importing, you can chosse to encrypt the account.
Findings:
- It may be useful (better UX) to …

Make it possible to create an encrypted database

---

res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/WebxdcActivity.java

show a warning when the app tries to use sendUpdate() for contact requests or other chats the user cannot send to.
this and https://github.com/deltachat/deltachat-core-rust/pull/3001 already catches many cases and improves things a lot, we'll see how that works out in practice.
wording suggestions welcome :)

webxdc: warn when the app tries sendUpdate() and the user cannot send

---

CHANGELOG.md
build.gradle

this is already ready for review, one approved, we should wait for https://github.com/deltachat/deltachat-core-rust/pull/3004, bump version - and can start the 1.27 testing release series :)

prepare 1.27

---

res/layout/webxdc_view.xml

this pr aims to do some _easy_ things to improve the layout of webxdc bubbles:
- larger icon - this came up in discussions here and there
- longer summary line - it is now the full bubble width, the summary is only one line for $reasons (changing this is out of scope of this pr)
- as title left of icon and summary below looks weird, also the title is moved down
if we agree in general on that layout, we can improve things further - as making the bubble as wide as the normal bubbles (tbh, no idea where to tweak things for that). i was also thinking here and there that landscape icons as on telegram may be nice, however, not totally sure. having this square format fits better to "apps" - the landscape is more a preview of some content.

tweak webxdc bubble layout

---

src/org/thoughtcrime/securesms/ConnectivityActivity.java
src/org/thoughtcrime/securesms/LocalHelpActivity.java
src/org/thoughtcrime/securesms/WebViewActivity.java

the forced dark mode usually messes the apps background and colors, it is completely unreadable in some cases, changing color of background images to light colors while the texts remains white

don't force dark mode in webpage for webxdc's webview

---

src/org/thoughtcrime/securesms/WebxdcActivity.java

after several discussions, we decided to allows these APIs, just natively what the browser/webview provide.
advantages of that approach are:
- existing apps can use the APIs without adaptions, so porting apps are easier
- no re-implementation needed - esp. for `IndexDB` that would probably take weeks~months, plus maintenance 
- as we are not using core, the local storage APIs cannot slow down receiving/sending messages
disadvantages:
- the local storage does not go the backups. it could be done by injecting javascript on exit and get `localStorage` etc. to the database, the other way round on opening. however, that's quite some effort, esp. when it comes to `IndexedDB`, this is probably not worth the effort.
other hints:
- no multi-device-sync possible, however, it is questionable if we …

enable `Window.sessionStorage`, `Window.localStorage` and `IndexedDB` APIs

---

src/org/thoughtcrime/securesms/ConversationFragment.java

Marking the message as seen starts ephemeral timer if it is not
already started.
Due to the bug in the core, sometimes messages were marked as seen
without starting ephemeral timer. This can also happen due to other
errors, like database access timeout.
Always calling markseenMsgs whenever the message is displayed, even if
it is already seen, ensures that ephemeral timer is started
eventually.

Mark already seen messages as seen

---

AndroidManifest.xml
androidTest/com/b44t/messenger/uitests/offline/ForwardingTest.java
src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/ConversationListRelayingActivity.java
src/org/thoughtcrime/securesms/ShareActivity.java

fix https://github.com/deltachat/deltachat-android/issues/1704 by creating an extra activity:
https://github.com/deltachat/deltachat-android/pull/2246/files#diff-5027fc167512e95578b7074b02d0740011435b3d033a2fe66d4893a74d81e0e2R12-R24
Also create some new UI test (and test it with the old UI tests) because we had so many regressions wrt sharing, forwarding and switching activities in the past. The test depends on https://github.com/deltachat/deltachat-core-rust/pull/3150; if it doesn't get merged, I'll have to find another method to disable this animation.

Introduce dedicated ConversationListRelayingActivity to fix forwarding bug

---

src/org/thoughtcrime/securesms/CreateProfileActivity.java
src/org/thoughtcrime/securesms/profiles/AvatarHelper.java

fixes 50% of #1835, when selecting image from Gallery, that is usually 99% of the use case when you set an avatar, I think it is rare to take the picture at the moment, the issue is still present in that case because the dependency we use to crop the avatars, which is outdated and causes other issues like #1566, need to be replaced by the image editor we have already, then #1835 will be 100% fixed

avoid rotated avatar image when selecting new self-avatar from Gallery

---

src/org/thoughtcrime/securesms/ConversationFragment.java

close #2250 
this doesn't solve the issue in 100% of cases, in some rare cases a "member removed/added" etc might has a webxdc as parent, I guess the proper fix must be done in core, perhaps set the parent webxdc as quote and use that instead of parent or make get_parent only return parent for webxdc's info messages

don't jump to parent if parent is not a webxdc

---

src/org/thoughtcrime/securesms/WebViewActivity.java

close #2258
(note: at least in my phone, the music is not paused when the webview is paused, but at least when the webxdc is closed destroying the webview stops the music)

pause/destroy webview when activity is paused/destroyed

---

src/org/thoughtcrime/securesms/ConversationActivity.java

go back to chatlist when back button is pressed or user touches outside the dialog in the dialog asking to confirm to forward message inside chat.
currently if back is pressed, the dialog is canceled but the chat stays open and you have to press back again to go to the chatlist with the "Forward to..." title

tweak confirm-to-forward dialog

---

src/org/thoughtcrime/securesms/ConversationItem.java

tapping on the message, still allows re-downloading
in case of temporary errors.
https://user-images.githubusercontent.com/9800740/163385728-43a5846e-4006-4018-b7ea-c5f75b2c20ee.MOV
maybe the error message could be nicer, however, not sure if that is worth the effort, at least this is sth. for another time :)
i came over that issue when trying to find out more information about https://github.com/deltachat/deltachat-core-rust/issues/2876

show download failures

---

res/layout/welcome_activity.xml
res/values/strings.xml

this pr is only about fine-tuning the new strings before they can get translated; wrt case: we are using "first letter uppercase for most words" on all buttons and items meanwhile, therefore i slightly adapted that.
suggestions welcome - once this is approved/merged, we can go for layout, positioning, logo (which is less time critical as no external persons involved)
before/after:

adapt strings to new welcome screen

---

src/org/thoughtcrime/securesms/WebViewActivity.java
src/org/thoughtcrime/securesms/WebxdcActivity.java

close #2279 
this allows to open internal pages and for other link have the same behavior than the viewer of HTML emails, allowing to open web links externally etc.

webxdc: allow internal pages and open some known schemes externally

---

src/org/thoughtcrime/securesms/WebxdcActivity.java

show the chat name in front of the webxdc name to
- prevent phishing (the window will not show just the name of your bank)
- give the user an idea about where the webxdc sends messages to
(important eg. when using the same webxdc from different chats)
counterpart of https://github.com/deltachat/deltachat-ios/pull/1578
see also https://github.com/deltachat/deltachat-core-rust/pull/3309

show context of Webxdc window

---

res/menu/webxdc.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/WebViewActivity.java
src/org/thoughtcrime/securesms/WebxdcActivity.java

the code is a tiny bit more complicated
as we keep the call to getWebxdcInfo() in background
and also avoid a second call to getWebxdcInfo() on startup.
(the menu is a bit lost, however, it will probably fill up in the future :)
closes https://github.com/deltachat/deltachat-android/issues/2298

add 'Source Code' item to webxdc menu

---

build.gradle

recently DeltaLab got added to [IzzyOnDroid](https://android.izzysoft.de/repo) repo and after being scanned with some apk analyzer got marked with anti-features because GMS blobs are bundled in the apk due to maplibre including it, this is also happening in official Delta Chat.
I excluded gms and all seems to work fine because in practice we don't use google services, and reading maplibre's repo, the class using the `gms` package is `com.mapbox.mapboxsdk.location.engine.GoogleLocationEngineImpl` and in:
https://github.com/maplibre/maplibre-gl-native/blob/ea234edf67bb3aec75f077e15c1c30c99756b926/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java#L83
it says that for `GoogleLocationEngineImpl` to be used:
> simply add the Google Play …

exclude com.google.android.gms from apk binaries

---

CHANGELOG.md
build.gradle

this version mainly fixes an issue with f-droid that disabled the last two versions because of https://github.com/deltachat/deltachat-android/pull/2303
in other words, on f-droid, 1.30.1 was available for some days, however, is disabled now again. 1.30.2 should fix that issue.

prepare 1.30.2

---

src/org/thoughtcrime/securesms/ConnectivityActivity.java
src/org/thoughtcrime/securesms/LocalHelpActivity.java
src/org/thoughtcrime/securesms/WebViewActivity.java

for webxdc, the system-back-button should do the same
as the back-button in the title bar - just close the webxdc.
without this commit, it loads the previous page, which is often unexpected -
eg. many games use reload() for simplicity,
so you would have press one time 'back' for each round :)
even if there may be situations where this may be useful,
we do not want to encourage webxdc to rely on the system-back-button -
eg. desktop or ios currently just do not have this button.
technically, this pr changes the default -
so, for all classes derived from WebViewActivity, the system-back-button will
now behave as the title-bar-back-button.
for the local-help, this behavior is changed explictly -
i think, for HTML-mails, the 'just close' approach is also better.

fix behavior of system-back-button for webxdc

---

.github/workflows/preview-apk.yml
Dockerfile
ndk-make.sh

Android NDK is updated from legacy ndk-bundle stuck at unsupported
r22b to LTS NDK r23c (23.2.8568313).
Since GNU binutils have been removed from NDK since r23 (see
https://github.com/android/ndk/wiki/Changelog-r23), ndk-make.sh now
uses TARGET_AR=llvm-ar and uses a workaround for `-lgcc` requirement.
Android command line tools used in the Dockerfile are updated to build
8512546
Preview APKs now use NDK r23c too.

Update to Android NDK r23c

---

res/layout/conversation_item_update.xml

the spacing was just a bit too much,
eg. bubble spacing is 6dp atop and abottom.
this was always not-so-good, however, as info-messages are
more in use by webxdc now, it gets more visible.
the new spacing roughly matches the layout on ios.
before/after:
nb: some of the info-messages from the screenshot will be cleaned up by https://github.com/deltachat/deltachat-core-rust/pull/3395 , but other series would not :)

show more info messages by adapting spacing to the overall layout

---

src/com/b44t/messenger/DcMsg.java
src/org/thoughtcrime/securesms/ConversationListItem.java

in core, the state is called `DC_STATE_OUT_FAILED`,
not `DC_STATE_OUT_ERROR`.
the new name also fits better to existing names as `isFailed()`.

use correct `DC_STATE_OUT_FAILED` name

---

src/org/thoughtcrime/securesms/ConversationFragment.java

i think, it makes sense to allow that,
on receiving side they are just text,
see https://github.com/deltachat/deltachat-core-rust/pull/3446
for further reasoning.

allow forwarding info-messages

---

jni/dc_wrapper.c

closes https://github.com/deltachat/deltachat-android/issues/2323

add `epoll_create1` that is missing in API<21 but needed by tokio

---

res/values/strings.xml

the deleted strings seems not to be used on android/ios/desktop
(checked with `./scripts/grep-string.sh`)

remove unused translations

---

src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java

`videochat_instance_explain_2`+`videochat_instance_example`
is mostly the same as `videochat_instance_explain`
but offers nicer layout on desktop.
to make things easier for translators,
we aim to remove `videochat_instance_explain`.

use updated videochat strings

---

res/values/strings.xml

depending on the system (desktop), music may be displayed in other tabs; therefore, just remove that hint. 'files' also include 'music' in the remaining cases.
came over that when filing https://github.com/deltachat/deltachat-desktop/issues/2829

fix gallery's "files" tab hint

---

src/org/thoughtcrime/securesms/ProfileActivity.java

- "Files" is broader than "Docs"
(documents are just one type of files,
files can also be executables and whatnot)
- at other places in the app, we also speak of "Files"
("sending files" etc.)
- Delta Chat iOS also uses the term "Files"
cmp https://support.delta.chat/t/tabs-for-links-and-files/2142

rename "Docs" tab to "Files"

---

build.gradle
src/org/thoughtcrime/securesms/map/MapActivity.java

update org.maplibre.gl to version 9.5.2

---

CHANGELOG.md
build.gradle

i think, it does not make much sense to add a device messages this time, AEAP is currently more a bug fix, better mention that next time. remaining things are mainly bug fixes, and that was already said in the previous device message.
if we want to add one, we can do one in an 1.32.1 easily, this one should be tagged fast so that there is a recent version again on f-droid.

prepare 1.32.0

---

jni/dc_wrapper.c
src/com/b44t/messenger/DcChat.java
src/org/thoughtcrime/securesms/ConversationTitleView.java
src/org/thoughtcrime/securesms/ProfileActivity.java

this pr adds the mailinglist-post-address to the profile's subtitle:
counterpart of https://github.com/deltachat/deltachat-ios/pull/1654
moreover, this pr fixes some "bugs":
- show ephemeral icon in profile for groups (before, it was shown there only for contacts)
- show subtitles for saved-messages, device-chat (i think it was hidden as just most subtitles were hidden at some point in profile)
all in all, the code is a _little_ more straight forward now.

show mailinglist post address in profile

---

AndroidManifest.xml
res/menu/conversation_context.xml
res/menu/profile_context.xml
res/menu/webxdc.xml
res/values/strings.xml
src/com/b44t/messenger/DcMsg.java
src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/ProfileDocumentsFragment.java
src/org/thoughtcrime/securesms/WebxdcActivity.java
src/org/thoughtcrime/securesms/util/views/ConversationAdaptiveActionsToolbar.java

this pr adds an option to add webxdc app icons to the launcher ...
... and start webxdc apps from there directly ...
see commit "[recreate back stack, if possible](https://github.com/deltachat/deltachat-android/pull/2353/commits/0d63f3505cc4eb43a3f08339614d7f81cc7e5163)" for a discussion about about back stack.
closes https://github.com/deltachat/deltachat-android/issues/2350

option to add webxdc apps to home screen

---

jni/dc_wrapper.c
src/com/b44t/messenger/DcContact.java
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationListItem.java
src/org/thoughtcrime/securesms/ConversationTitleView.java
src/org/thoughtcrime/securesms/contacts/ContactSelectionListItem.java
src/org/thoughtcrime/securesms/util/DateUtils.java

use `dc_contact_was_seen_recently()` introduced by https://github.com/deltachat/deltachat-core-rust/pull/3560 (already on android master) instead of ui-implementation.
successor of https://github.com/deltachat/deltachat-android/pull/2371

use dc_contact_was_seen_recently()

---

src/org/thoughtcrime/securesms/WebxdcActivity.java
src/org/thoughtcrime/securesms/util/JsonUtils.java

~~this requires https://github.com/deltachat/deltachat-core-rust/pull/3516 to be on master first.~~ EDIT: done
we we need to know the `internet_access` flag before creation of the html view, this pr moves `getWebxdcInfo()` to the main thread on webxdc creation. doing things in background would be more complicated and error prone (i can easily imagine races if we move html-view-creation to a background thread or change the flag after creation, that would need additional code to be targeted etc.). however, `getWebxdcInfo()` is also called at other places (message list!) from the main thread, so that is probably good enough.
all other things are left in background threads as before.
see https://github.com/deltachat/deltachat-core-rust/pull/3516 for further information.
here is a little demo: …

restricted webxdc internet access

---

src/org/thoughtcrime/securesms/ConversationActivity.java

that option did nothing since you can't leave a mailing list in Delta Chat, at least not yet ;)

hide "leave group" option from menu for mailing list chats

---

res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/ProfileDocumentsAdapter.java

adding "App" to the term makes things much clearer to the user,
was "Webxdc" is about [^1]
eg. on iOS, we have an app selector meanwhile,
calling that _just_ "Webxdc" in the menu or in the title makes it pretty
unclear to the user what this is about.
same for the tab "Webxdc" on desktop or the default description in the summary.
otoh, calling it _only_ "Apps" (as now), may also raise false expectations
and may be mixed with "normal" apps.
so, "Webxdc App" seems to be a good approach.
there is also the term "Mini App" [^2], we could also go for that,
but this is a broader discussion as this would give up the term "Webxdc" partly.
but i would not be against "Mini App" :)
in any case, if there is few space in the UI,
it seems to be okay to abbreviate with just "App" or "Apps" as needed,
if …

reword "Webxdc content"

---

res/values/strings.xml

Depends partly on #2377 being settled. The webxdc selector strings will probably change after the merge of #2377. 
This PR is mainly to not forget about these untranslated strings currently used on iOS.

add missing strings for webxdc selector and webxdc shortcuts on iOS

---

AndroidManifest.xml
res/values/strings.xml
src/com/b44t/messenger/DcContext.java
src/org/thoughtcrime/securesms/WelcomeActivity.java
src/org/thoughtcrime/securesms/qr/QrCodeHandler.java

see https://github.com/deltachat/interface/pull/48 for spec.
needs a core with https://github.com/deltachat/deltachat-core-rust/pull/3541 merged.
I started with android implementation mainly to add the strings that they are swiftly discussed and then translated.
those intents are beyond me, I can't figure out how to register DC as `dclogin:` scheme handler systemwide. sure it needs to go into `AndroidManifest.xml` but then the java code besides that is to hard for me. (I strongly dislike coding java) so it's better done by someone with real android experience, maybe together with #2365, as those two tasks are very similar.
so feel free to just push java stuff to this branch, I'm tired and annoyed of writing java.

add dclogin scheme to qr code scan

---

res/values-az/strings.xml
res/values-bg/strings.xml
res/values-ca/strings.xml
res/values-cs/strings.xml
res/values-da/strings.xml
res/values-eu/strings.xml
res/values-fi/strings.xml
res/values-fr/strings.xml
res/values-in/strings.xml
res/values-ja/strings.xml
res/values-km/strings.xml
res/values-nb/strings.xml
res/values-pl/strings.xml
res/values-pt/strings.xml
res/values-sk/strings.xml
res/values-sr/strings.xml
res/values-sv/strings.xml
res/values-zh-rTW/strings.xml

by the revamped system messages,
lots of translations would be trashed.
this pr preserves these translations by running a little script (https://gist.github.com/r10s/90e78b425ccc47515a2120952ac13809)
the translation state is not worse than before
https://github.com/deltachat/deltachat-android/pull/2380 and already manually improved translations are not touched.
afterwards, we can finally deleted all the deprecated strings.

preserve system message translations

---

scripts/check-translations.sh

`<br>` lineends are not allowed in strings.xml
and lead to compile errors as "terminating tag missing".
(adding these checks as this pop up from time to time and is easily overseen)

check translation for bad lineends

---

res/drawable/ic_circle_status.xml
res/values/colors.xml

with the "connection view",
we already have a green indicating sth. as "online", reuse that. (the green used before is a bit too much of a muted color, this does not reflect "activity" well)
i came over that when [playing around with the layout on ios](https://github.com/deltachat/deltachat-ios/pull/1707); ios uses the same color now.
also many other apps use a similar, less muted green for "activity" or "online".
the difference is not huge on android, on ios it was larger - so this pr is mainly to keep things in sync.
corresponding ios pr using the same color: https://github.com/deltachat/deltachat-ios/pull/1707
once merged, we should also add the color to the interface-repo and change it on desktop (that appears already "more active" by the white border, however)

use less muted color for "recently seen"

---

src/com/b44t/messenger/DcMsg.java
src/org/thoughtcrime/securesms/ConversationUpdateItem.java
src/org/thoughtcrime/securesms/components/ConversationItemFooter.java

Needed for https://github.com/deltachat/deltachat-core-rust/pull/3583/. Before that PR, we never put errors on incoming messages, so this wasn't necessary.

Also show errors for incoming emails

---

src/org/thoughtcrime/securesms/ApplicationContext.java
src/org/thoughtcrime/securesms/connect/NetworkStateReceiver.java

use [`registerDefaultNetworkCallback()`](https://developer.android.com/reference/android/net/ConnectivityManager#registerDefaultNetworkCallback(android.net.ConnectivityManager.NetworkCallback)) instead of [deprecated CONNECTIVITY_ACTION](https://developer.android.com/reference/android/net/ConnectivityManager#CONNECTIVITY_ACTION).
- there is also a [`registerNetworkCallback()`](https://developer.android.com/reference/android/net/ConnectivityManager#registerNetworkCallback(android.net.NetworkRequest,%20android.app.PendingIntent)) but according to [SO](https://stackoverflow.com/questions/53863034/difference-between-registerdefaultnetworkcallback-and-registernetworkcallback) , that is for less broader usage and won't catch "more".
- it is a bit unclear to me, if the other callbacks are …

use more modern methods to track connectivity changes

---

AndroidManifest.xml
build.gradle
src/org/thoughtcrime/securesms/connect/KeepAliveService.java
src/org/thoughtcrime/securesms/notifications/NotificationCenter.java
src/org/thoughtcrime/securesms/service/GenericForegroundService.java
src/org/thoughtcrime/securesms/util/IntentUtils.java

using `targetSdkVersion  32` is required for gplay **from Nov 2022** and requires some adaptions, see https://developer.android.com/google/play/requirements/target-sdk#pre12 ; some notes on the steps mentioned there:
moreover, this PR updates gradle (i got weird errors with the old version) and androidx, at least the old sharetarget does not compile for API 32 (see https://developer.android.com/jetpack/androidx/releases/appcompat for androidx changelogs (select package on the left))
the updated androidx compat dependencies may also help on https://github.com/deltachat/deltachat-android/issues/2400
once this pr is merged, we can rebase and merge #2406 and do a release.

bump targetSdkVersion to 32

---

AndroidManifest.xml

this issue was reported by the testing group, thanks a lot for all the testers and their great job they're doing 🙏
the [crash](https://gist.github.com) was introduced by 1.34.2 that was released for testing only. 
reason is a wrong `exported` flag - it makes sense to have `exported="true"` here.
the flag was added in https://github.com/deltachat/deltachat-android/pull/2407 as needed for android12 - and i was assuming that the old default was `false` and set that value to all missing ones.  
that assumption seems to be wrong, so we should double-check all flags changed by https://github.com/deltachat/deltachat-android/pull/2407
EDIT: according to https://stackoverflow.com/questions/9274742/is-androidexported-true-really-necessary-for-an-authentication-service , it defaulted to `false` only …

fix crash in share-to-delta and similar issues

---

src/org/thoughtcrime/securesms/notifications/NotificationCenter.java

notificationManager.notify() sometime crashes,
it seems to be on some OS versions
in combination with missing sounds (maybe deleted system sounds, idk).
i could not reproduce the issue,
however, by the stack traces reported in the gplay backend, adding a try/catch block should help.
there is also a similar issue reported on stackoverflow , https://stackoverflow.com/questions/72491592/notificationmanager-notify-throwing-securityexception-only-on-android-11-and-1
in the issue, ppl try to fall back to some default parameters in the exception block, however, as it is a bit unclear what really the issue is, one only risks further crashes; also, the crashes are still quite rare, sth. seems to be wrong in the OS here,
so we should not try to be too smart here.
closes #2417

avoid crashes when adding notifications

---

src/org/thoughtcrime/securesms/util/DynamicLanguage.java
src/org/thoughtcrime/securesms/util/ViewUtil.java

sdk16/android4.1 does not support RTL fully,
therefore just return LTR in this case
(this is also what `ViewCompat.getLayoutDirection()` and `View.getLayoutDirection()` are doing).
always using `ViewCompat.getLayoutDirection()`, however, causes problems as the layout is based on the content then (see #2422)
supersedes #2422
closes #2420

let `DynamicLanguage.getLayoutDirection()` work on sdk16/android4.1

---

CHANGELOG.md
build.gradle

another minor update in the 1.34 series.
reminder for myself: once merged, a tag for f-droid should be added immediately.
closes #2426

prepare 1.34.5

---

androidTest/com/b44t/messenger/TestUtils.java
src/org/thoughtcrime/securesms/components/DeliveryStatusView.java

This is needed for the UI tests to run (since https://github.com/deltachat/deltachat-core-rust/pull/3150 didn't get merged, but I didn't try to run the UI tests since then).
Plus, it's just the correct behavior; if the animations are disabled system-wide, there should be no animations. A slight downside of this PR is that the circle doesn't make that much sense if it's not spinning, so we could alternatively replace the image with an hourclock or a clock. I don't think that's worth it though, because the kind of users that disables the animations probably won't mind.
Also, this PR shows an error if someone tries to run the tests with animations on (since they will probably fail anyway).

Don't animate the spinning circle if animations are disabled

---

.tx/config

the old `tx` (written in Python) tool is sunset end nov22 [^1].
- installed the new `tx` tool (written in Go) according to https://developers.transifex.com/docs/cli
- ran `tx migrate` to update tx config files
`/scripts/tx-pull-translations.sh` etc. continue working as expected.
[^1]: https://github.com/transifex/transifex-client

update transifex tool

---

src/org/thoughtcrime/securesms/RegistrationActivity.java

when editing the settings after account was successfully configured.
missed to do this in #2452

don't allow to reveal proxy password 

---

scripts/update-core.sh

new core uses stable-VERSION branches, this pr adapts the script for updating the core to that.
to switch to a new stable core branch or to update an existing one, use
```
./tools/update-core.sh BRANCH_NAME
```
eg. 
```
./tools/update-core.sh stable-1.107
```
counterpart of https://github.com/deltachat/deltachat-ios/pull/1798
i'll move soon forward and merge this pr in; not sure if the script is used by someone else at all :)

adapt tools to work with new core branches

---

docs/release-checklist.md

successor of #2444:
- there seems to be a maximal lenght of 500 characters for the changelog (the 500 chars come from the changlog in #2444 that was truncated after 500 characters)
- the changelog is only needed if there is really a f-droid release scheduled; move the instructions down

refine new f-droid documentation

---

src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/FullMsgActivity.java

loading remote content in contact requests
now always require explicit consent of the user.
moreover, contact request do not alter
the otherwise used never/once/always settings.
iirc, this was also the original gist (contact requests needed to be confirmed to really use the message that time), however, contact requests have  changed since then and behave mostly like normal messages.
we have a similar thing also for webxdc, where webxdc contact requests also cannot send updates.
these improvements are the result of discussions with @Simon-Laux who is just adding html-view to desltop \o/
counterpart of https://github.com/deltachat/deltachat-ios/pull/1804

no automatic remote content loading for contact requests

---

res/raw/webxdc_wrapper.html

remove unused lines; the iframe should include webxdc.js as needed.
they came in by https://github.com/deltachat/deltachat-android/pull/2465/commits/22ae648160df066ad47cdef4db7659e2fc8866ed but i do not see the sense of these lines.
maybe i have overseen sth?

tweak webxdc

---

jni/dc_wrapper.c

These functions are not available in related NDK,
so we provide a fallback implementation for them.

Add fallback implementations for sendmmsg, recvmmsg and getauxval

---

res/menu/text_secure_normal.xml
src/org/thoughtcrime/securesms/ConversationListActivity.java
src/org/thoughtcrime/securesms/ProfileActivity.java

add a global profile to browse all media/documents/attachments, games etc. really useful to find attachments when user can't remember in which chat was sent, also useful for quickly reviewing and removing big attachments to save space
(note: most stuff was already in place to support this, thanks to that fellow collaborator from the past!)

Add "All Media" option to global menu

---

res/menu/conversation_clear.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationAdapter.java
src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/MessageSelectorFragment.java

to decide: when chat has no messages, what to do? hide the menu item? show an error toast on menu item selected? show a dialog? 
currently the same dialog is show for all cases so when there is no messages the "delete 0 messages?" dialog is shown and does nothing

allow to remove all messages from current chat

---

res/values/strings.xml
src/org/thoughtcrime/securesms/ProfileDocumentsFragment.java
src/org/thoughtcrime/securesms/ProfileGalleryFragment.java

this implements (2) of #2498 - a common hint makes things easier,
and also has the advantage, that it is more clear to the user what the
focus of this view is as it picks up the wording from the title.
so, i think, this is good enough.

fix "empty hints" for "all media" view

---

res/values/strings.xml

the terms "App" and "Apps" seems to be clear enough inside Delta Chat, from the view of the user, it is just an app anyway. and from outside, other terms may still be used to clarify things. detaching that, makes the latter even simpler.
finally, it uses less space and clutters UI less.

streamline "App" wording

---

res/values/strings.xml

in english "Background" is already used for "Background connection", "Background App Refresh", "Background Notification", so using another term here make things clearer -
esp. when the option is seen without futher context.
also, many other app prefer "Wallpaper", eg. iOS, Android, Signal, WhatsApp ... so it is also known from there.
all in all, the new term seems much clearer and
avoids misunderstandings.
note: this change is about english only,
no need to re-translate the other languages,
where "Wallpaper" may also should strange;
i added a hint that translators do not need to use the term literally.
i came over that while revamping the ios settings dialog at https://github.com/deltachat/deltachat-ios/pull/1822

use term "Wallpaper" instead of "Background"

---

src/org/thoughtcrime/securesms/BaseActionBarActivity.java
src/org/thoughtcrime/securesms/PassphraseRequiredActionBarActivity.java
src/org/thoughtcrime/securesms/qr/BackupTransferActivity.java

this pr removes superfluous overwrites from `PassphraseRequiredActionBarActivity` and moves the `initFragment()` functions from `PassphraseRequiredActionBarActivity` to its parent,`BaseTitleBarActivity`.
this makes `initFragment()`  accessible from all activities.
successor of #2493 
targets https://github.com/deltachat/deltachat-android/pull/2493#discussion_r1145984223 and some cleanup for finally fixing #2507

cleanup base activities

---

src/org/thoughtcrime/securesms/ApplicationPreferencesActivity.java
src/org/thoughtcrime/securesms/qr/BackupTransferActivity.java
src/org/thoughtcrime/securesms/service/NotificationController.java

this fixes leaving Delta Chat during backup transfer by removing other activities that would abort BackupTransfer by getting called with onNewIntent() otherwise.
moreover, the permantent notification is removed more reliably and possible crashes in  the permantent notification closing (races ...) are catched.
see code + comments for details.
successor of #2508 and #2493
closes #2507

fix leaving Delta Chat during backup transfer

---

res/layout/activity_registration_2nd_device_qr.xml
res/layout/activity_registration_qr.xml
res/layout/welcome_activity.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/WelcomeActivity.java
src/org/thoughtcrime/securesms/qr/BackupTransferActivity.java
src/org/thoughtcrime/securesms/qr/RegistrationQrActivity.java

ppl try already now to set up a second device from the welcome screen. however, end up in logging into their email account again, creating issues with keys and more.  a dedicated "Add as Second Devies" button targets this UX issue by offering a clear path for setting up a second device.
moreover, the string "Scan Invitation Code" is used again (as on all releases), this string is used quite a bit in different handouts, changing that would worsen UX as well.
the "Restore from Backup is moved down,
if you really use this path, finding the button is the smallest issue. the different layout of the button makes clear,
that this is not the preferred way to set up a new account (but sure, to restore a backup :)
moreover, this flags the feature as being "experimental" - this hint and the version …

add "Add as Second Device" to welcome view

---

src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationListActivity.java
src/org/thoughtcrime/securesms/ShareActivity.java
src/org/thoughtcrime/securesms/notifications/MarkReadReceiver.java
src/org/thoughtcrime/securesms/notifications/RemoteReplyReceiver.java

Fix #2505 and make the automated tests pass again by simply reverting https://github.com/deltachat/deltachat-android/commit/8962476a21c67fd943a496f759422a4b2e6cd3e3.
The second commits fixes an NPE that somehow sneaked into the tests.
The "manual sharing tests" don't pass again, esp. https://github.com/deltachat/interface/blob/master/user-testing/mailto-links.md#regression-test-for-the-issue-fixed-by-1770 still doesn't work, but this is for another PR.

Fix sharing, again

---

src/org/thoughtcrime/securesms/qr/BackupProviderFragment.java
src/org/thoughtcrime/securesms/qr/BackupReceiverFragment.java
src/org/thoughtcrime/securesms/qr/BackupTransferActivity.java
src/org/thoughtcrime/securesms/qr/RegistrationQrActivity.java

this adds the used wifi to the "same wifi hint" already before scanning.
there is a pretty low likelihood that we really get that information on a new installation, but still.
successor of #2511 and #2493

show used wifi already before scanning

---

src/org/thoughtcrime/securesms/ConversationFragment.java

we're also checking for null at some other critical code positions, so this seems reasonable also here.
this might fix a recently reported crash,
maybe caused by a race condition.

use conversation-list-adapter more carefully

---

res/layout/activity_registration_2nd_device_qr.xml
res/layout/backup_provider_fragment.xml
res/layout/backup_receiver_fragment.xml
res/values/strings.xml
src/com/b44t/messenger/DcBackupProvider.java
src/org/thoughtcrime/securesms/ApplicationPreferencesActivity.java
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java
src/org/thoughtcrime/securesms/qr/BackupProviderFragment.java
src/org/thoughtcrime/securesms/qr/BackupReceiverFragment.java
src/org/thoughtcrime/securesms/qr/BackupTransferActivity.java
src/org/thoughtcrime/securesms/qr/RegistrationQrActivity.java
src/org/thoughtcrime/securesms/service/GenericForegroundService.java
src/org/thoughtcrime/securesms/util/ScreenLockUtil.java

this pr fixes some things wrt progress bars and crashes when the activity is left during preparing, see commits for details.
moreover, there was a recent request to add a confirmation dialog before the qr code is shown: not sure, how important that really is, however, it turns out, that we already show such a dialog for probably most security-aware ppl using a system-screen-lock (i added that, but have disabled it for testing :)
so, this pr adds a more on-point message to the screen-lock dialog  - and, if the system screen lock is disabled, we show the same message in an alert (that could be made nicer, but that is sth. post 1.36 - also, i assume most ppl use a screen lock)
successor of #2493

send backup progress tweaks

---

res/values/strings.xml

'Unlock to continue' is shorter and sufficient - the context is shown above - and the way to unlock (password, swipe...) is shown below

reword to "Unlock to continue"

---

src/org/thoughtcrime/securesms/qr/BackupTransferActivity.java
src/org/thoughtcrime/securesms/qr/QrCodeHandler.java

this was requested several times during testing - also, later on, switching the network may require recreating qr and/or rescan

if known, show ssid in the AlertDialog directly after scanning

---

src/org/thoughtcrime/securesms/qr/BackupProviderFragment.java
src/org/thoughtcrime/securesms/qr/BackupReceiverFragment.java
src/org/thoughtcrime/securesms/qr/BackupTransferActivity.java

unref() will soon also emit errors, but also before, this was only correct by coincidence, this is for 1.36.1+ with core 1.112.2+ - but can also be merged sooner

make sure, only one error alert is shown 

---

src/org/thoughtcrime/securesms/qr/BackupProviderFragment.java

in theory, this should be more proper, if `stopOngoingProcess()` does not block and returns immediately - otherwise, we get ANR. did not test much yet, however
closes #2531

join prepare/wait threads before calling unref

---

jni/dc_wrapper.c
src/com/b44t/messenger/DcContext.java
src/com/b44t/messenger/DcHttpResponse.java
src/org/thoughtcrime/securesms/FullMsgActivity.java
src/org/thoughtcrime/securesms/WebViewActivity.java

requires https://github.com/deltachat/deltachat-core-rust/pull/4339 to be checked out at jni/deltachat-core-rust

Set WebView proxy to 0.0.0.0 when possible

---

src/org/thoughtcrime/securesms/FullMsgActivity.java

even with setBlockNetworkLoads(true),
shouldInterceptRequest() is called,
not sure if this is a bug or expected behavior,
i did not find documentation for that;
intuitively, i dit not expect sort of a proxy to bypass and explicit block_networks = true,
however, one can probably also argue in the other direction.
leaving setBlockNetworkLoads(true),
in case default behavior changes (or older webviews have different ones), we have a second layer.

do not intercept requests when loading remote content is disabled

---

AndroidManifest.xml
androidTest/com/b44t/messenger/uibenchmarks/EnterChatsBenchmark.java
androidTest/com/b44t/messenger/uitests/offline/ForwardingTest.java
androidTest/com/b44t/messenger/uitests/offline/SharingTest.java
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/ConversationListActivity.java
src/org/thoughtcrime/securesms/ConversationListArchiveActivity.java
src/org/thoughtcrime/securesms/ConversationListFragment.java
src/org/thoughtcrime/securesms/ConversationListRelayingActivity.java
src/org/thoughtcrime/securesms/NewConversationActivity.java
src/org/thoughtcrime/securesms/ShareActivity.java
src/org/thoughtcrime/securesms/connect/DcHelper.java
src/org/thoughtcrime/securesms/util/RelayUtil.java
src/org/thoughtcrime/securesms/util/SendRelayedMessageUtil.java

It always seemed weird to me that there can be multiple running ConversationActivity's. In WA and TG, there is just one chat activity active at a time, and when you press back, you _alway_ get to the chat list.
Now, I noticed that having multiple ConversationActivity's is the cause for at least three bugs on master:
1. - Share to the same chat from within DC
- Go back
- The shared text is gone
2. - Share to another chat from within DC
- Open the image
- Click Back
- The image is gone
3. #2509
In the past, it was also the reason for #2032 and made #1770 necessary.
@adbenitez also agreed that WA's and TG's behavior is nicer. Soooo, that's what this PR introduces.
This is a pretty big change, so this PR probably introduces new bugs, but fixing three bugs at once, making the logic a lot …

Rework how activities interact when forwarding/sharing

---

src/org/thoughtcrime/securesms/ConversationFragment.java

Follow-up for #2549
The bug was: Replying privately gets you to the chatlist instead of the chat, and quotes to messages replied privately don't jump to the chat but to the chatlist.
The bugfix is removing the `finish()`. Adding `FLAG_ACTIVITY_CLEAR_TOP` is just to make sure that we will never have two ConversationActivities at once here, also in future Android versions that might change the behavior.

fix: Make replying privately work again

---

res/values/themes.xml

Before, the chat names were as bright as the subtitles, which made them hard to distinguish.

Tweak chatlist colors: Make titles more visible in dark mode

---

res/menu/conversation.xml
res/menu/text_secure_normal.xml
res/values/strings.xml

this pr syncs the wording of "All Location" to what is used elsewhere in the app and common in apps in general (omitting the verb "show" before objects).
see commit messages for more details.

streamline map wording

---

res/values/strings.xml

for https://github.com/deltachat/deltachat-desktop/pull/3227
partially addresses https://github.com/deltachat/deltachat-android/pull/2429:
because it addresses one key `last_seen_relative`

add strings for `verified`, `verified by` and `last_seen_relative`

---

res/layout/conversation_item_footer.xml

Fix #2566 - well, mostly: This enlarges the padlock (and the location indicator if it's present), but not the checkmark(s), because I didn't manage to also enlarge the checkmark(s) within a bit more than half an hour of work (and I still don't have an idea how it might work, though surely possible).
When using the app like this, this feels good as-is.
This PR with "Largest" resp. "Normal" text size:

Adapt Padlock and Location indicator to screen size

---

res/menu/conversation_context.xml

message list allows multiple messages
being copied to clipboard at the same time;
if these messages as not just text, a summary is added, sth. as "Voice Messages" or "Forwarded: Image - this is my family" etc.
this is on purpose and the gist of the action,
renaming the action to 'Copy Text' makes that more clear.
targets #2569

reword 'Copy to Clipboard' to 'Copy Text'

---

scripts/update-core.sh

core always has a new tag for releases, but only randomly a branch.
this pr changes the update script so that both are accepted and branches can be created as needed.

./update-core.sh accepts tags as well as branches

---

res/values/strings.xml

the current dialog that is show on sendToChat() reads `Share with`.
the idea is to add the filename and also adapt verb to "send" instead of "share" (although i am +-0 on that, it seems more fitting)

add strings for improved sendToChat title

---

CHANGELOG.md
build.gradle

needed a new version code: after a failing upload of 1.38.1 to google play, further attempts to upload the 1.38.1 file again were rejected 🤣
with the version updated to 1.38.2 things are working again (🍋 https://download.delta.chat/android/deltachat-gplay-release-1.38.2.apk) - so 1.38 is finally on the way to gplay ...

prepare 1.38.2

---

AndroidManifest.xml

@adbenitez this fixes the problem you reported that if the user sets the device to dark mode while a webxdc is open, it re-loads veeeeery slowly.
Slight downside: The title bar isn't correctly updated when going into dark mode, i.e. it doesn't become black.
- When going to dark mode, onConfigurationChanged() is called which we can override, but I didn't find a way to update the title bar except for https://stackoverflow.com/a/49209143/8037600, which I didn't want to copy-paste and seems way too complex just to change the color of the title bar a bit.

Don't recreate WebxdcActivity when going to dark mode

---

src/org/thoughtcrime/securesms/ConversationActivity.java

The exception was:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.b44t.messenger.DcMsg.getType()' on a null object reference
at org.thoughtcrime.securesms.ConversationActivity$5.doInBackground(ConversationActivity.java:1124)
at org.thoughtcrime.securesms.ConversationActivity$5.doInBackground(ConversationActivity.java:1115)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
```

Fix NullPointerException

---

build.gradle
src/com/b44t/messenger/rpc/Rpc.java

@adbenitez figured this out, I'm just creating the PR because we tested it on my laptop.
Thanks :tada:!
The issue was:
- On Android 4.2 or older:
- Open an HTML message in Full Msg View
- Enable loading remote images
-> The app crashes.
We only had an Android 4.1 Emulator to test it, but assume that it's the same issue.
It's a known issue in gson 2.10.1: https://github.com/google/gson/issues/2310

Fix crash in the "Full Msg" view by downgrading Gson

---

scripts/ndk-make.sh

Providing an alternative that does not require ADB / connecting a device to laptop. When searching online for "android determine CPU architecture" many non-OSS apps where suggested. I found this app in f-droid to be useful. Maybe somebody else is helped by this.

Update ndk-make.sh initial comment to suggest an app for determining CPU architecture

---

CHANGELOG.md
build.gradle

this is the first release we're doing explicitly on `stable`; as master is defined to contain everyrthing, we need a `git checkout master; git merge stable` afterwards (this will probably also update the submodule, idk)
a device message seems dispensable as there there are not really user-visible/larger changes (in the past, we also did not add device messages for every release)

prepare 1.40.0

---

src/org/thoughtcrime/securesms/ConversationActivity.java

`recipient.getDcContact()` has an old snapshot of the contact that might have changed display name specially by the time we receive a message from a new device and encryption breaks

fix: load updated display name when chat protection breaks

---

src/org/thoughtcrime/securesms/WebxdcActivity.java

in case, getMimeTypeFromExtension()
fails to figure out the mime type for .wasm files, we set application/wasm manually afterwards
closes #2635

set correct mime type for .wasm files

---

res/values/strings.xml

- meet.jit.si is no longer usable without registration, so does not work smoothly for ad-hoc calls
- basicwebrtc: protocol is no longer build-in in any app, so that example does not make sense as well
this is an intermediate step,
we want to get rid of the example string completely and instead show the URLs of the predefined settings.
closes https://github.com/deltachat/deltachat-android/issues/2642
once merged, this requires `./scripts/tx-update-changed-sources.sh` to be run (**from master, not stable!**, so before, we need to merge stable to master /me still not convinced that this stable/master makes sense ... there are so many additional things that can be done wrong, once verified-one-to-ones are stable, we should reconsider this)

adapt videochat instance example

---

src/org/thoughtcrime/securesms/ConversationListActivity.java

don't open connectivity activity when title is clicked if the program is relaying content (forwarding, sharing, etc)

ignore title click when relaying content

---

jni/dc_wrapper.c
res/layout/profile_settings_item.xml
src/com/b44t/messenger/DcContact.java
src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java
src/org/thoughtcrime/securesms/ProfileSettingsFragment.java
src/org/thoughtcrime/securesms/ProfileSettingsItem.java

add 'verified by' to contact profiles

---

res/raw/webxdc.js

main reason is, that these annotations cover the code, making it hard to follow what is going on.
maybe opionionated, however,
in general, .ts is not needed in small projects,
and an additional burden for devs to keep them up to date

remove ts fragments from webxdc.js

---

res/values/strings.xml
res/xml/preferences_advanced.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/util/Prefs.java

the system camera has usually more features (flash, physical zoom, filter) and is less buggy than the mostly unmaintained built-in one. also, the system camera seems to be more supported (isDeviceSupported() is not needed) and does not require to ask for permission
there is still a switch in "advanced settings" to use the old built-in camera, however, at some point we may remove the old code completely
@adbenitez can you please verify that on your device the permission is not needed by disabling it beforehand?

use system camera as default

---

res/drawable/reaction_pill_background.xml
res/drawable/reaction_pill_background_selected.xml
res/layout/conversation_item_received.xml
res/layout/conversation_item_sent.xml
res/layout/reactions_pill.xml
res/values-night/colors.xml
res/values/attrs.xml
res/values/colors.xml
res/values/strings.xml
src/com/b44t/messenger/DcContext.java
src/com/b44t/messenger/rpc/Reaction.java
src/com/b44t/messenger/rpc/Reactions.java
src/com/b44t/messenger/rpc/Rpc.java
src/org/thoughtcrime/securesms/BaseConversationItem.java
src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/reactions/ReactionsConversationView.java
src/org/thoughtcrime/securesms/util/ViewUtil.java

related core PRs:
- https://github.com/deltachat/deltachat-core-rust/pull/3644
- https://github.com/deltachat/deltachat-core-rust/pull/4379
- https://github.com/deltachat/deltachat-core-rust/pull/4388
close #2401

display reactions

---

jni/dc_wrapper.c
res/values/strings.xml
src/com/b44t/messenger/DcContact.java
src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java
src/org/thoughtcrime/securesms/ProfileSettingsFragment.java

core was changed to return SELF from `get_verifier_id()` at https://github.com/deltachat/deltachat-core-rust/pull/4754 - until then, core will return always a contact-id,
which is equal to the current state

show 'verified by SELF' as such

---

res/layout/conversation_input_panel.xml

this looks better the emoji button is not needed as using system-emoji are used and is a prerequisite when considering changing the emoji-default to system
before/after:

move part of left padding from emoji-button to parent

---

src/org/thoughtcrime/securesms/WebxdcActivity.java
src/org/thoughtcrime/securesms/util/Util.java

it seems, fast tapping may result in starting a webxdc twice on some systems, https://github.com/deltachat/deltachat-android/issues/2546, i cannot reproduce this, but the timing-check introduced by this PR may help
@WofWca there will be an `.apk` created by CI soonish - can you please check if that fixes your issue and answer in this PR then?

no more than one webxdc start within 500ms

---

src/com/b44t/messenger/DcContext.java

this PR aims to implement the "Thread Safety" tips from https://c.delta.chat 
to sum up things
- it is recommended, to check an [`AtomicBool`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/AtomicBoolean.html) before calling [`DcEvent event = emitter.getNextEvent()`](https://github.com/deltachat/deltachat-android/blob/main/src/org/thoughtcrime/securesms/ApplicationContext.java#L119)
- [before destroying `DcAccounts`](https://github.com/deltachat/deltachat-android/blob/main/src/com/b44t/messenger/DcContext.java#L103), we would change the `AtomicBool`
while we could implement that easily ([code](https://gist.github.com/r10s/51373a0697091c6e1c74bdc7e215ef86)),  currently, the DcAccounts object is just never deleted as both, main thread as well as the event loop hold a …

check shutdown

---

assets/help/help.css
src/org/thoughtcrime/securesms/ConnectivityActivity.java
src/org/thoughtcrime/securesms/WebViewActivity.java

`setForceDark()` will be a no-op function in api33, use css-attributes instead
~~moreover, this pr enables webxdc darkmode for older androids - for whatever reason, `setForceDark()` was not called in `WebxdcActivity`~~ EDIT: it was not called for reasons as it not sets dark/light and let the css decide what to do but really changes colors, which usually does not work out, see 2048 app as an example
targets #2599

api33: update webview darkmode, enable webxdc darkmode for older androids

---

AndroidManifest.xml
build.gradle
res/values/strings.xml
src/org/thoughtcrime/securesms/ApplicationPreferencesActivity.java
src/org/thoughtcrime/securesms/ConversationListActivity.java
src/org/thoughtcrime/securesms/ConversationListFragment.java
src/org/thoughtcrime/securesms/components/AttachmentTypeSelector.java
src/org/thoughtcrime/securesms/components/AvatarSelector.java
src/org/thoughtcrime/securesms/database/loaders/RecentPhotosLoader.java
src/org/thoughtcrime/securesms/mms/AttachmentManager.java
src/org/thoughtcrime/securesms/permissions/Permissions.java
src/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java
src/org/thoughtcrime/securesms/qr/BackupTransferActivity.java
src/org/thoughtcrime/securesms/util/Prefs.java

this PR updates targetSdkVersion to 33, compiling and building works, however, this kind if updates usually also comes with behaviour changes (see  https://developer.android.com/about/versions/13/behavior-changes-all ) that need to be checked carefully:
concrete things that do not work at a first glance:
also see [below](https://github.com/deltachat/deltachat-android/pull/2649#issuecomment-1733929228)
general aspects (unticked items need to be checked, please add a summary-IMPACT next to the items then):
closes https://github.com/deltachat/deltachat-android/issues/2599

set targetSdkVersion to 33

---

src/org/thoughtcrime/securesms/ApplicationPreferencesActivity.java
src/org/thoughtcrime/securesms/notifications/NotificationCenter.java
src/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java

this is best-practise according to
https://developer.android.com/develop/ui/views/notifications/notification-permission
moreover, use the same check for displaying the settings.
successor of https://github.com/deltachat/deltachat-android/pull/2695

check areNotificationsEnabled() before adding notification

---

src/org/thoughtcrime/securesms/ApplicationPreferencesActivity.java

this applies changed immediately,
so esp. right-to-left-changes are correct -
but also weird issues wrt wrong language in the title bar on some api should be fixed.
little downside is that after changing the language, you're back to the "main settings page"
and do not stay in the "appearance page";
but you can regard this also as a feature, one tap less.
(only devs want to stay in the language-selection after language-selection - most users will go on with other things
also - other apps reset much more on language changes)
(reason is that the activity is resumed on language changes and the underlying intent does not track fragments currently)
closes #2698

resume settings activity on language changes

---

src/org/thoughtcrime/securesms/ApplicationPreferencesActivity.java

if we do not stay in the appearance page (see https://github.com/deltachat/deltachat-android/pull/2699),
it makes more sense to quit the settings completely.
also, this removes potential other issues with the language change as there is really only the chatlist that needs an update

finish settings on language changes

---

src/org/thoughtcrime/securesms/components/AudioView.java

use only one `audioFocusChangeListener`
as otherwise the "old" will immediately pause
when we restart playing.
moreover, this pr switches to the new `requestAudioFocus()` api
closes #2700

use only one `audioFocusChangeListener`

---

res/layout/conversation_item_footer.xml
res/layout/conversation_item_received.xml
res/layout/conversation_item_received_sticker.xml
res/layout/conversation_item_sent.xml
res/layout/conversation_item_sent_sticker.xml
res/layout/recent_photo_view_item.xml
src/org/thoughtcrime/securesms/BaseConversationItem.java
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/components/AudioView.java
src/org/thoughtcrime/securesms/components/ConversationItemFooter.java
src/org/thoughtcrime/securesms/components/ConversationItemThumbnail.java
src/org/thoughtcrime/securesms/components/DeliveryStatusView.java
src/org/thoughtcrime/securesms/components/DocumentView.java
src/org/thoughtcrime/securesms/components/ThumbnailView.java
src/org/thoughtcrime/securesms/components/WebxdcView.java
src/org/thoughtcrime/securesms/util/Util.java

close #2470 
treat voice messages, audios, videos, documents, webxdc apps, images and stickers as a single unit for screen readers, being able to "activate"/open each of that attachments from the action double-tapping the message without carefully having to select small play buttons etc.
also now the message body is read when a text message is selected instead of just saying "message" and user having to find the text with their finger to read it.
videos are now announced as videos instead of "image"

improve screen reader support in conversations

---

src/org/thoughtcrime/securesms/components/ConversationItemThumbnail.java

this was not causing issues because the new line character and empty footer description don't change the screen-reader output, but still wise to avoid unexpected issues, ex. with recycled views

check if thumbnail's footer is visible in getDescription()

---

src/org/thoughtcrime/securesms/map/MapActivity.java
src/org/thoughtcrime/securesms/map/MapDataManager.java
src/org/thoughtcrime/securesms/util/Prefs.java

save map preferences per account, not only per chat id

---

src/org/thoughtcrime/securesms/notifications/NotificationCenter.java
src/org/thoughtcrime/securesms/util/Prefs.java

the screen-lock functionality was removed in
https://github.com/deltachat/deltachat-android/pull/1942 ; the getters/setters were in use a little longer for a migration device messsage, however, meanwhile this migration is removed as well.

remove dead code

---

CHANGELOG.md
build.gradle

what a loooooong list ... the result of >1w fixing and triaging issues
ftr: these are the current issue/pr stats:

prepare 1.41.0

---

AndroidManifest.xml
src/org/thoughtcrime/securesms/LogViewActivity.java
src/org/thoughtcrime/securesms/MediaPreviewActivity.java
src/org/thoughtcrime/securesms/MessageSelectorFragment.java
src/org/thoughtcrime/securesms/ShareActivity.java
src/org/thoughtcrime/securesms/WelcomeActivity.java
src/org/thoughtcrime/securesms/mms/AttachmentManager.java
src/org/thoughtcrime/securesms/permissions/Permissions.java
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java

fixes #2726 
- EDIT: tried at least import-after-fresh-install, export-image, camera-roll on:
- android5 (sdk21): ok
- android9 (sdk28): ok
- android10 (sdk29): ok
- android11 (sdk30): ok
- _android12 (sdk31): cannot test, emulator issues_
- android12 (sdk32): ok
- android13 (sdk33): ok
- EDIT: tried backup-after-fresh-install-without-any-rights-granted:
- android5 (sdk21): ok
- android9 (sdk28): ok
- android10 (sdk29): ok
- android11 (sdk30): ok
- android12 (sdk32): ok
- android13 (sdk33): ok
_other file access points_ are:
- export media from chat
- export media from gallery
- export keys
- export log
- export backup
- import key
- import backup on welcome screen

fix permissions for ~ android 11

---

src/org/thoughtcrime/securesms/preferences/ChatBackgroundActivity.java

the call to `acceptMenuItem.setEnabled(true);` might cause `NullPointerException`, and it is unnecessary since the menu-item/button is always enabled (ex. resetting the background to default also doesn't call `setEnable(true)` and it works fine)
close #2742

remove unnecessary code in ChatBackgroundActivity

---

src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/ConversationSwipeAnimationHelper.java

fix bug and recycle unused code! :recycle:
when you swipe a message to reply it, the message bubble moves, but if the message has reactions, the reaction pills remain in the same static position and the user avatar touches the reaction pills in groups,
this pull request fixes that issue

move reaction pills together with swiped message bubble

---

res/values/strings.xml
src/org/thoughtcrime/securesms/GroupCreateActivity.java

Before https://github.com/deltachat/deltachat-core-rust/pull/4644, when creating a broadcast list, the UIs didn't ask for a name since the name wasn't shown to the recipients and therefore not that important.
As of https://github.com/deltachat/deltachat-core-rust/pull/4644, broadcast lists will create their own chat for the recipients, showing the broadcast lists's name, so we should ask the user for a name when creating a broadcast list.

Ask for the name when creating a broadcast list

---

res/values-land/attrs.xml
res/values/attrs.xml
src/org/thoughtcrime/securesms/WebxdcActivity.java

isLandscape attribute was introduced initially as part of a complex logic that would set it to true only if in landscape mode AND device screen size was not big (ex. tablets) but later it was decoupled and a dedicated "isBigScreen" was introduced, then isLandscape was just telling if the device is in landscape mode, for that there is no need for this trick using an attribute, screen orientation can be checked directly and is already available in the onConfigurationChanged() event that calls setScreenMode() so there is no need to check an extra attribute

remove unnecessary attribute isLandscape

---

src/org/thoughtcrime/securesms/preferences/widgets/ProfilePreference.java
src/org/thoughtcrime/securesms/qr/QrShowActivity.java
src/org/thoughtcrime/securesms/service/IPCAddAccountsService.java

if you try to change account configuration ex. change address and password and it fails, still the new tried address will be shown in the account overview in settings and some other places

use CONFIG_CONFIGURED_ADDRESS instead of CONFIG_ADDRESS

---

src/org/thoughtcrime/securesms/ConversationListActivity.java
src/org/thoughtcrime/securesms/accounts/AccountSelectionListFragment.java

avatar and title appears as one unit to the user;
doing different things on taps in the avatar (open account switcher) and the title (open connectivity)
is confusing - and also easily done wrong.
this pr always opens the account switcher;
to get to the connetivity view,
there is a static button inside the account switchter.

always open account switcher from main title bar

---

androidTest/com/b44t/messenger/uitests/offline/SharingTest.java
src/org/thoughtcrime/securesms/NewConversationActivity.java
src/org/thoughtcrime/securesms/ShareActivity.java
src/org/thoughtcrime/securesms/util/MailtoUtil.java

That's https://github.com/deltachat/deltachat-android/pull/2637 which was (probably accidentally) dropped out when renaming `stable` to `main` and `main` to `feat/verified-1to1`.
@r10s would you like this to go into 1.41? It might be better to wait until 1.42, since sharing is an area with lots of regressions, and 1.42 is not that far out.

Merge "improve mailto Intent handling in ShareActivity" into main

---

src/org/thoughtcrime/securesms/connect/DcHelper.java

there is no need to push ppl to re-scan a qr-code at this point (in contrast to protection-broken-dialog)

remove scan-qr-button from protection-ok-dialog, fix url

---

src/org/thoughtcrime/securesms/connect/DcEventCenter.java
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java
src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java

this starts all backups at the same time,
overwriting different progress-dialogs as needed.
when the last "done" arrives, the progress dialog is closed. the progress itself, is taken from the first account (this could be improved, but maybe it is just good enough)
best review without whitespace as indentation has changes.
needs lots of testing.

start all backups

---

src/org/thoughtcrime/securesms/GroupCreateActivity.java

don't ask to create verified group if the user is creating a broadcast list

fix bug in group creation activity

---

res/values/strings.xml
src/org/thoughtcrime/securesms/connect/DcEventCenter.java
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java
src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java

~~:warning:  before this gets merged, would be nicer if core sets the account address in the backup filename~~ (DONE: https://github.com/deltachat/deltachat-core-rust/issues/4816)

allow to backup/export all accounts at once

---

res/layout/group_create_activity.xml
src/org/thoughtcrime/securesms/GroupCreateActivity.java

before if was just 'Name',
which can lead to confusion
when heading instructions as "create a group with that person": one may create a group and enter the email address to "Name" ...
same with 'Broadcast List Name'
cc @hpk42 @link2xt @kermoshina 
this pr will probably mitigate confusion, we can think over additional changes when this problems happens more often

use 'Group Name' as placeholder for group name

---

src/org/thoughtcrime/securesms/GroupCreateActivity.java

this pr removes the remove "use guaranteed e2ee?" question and instead creates a verified group when all members are verified.
this Yes/No question is a hard one.
this turns out last, not least,
when trying to use self-explaining buttons for iOS without using the term "verified groups".
what would be "No"? "Best-Effort-Encryption"?, "I don't care"? :)
joking aside,
few ppl will really read the question on group creation, let alone understanding it and making and informed decision.
many ppl will just tap the rightmost button,
just to continue.
so better go with defaults here until we get
a real usecase where we would need this question.
and then consider how to solve that usecase
without reintroducing weird questions.
this pr is the outcome of longer discussions with @link2xt and @hpk42 ; …

remove "use guaranteed e2ee?" question

---

res/menu/profile_common.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/GroupCreateActivity.java
src/org/thoughtcrime/securesms/ProfileActivity.java

close #2786 
this allows to upgrade existing non-verified groups to verified  by drafting a new group and then getting the chance to make it verified if all contacts are verified, thanks to recent changes in the group creation workflow

allow to clone groups and broadcasts

---

src/org/thoughtcrime/securesms/ContactSelectionListFragment.java

the created new contact via the "new contact" button can't be added to the verified group anyways
this also fixes existing crash on master if you try to press the "new contact" button in a verified group because it was assumed all items where contacts and then it is tried to check isVerified() in a null pointer reference since the "new contact" item doesn't holds any real DcContact

don't display "new contact" in verified group contact selection

---

res/values/strings.xml

this pr aims to target one outcome of the recent user testing with @kermoshina , where one finding was that the "Interaction between encryption and verification is difficult to understand." and the explanations tell about end-to-end-encryption and it is unclear how this relates to "verified checkmarks" or "verified contacts" or "verified groups". 
as the term "end-to-end-encryption" is roughly known by users due to whatsapp - but the term "verified" not and is very interpretive, this pr removes this term completely. 
we do no longer talk about verification at all, we talk about "guaranteed end-to-end-encryption" that relates to "green checkmarks" - this seems easier to understand as before (iirc @Hocuri already tried to avoid too many terms and avoided to say "verified chats" or so; this …

remove "verified" from strings

---

res/values/strings.xml
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java

these comparable complicated strings are duplicated and also partly wrong (eg. autocrypt does not talk about "keys")
once this is merged, ios should adapt to now missing %1$1 in autocrypt_send_asm_explain_after and we can file a pr for desktop using the new strings. once next android-string-cleanup, the duplicate strings can be deleted

cleanup chore: target duplicate autocrypt strings

---

src/org/thoughtcrime/securesms/ConversationTitleView.java

the contact profiles mix of contact and chat data for the ease of the user.
the contact profile title,
however, shall show the state of the chat (chat_is_protected()) and not the state of the contact (contact_is_verified()) to make things easier to understand and to be in sync with groups - and also with what we're saying in the faq
at https://github.com/deltachat/deltachat-pages/pull/746 :
> "contact profiles show a green checkmark
> if messaging a contact is guaranteed to be end-to-end encrypted."

contact profiles show chat's green checkmarks

---

src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java

using display name and email address adds quite some noise, esp. if the email addresses are long and non-telling, this does not really add sth. to "security".
depending one the language, this issue may be even worse.
the verified-by address is shown bigger that the address of the contact itself.
it just looks bad.
the idea of showing the address was only to "protect" against ppl that set their name to "You" or "Me" - however, this trick is maybe a joke but no security issue, it was not really thought to the end:
- the verifier is always a directly verified, known contact
- we do not regard verified contacts as enemies
- the "Me" or "You" is visible and annoying at quite more visible placed
- you can always tap the row and will see that this is just a contact with a weird name (iOS, eg. …

use display name for verified-by row

---

src/org/thoughtcrime/securesms/ConversationTitleView.java

This reverts commit f6c4e189e3b35989acc30396a495d310868022ef.
after lots of discussion (#2836, https://github.com/deltachat/deltachat-core-rust/pull/4966), contact-profiles-without-chat, should show is_verified() for the green checkmarks as in the past.
it still makes sense to streamline the android code, but that is another issue.

Revert "contact profiles show chat's green checkmarks"

---

CHANGELOG.md
build.gradle

@link2xt if there is more in the queue, we should maybe better wait for a new core?
we can also brand this update as 1.42.0, however i'd update the help links before then (i think i prepare https://github.com/deltachat/deltachat-pages/pull/746 anyways now)

Prepare 1.41.8

---

src/org/thoughtcrime/securesms/NewConversationActivity.java

this pr fixes my findings at https://github.com/deltachat/deltachat-android/issues/2871#issuecomment-1816239147 by looking up the contact-id before creating it with an empty name.
in general, it seems undefined if you call createContact() with an empty name on an existing address with a name set. as createContact() is really only for "user input", it is probably okay to reset the name (and it was wrong to use this function here, maybe a relict from the old UI; the code is also overcomplex as it passes addresses though where IDs should be good enough, but yes ...)
it need to be tested if this pr also fixes the issue @gerryfrancis reported at #2871 EDIT: closes #2871

fix contact creation

---

metadata/en-US/changelogs/6744.txt

according to [RELEASE.md](https://github.com/deltachat/deltachat-android/blob/main/RELEASE.md#release-on-f-droid):
- changelog created (based on device message)
- after merging this pr,  
`git tag v1.2.1; git push --tags`
needs to be called on branch `main`
/me a bit more careful this time :) but we have some precautions, obviously bad core should not build because of #2647, main is clean, i disable "git commit -a", there is no confusion between stable/master, and there are no recent api changes in core, and we're not _that_ much in a hurry ...

prepare f-droid 1.42.3

---

src/org/thoughtcrime/securesms/LocalHelpActivity.java

the anchor must not be taken into account when checking for the existance of the asset file.
closes #2883
cmp #2842
i'd like to get that in before the 1.42 update

fix localized deep links to help

---

CHANGELOG.md
build.gradle
metadata/en-US/changelogs/6754.txt

this mainly pulls in recent core.
as f-droid already read the 1.42.3 tag (but did not build yet), better add the 1.42.4 tag directly after merging using `git tag v1.42.4; git push --tags` (fdroid changelog summary can stay as is)

prepare 1.42.4

---

res/values/strings.xml
src/org/thoughtcrime/securesms/connect/DcHelper.java

remove stock-string for old default signature.
ios/desktop also do not used that string, so even removing from translations is fine; on next "tx pull", the string will also be removed from all translations.
closes #2904

remove unused stock-string

---

res/values/strings.xml

the hint already led to confusion on 37c3 testings of chatmail.
the hint that appears when a one-to-one-chat was just created manually (by entering an email address manually) is a bit misleading when using chatmail, as it says it 'does not matter if the other side uses Delta Chat'.
this is still true, however, with chatmail it is needed that messages outside the chatmail-server are encrypted,
which is arguably not so easy without delta chat and QR code scanning.
this PR therefore just removes the hint (alternative suggestions welcome);
it would still be great if the error message 'cannot encrypt' is improved, however, this is another thing.
before/after:
once merged, `./scripts/tx-update-changed-sources.sh` needs to be executed; ios/desktop will get the updated string automatically

make 1to1-empty-hint working better with chatmail

---

src/org/thoughtcrime/securesms/ConversationTitleView.java

with chatmail, the address is less meaningful,
it seems sufficient to show it in the profiles.
this moves focus to name and avatar and leave the email address as a "handle" that is not that meaningful and also subject to change, you check it on issues, similar to keys, similar to most other messengers.
this PR is not really a requirement for chatmail, however, tuning down the address is also reasonable by other means as the idea of changing addresses (AEAP) or even using more addresses per account

do not show addr in guaranteed-e2ee chat titles

---

res/values/strings.xml
src/org/thoughtcrime/securesms/CreateProfileActivity.java

with this PR, empty display names are no longer accepted. instead, a warning is shown.
moreover, the PR rewords the hint above the input field, which is also used by iOS and desktop soon; for review, there should be some focus on the text therefore.
(maybe the "for your new account" can be left out, that would make the scope of the name clearer)
re-layout etc. are out of scope of this PR.
closes #2913

force a display name to be set

---

AndroidManifest.xml
src/org/thoughtcrime/securesms/ConversationListActivity.java

register to handle i.delta.chat links

---

src/org/thoughtcrime/securesms/ConversationListItem.java

'pinned' chats are always shown together below each other; moving the 'pinned' indicator to the same position in each chat makes the UI a little less cluttered and nicer
(all pinned indicators will form a column if you will)
this PR is an outcome of the feature-proposal at https://support.delta.chat/t/three-small-changes-to-make-delta-chat-better/2886

move 'pinned' indicator right for cleaner UI

---

res/layout/contact_filter_toolbar.xml
src/org/thoughtcrime/securesms/BlockedContactsActivity.java
src/org/thoughtcrime/securesms/ContactSelectionListFragment.java
src/org/thoughtcrime/securesms/NewConversationActivity.java
src/org/thoughtcrime/securesms/connect/DcContactsLoader.java
src/org/thoughtcrime/securesms/contacts/ContactSelectionListAdapter.java

this PR add a 'Scan QR Code' button to 'New Chat' activity.
this makes setting up contacts easier when the best option is scanning a QR code (as for chatmail).
closes #2911 
EDIT: i think, best would be to combine "New Contact" and "QR Invite Code" to one item that offers QR code scanning by default and "Share Invite Link" an "Manual Setup" as option. we can also think over renaming the options. but that is another PR/discussion, the PR at hand already improves things

add 'Scan QR Code' to 'New Chat'

---

src/org/thoughtcrime/securesms/ConversationListActivity.java
src/org/thoughtcrime/securesms/CreateProfileActivity.java
src/org/thoughtcrime/securesms/WelcomeActivity.java

on new installations or accounts,
the "What's new?" messages only clutter the device messages with unimportant information (either the user is new to the app, so everyrhing is new and nothing is changed, or an existing user has created a new account, they have seen the changelog anyways)
in other words,
the changelog will be added only for updates.
when reading https://c.delta.chat/classdc__context__t.html#a1a2aad98bd23c1d21ee42374e241f389 , this was always the gist,
however, somehow forgotten or removed on the way :)
targets #2914

do not add "Changelog" for new accounts

---

src/org/thoughtcrime/securesms/ConversationActivity.java

this was a hack I added to try to compensate the lack of event for "contact is not longer seen-recently" and to update the seen-recently indicator (green dot) after that core was improved to emit contact-changed event to properly update the seen-recently status

remove old hack to update seen-recently indicator

---

res/values/strings.xml
src/com/b44t/messenger/DcMsg.java
src/org/thoughtcrime/securesms/BaseConversationItem.java
src/org/thoughtcrime/securesms/ConversationUpdateItem.java
src/org/thoughtcrime/securesms/connect/DcHelper.java

This PR refines the "Invalid Unencrypted" info messages that is added since  https://github.com/deltachat/deltachat-core-rust/pull/5198 when a message cannot be encrypted _and_ the provider does not allow unencrypted messages; this is true eg. for chatmail
In addition to stock core message:
- a "Tap to learn more" is added
- a tap shows a little dialog, allowing to perform a QR code scan or get more help about the scanning process (this seems mostly on-point to solve the user's problem at hand, and probably mostly good enough for now, we can always refine as needed)
@adbenitez this PR also removes linkifying info-messages in general - do we know of any info-messages that contain links _on purpose_? if so, we can make the linkify-removal conditional.

improve status message for "Invalid Unencrypted"

---

res/menu/conversation_list.xml
src/org/thoughtcrime/securesms/ConversationListFragment.java

this allows to mute a noisy chat you can't attend to at the moment without entering it and marking as read messages you don't intend to read at the moment and sending read receipts to the peer
also allows to mute/unmute chats in batches without having to do it one by one

allow to mute/unmute from chatlist

---

src/org/thoughtcrime/securesms/util/LongClickCopySpan.java
src/org/thoughtcrime/securesms/util/Util.java

currently when user click a link in a message, the handling is passed to the system which then select the app that handles links, for invite-URLs that apps is Delta Chat itself so the chatlist activity is launched and user gets a dialog with a question "do you want to join group X?" even if user cancels the dialog, context is already lost and user has to re-enter the chat they were
with this PR, the invitation link is handled sooner, without the extra round-trips and the dialog appears in-place giving chance to the user to just cancel in case of a miss-click etc

handle in-chat clicks to invite-URLs

---

src/org/thoughtcrime/securesms/util/Util.java

catch errors thrown by Uri.parse() to avoid crashes on tapping invite links

catch errors thrown by Uri.parse()

---

src/org/thoughtcrime/securesms/ContactSelectionListFragment.java
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
src/org/thoughtcrime/securesms/util/Prefs.java

while working on the [iOS counterpart](https://github.com/deltachat/deltachat-ios/pull/2069), i came to the conclusion that it is much better to have a per-account setting here
this fits better to chatmail:
- one can have chatmail=OFF and normal-mail=ON
- new accounts are most often chatmail, even if there is a normal-mail account, and get the setting OFF, which is better in most cases
- the option more "fades out" this way :)

make 'Read Address Book' a per-account option

---

res/xml/preferences_advanced.xml
src/com/b44t/messenger/rpc/Rpc.java
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java

Depends on https://github.com/deltachat/deltachat-core-rust/pull/5129
Part of https://github.com/deltachat/deltachat-android/issues/2909

Self-reporting, Android UI

---

res/values/strings.xml

`new_messages_body` is used for a generic notification message in case we do not know anything about the new message apart from the fact that there _is_  a new message. currently, this is used on iOS only and looks like the following:

add generic 'body' text for new messages and add translators hints

---

scripts/clean-core.sh

the idea of the script
is to prune all possible caches
that may cause problems when updating core.
it is run usually before a release
and to make sure a core is rebuild from scratch.

tweak scripts/clean-core.sh

---

AndroidManifest.xml
build.gradle
res/layout/conversation_fragment.xml
res/layout/reaction_picker.xml
src/org/thoughtcrime/securesms/reactions/AddReactionView.java

using the existing reaction picker seems to be a pain as it is bound very close to our keyboard - and would also need special casing if it is not used.
therefore, this PR goes for using https://developer.android.com/develop/ui/views/text-and-emoji/emoji-picker , which had some building issues (see commit messages), however, seems straight-forward.
also, only very few lines of codes are needed.
~~however, for whatever reason, emoji do not show up in the picker.  when tapping the empty space in the picker, the app crashes. might be because of kotlin, because of a missing dependency, or excluded bit, whatnot. @adbenitez can you try this as well and maybe have a closer look?~~ EDIT: thanks a lot for fixing and for taking over this PR, this is very welcome! 💯
size-wise, this PR adds about 1mb …

react with any emoji

---

res/values/strings.xml
src/org/thoughtcrime/securesms/connect/DcHelper.java

this PR makes the strings `You reacted 🤘 to "Nice photos!"` etc. translatable and gives translations to core.
moreover, this PR picks up suggestions and alternatives wrt translations and adds them as translator's hints.
see for details https://github.com/deltachat/deltachat-core-rust/pull/5387

add strings needed by core to show reactions in summaries

---

src/org/thoughtcrime/securesms/ConversationListFragment.java

next core will show reactions in the chatlist's summaries, see https://github.com/deltachat/deltachat-core-rust/pull/5387 for details and reasoning
there is not more to do in UI other than updating the chatlist on DC_EVENT_REACTIONS_CHANGED

add support for "reaction summaries"

---

res/values/strings.xml

for desktop, the QR code scanning hint "Hold your camera over the QR code." is often not practical.
this PR adds the often better fitting string "Move the QR code to the camera."
see https://github.com/deltachat/deltachat-desktop/pull/3762

add QR code scanning hint better fitting for desktop

---

src/org/thoughtcrime/securesms/FullMsgActivity.java
src/org/thoughtcrime/securesms/WebViewActivity.java
src/org/thoughtcrime/securesms/WebxdcActivity.java

support request_internet_access again

---

src/org/thoughtcrime/securesms/LocalHelpActivity.java
src/org/thoughtcrime/securesms/PassphraseRequiredActionBarActivity.java
src/org/thoughtcrime/securesms/qr/BackupTransferActivity.java
src/org/thoughtcrime/securesms/qr/RegistrationQrActivity.java

close #2994 
after this is merged, we could then easily merge `PassphraseRequiredActionBarActivity` and `BaseActionBarActivity`

allow to open troubleshooting menu option directly from offline help

---

src/org/thoughtcrime/securesms/WebxdcActivity.java

adding a webxdc-shortcut to the home screen is sometimes a request only,
the user has to confirm and/or there is a subsequent dialog.
so, when `requestPinShortcut()` returns successfully, saying "Done" as the result of "Add to Home Screen" is often wrong from the view of the user.
however, some feedback is still needed for the cases there are no dialogs.
saying "One moment..." covers both cases sufficiently.
<i>this is a bit misleading</i>
(came over that when playing with webxdc  during review of https://github.com/deltachat/deltachat-android/pull/3008 )

don't say 'Done' when we do not know we're done

---

src/org/thoughtcrime/securesms/WebViewActivity.java
src/org/thoughtcrime/securesms/WebxdcActivity.java

fix bug recently introduced by #2988 
mailto/openpgp4fpr was not handled in openOnlineUrl() which caused it to be handled in interceptRequest() which only expects HTTP(S) requests
this also allows to open openpgp4fpr links (only mailto was supported in the past) as DC desktop does (what is needed by the [Public Bots Index](https://github.com/deltachat-bot/public-bots))

fix openOnlineUrl(), mailto/openpgp4fpr has to open externally

---

res/values/strings.xml

this PR extracts  new strings from [deltachat/deltachat-desktop#3773](https://github.com/deltachat/deltachat-desktop/pull/3773/files#diff-5bd8446ffbbe28eb2eacda360fd1fa0640832786a9170440fe58275a4190102b).
the following strings were not added as they are existing already in a sufficient way (desktop PR needs to be changed):
`onboarding_title` -> `welcome_desktop` (exclamation mark can be added later)
`onboarding_subtitle` -> `welcome_chat_over_email` (dot can be removed later)
`onboarding_scan_qr_code` -> `qrscan_title`
`multidevice_setup_option` -> `multidevice_receiver_title`
`import_backup_option` -> `import_backup_title` (iirc, it was renamed to "restore" on purpose, let's stay with that for now)
`instant_onboarding_confirm_label` -> `ok` (this is used in a message box, right? i would …

add strings needed for instant onboarding

---

res/values/strings.xml

instead of saying that there are no Delta Chat servers, say that things are local only.
reason is the onboarding with the default chatmail server - and although they're probably not used when ppl go to this "Manual Setup", it is good to reword that in a form that cannot be misunderstood.
the key of the string stays as is, this makes changes in UI effortless - translators will see the change anyways.
closes https://github.com/deltachat/interface/issues/64

adapt no-servers hint

---

res/layout/profile_create_activity.xml
res/values/strings.xml
res/xml/preferences_advanced.xml
res/xml/preferences_chats.xml
src/org/thoughtcrime/securesms/CreateProfileActivity.java
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java
src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java

this PR is an outcome of an discussion with @hpk42 :
with the new instant onboarding, classic email move from "recommended workflow" to "supported workflow", meaning that the corresponding options should go to "advanced".
concretely, these are the options "show classic email" and "password & account".
moreover, this PR resorts the advanced settings so that the more important ones are shown first - so we start with **show-classic-mail/send/stats/log**, followed by **experimental** (we want ppl to try things out to get feedback), **app-access/encryption** (discouraged things) and finally **account/password/imap-options** (discouraged, often not needed - but bottommost is also not that bad for these kind of settings) (i know, AEAP is there, but that is not bulletproof enough to become a …

reorder settings

---

AndroidManifest.xml
build.gradle
google-services.json
jni/dc_wrapper.c
src/com/b44t/messenger/DcAccounts.java
src/org/thoughtcrime/securesms/ApplicationContext.java
src/org/thoughtcrime/securesms/LogViewFragment.java
src/org/thoughtcrime/securesms/notifications/FcmReceiveService.java

this PR adds Firebase Clould Notifications (FCM), see #2998 for details and reasoning
the FCM token is get unconditionally currently. when the server pings us, we do nothing special - at that moment, the app should just be started (again) and process messages.
we should get this PR in to **gather feedback on a beta-version** if there are any issues of running on real devices (google and non-googles) - even if the server is not yet ready.
subsequent tasks in **another PR:** 
- init more gracefully together with POST_NOTIFICATION and other background-checks
- consider adding options and/or ask on startup
- reorganize `build.gradle`, so that `com.b44t.messenger` flavour (used for f-droid) is build without FCM - `chat.delta` and `com.b44t.messenger.beta` should stay as is
tasks done:
in …

add FCM PUSH notification support

---

src/org/thoughtcrime/securesms/InstantOnboardingActivity.java
src/org/thoughtcrime/securesms/WelcomeActivity.java
src/org/thoughtcrime/securesms/connect/AccountManager.java
src/org/thoughtcrime/securesms/qr/QrCodeHandler.java

- fix: when scanning "add as second device" QR code from chatlist's QR button open WelcomeActivity, not InstantOnboardingActivity
- fix: InstantOnboardingActivity: go back to chatlist when back button is pressed and we don't come from WelcomeActivity
- remove unused code in WelcomeActivity
followup of #3015

fix bugs and some code cleanup

---

src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java

this PR  adds a 'cancel' button to 'manage keys'; that was somehow missing

add 'cancel' button to 'manage keys'

---

AndroidManifest.xml

close #2999 
the issue was introduced in #2975 
the new dependency [SafeContentResolver ](https://github.com/cketti/SafeContentResolver?tab=readme-ov-file) says:
> Replace all occurrences of ContentResolver.openInputStream() where URIs provided by other apps are opened with SafeContentResolver.openInputStream().
>
> SafeContentResolver will refuse to open file:// URIs pointing to files belonging to your app and content:// URIs belonging to content providers of your app.
If you wish to allow access to certain content providers, add the following <meta-data> element to the appropriate <provider> entries in your manifest
so not only `file://` are rejected, also `content://` URIs are rejected if they point to content of the Delta Chat app, but this doesn't consider the situation when you want …

fix: allow to share attachments from one chat to another

---

src/org/thoughtcrime/securesms/notifications/FcmReceiveService.java

came over that, when trying to make sense why FCM onMessageReceived() is not called.
our current strategy is to just let the app run on received PUSH, however, it is useful to log this information for debugging
this is the corresponding code, btw ...
https://github.com/firebase/firebase-android-sdk/blob/2a75605db0cfac05c1634f911a0c1f7751599035/firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessagingService.java#L124
... i also tried to set a breakpoint in the handleIntent(), but even that is not called

log if we receive onDeletedMessages()

---

src/org/thoughtcrime/securesms/mms/SignalGlideModule.java

close #2957 
the APNG decoder is too problematic and has caused similar "blank images" due to other bugs in normal PNG in the past, as APNG images are kind of rare and not widely supported (they are animated PNG but also at the same time can be displayed as  normal still PNG) it is better to disable the decoder and just display APNG as normal PNG
I reported the bug to upstream in https://github.com/penfeizhou/APNG4Android/issues/217 if eventually it gets more stable or does fallback to PNG in case the APNG decoder  fails, we can reconsider enabling it again

disable APNG decoder

---

src/org/thoughtcrime/securesms/geolocation/DcLocation.java
src/org/thoughtcrime/securesms/geolocation/DcLocationManager.java
src/org/thoughtcrime/securesms/geolocation/LocationBackgroundService.java

close #3037 
this also solves this issue: even if you already had location set with dcContext.setLocation(), a chat will only get location in messages when dcContext.setLocation is called again after the location streaming was enabled for the new chat, so you could have situations where you stream location for one chat in every sent message, but in another chat where you enabled it recently it would not work

use last known location if it is recent enough

---

res/values/strings.xml
src/org/thoughtcrime/securesms/connect/DcHelper.java

this PR adds the strings for the new 'please wait' securejoin flow.
background: when https://github.com/deltachat/deltachat-core-rust/pull/5550 gets merged, a one-to-one chat is read only the first seconds:
- **either** until the protocol finishes. if both devices are line and connection is fine already after 1 or 2 seconds, this should be how things should usually go:<br><img width=250 src=https://github.com/deltachat/deltachat-android/assets/9800740/55519a34-6c8f-4024-a20b-2c86f22faa76>
- **or**, on bad network or if devices are offline, we start with the same "please wait" message (we do not know yet that things will last) - after 15 seconds sending is allowed, but ppl will get a warning and can message already - if devices get online again or network gets better, also then in the …

add strings for new 'please wait' securejoin flow

---

src/com/b44t/messenger/DcContext.java
src/org/thoughtcrime/securesms/ContactSelectionListFragment.java
src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java

this PR makes use of the `is_chatmail` config introduced by https://github.com/deltachat/deltachat-core-rust/pull/5567 and hides the IMAP folder options.
~~for whatever reason, `is_chatmail` is currently always `0` (also in "View Log" which is generated by core directly),  might be things are not rolled out yet.~~ EDIT: works now, see below
this is what it will look like:
targets https://github.com/deltachat/deltachat-core-rust/issues/5380
when this PR gets merged, we need to file issues/PR for the same change on desktop/ios

hide IMAP folder options on chatmail

---

res/values/strings.xml

prefer 'Profile' wording as discussed with @hpk42, @kermoshina, @adbenitez and other
the term  'Accounts' is left only for classic email in advanced settings. moreover, this PR changes some related things, as 'Inbox' and 'Signature'.
this PR only changes strings, after merge, we need to run `./scripts/tx-update-changed-sources.sh`
changes wrt "QR code" and "Explore Other Options" and policy-link are left for subsequent PR

prefer 'Profile' wording

---

src/org/thoughtcrime/securesms/ConversationItem.java

only after https://github.com/deltachat/deltachat-core-rust/pull/5585 is merged will this be visible, but this already can be merged without waiting  for it since it is just an internal change in DcMsg.getOverrideSenderName() that was not setting the overridden sender name for outgoing messages

show overridden sender name also for self messages if present

---

res/layout/instant_onboarding_activity.xml
res/layout/login_options_view.xml
res/layout/signup_options_view.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/InstantOnboardingActivity.java
src/org/thoughtcrime/securesms/WelcomeActivity.java

after some internal discussion with @link2xt @hpk42 @adbenitez, "Manual Log In" still creates a client-side profile on the client, and therefore it makes some sense to move it to the first "Create New Profile" button.
this makes the "i already have a log in" pretty bulletproof, also, it seems less probable ppl will try to somehow manually login there. idea is also that ppl will less often "just so manually log in" - as the "create new profile" is sth else than "log in". but well, user testing will tell.
moreover, this PR takes the chance to move the "scan qr code" button to "other options" as well.
"explorer other options" is a bit more visible as before (where the text was smaller and gray), however, by its position still  pretty much tuned down; this is on purpose as the user really …

move 'manual log in' to 'create profile'

---

src/org/thoughtcrime/securesms/ConversationListActivity.java
src/org/thoughtcrime/securesms/util/Prefs.java

otherwise, the message pops up again on every account switch, which is quite annoying

show the device-update-message only once, not on every account switch

---

src/org/thoughtcrime/securesms/ConversationListFragment.java
src/org/thoughtcrime/securesms/components/reminder/DozeReminder.java
src/org/thoughtcrime/securesms/notifications/FcmReceiveService.java

do not ask for "disable battery optimisations" when all accounts are chatmail _and_ we got a push token.
with chatmail, we reduced the number of questions from three to only one (or zero for android<=12):
if classic mail is used, the following questions follow - either for the first account, but also anytime later when a non-chatmail is added:
the push token, however, is got unconditionally from the other states - it is a cheap call, the device is connected to the PUSH server anyways and we want to leave it up to core what to do with it

tweak asking for "disable battery optimisations"

---

src/org/thoughtcrime/securesms/components/reminder/DozeReminder.java

the check before was too implicit and relied on DOZE_ASKED_DIRECTLY only.
but if the user was asked one time and went for chatmail again, it did not work and the user was getting the message "please enable 'ignore battery optimisations'"
even though they were using chatmail-only.

check if push is sufficient before adding device message

---

res/values/strings.xml
res/xml/preferences_notifications.xml
src/org/thoughtcrime/securesms/ApplicationContext.java
src/org/thoughtcrime/securesms/LogViewFragment.java
src/org/thoughtcrime/securesms/notifications/FcmReceiveService.java
src/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java
src/org/thoughtcrime/securesms/util/Prefs.java

for a subsequent PR: link to the help topic `instant-delivery` from https://github.com/deltachat/deltachat-pages/pull/883

add a switch for push notifications

---

src/org/thoughtcrime/securesms/InstantOnboardingActivity.java

the problem is that in welcome screen we obviously switch to new account, also the case when user has selected an account and then scan dcaccount QR, it first switch to a new account before invoking InstantOnboarding screen, but the direct dcaccount:// URI handling happens by the system that directly opens the activity so we need to check that in the activity and create new account if needed

switch to new account when opening DCACCOUNT:// URIs

---

RELEASE.md

seen a similar hint for other apps,
it is useful to give interested users a clue
why they have a feature but others may not.
counterpart of https://github.com/deltachat/deltachat-ios/pull/2194

hint user that rollout may take time

---

CHANGELOG.md
build.gradle
metadata/en-US/changelogs/6864.txt

only change compared to 1.46.2 is that FCM is disabled for default/fdroid buils.
this version will go to fdroid, no need to push it to gplay.
after merging, we should follow the instructions from RELEASE.md:
```
git tag v1.46.3; git push --tags
```

prepare 1.46.3

---

src/main/java/org/thoughtcrime/securesms/BaseConversationListFragment.java

exiting 'select mode' is unexpected when hitting 'cancel' - the user may still want to do other things with the selection.
this makes the 'mute' behavior consisten with other cases showing a dialog, eg. 'delete'

cancel muting should not exit select-mode

---

src/main/java/com/b44t/messenger/rpc/Rpc.java
src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java
src/main/java/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
src/main/res/raw/webxdc.js
src/main/res/values/strings.xml
src/main/res/xml/preferences_advanced.xml

add support for RealtimeChannel API

---

src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java
src/main/java/org/thoughtcrime/securesms/util/Prefs.java

came over that while targeting https://github.com/deltachat/deltachat-ios/pull/2204 and was shortly confused about what is going on there :)
(the name saved to database is not changed, however, to avoid popping up the message again in case we do an update without a new device messase)

use name `deviceMsgLabel` as it is a label and no id

---

src/main/java/org/thoughtcrime/securesms/BaseConversationListFragment.java
src/main/res/menu/conversation_list.xml
src/main/res/values/strings.xml

close #3128 
user can select certain chats they want to mark as seen, they still can mark as sen all by using "select all" and then use "mark all as read"

allow to mark as read selected chats

---

src/main/res/values/strings.xml

before, "Info" and "Message Details" were used for the same things synonymously,
this is an issue mostly in the context menus,
where eg. iOS had "Info" but desktop did not -
and android had an "i"-icon ...
but also, tapping 'Info' and then getting a different title (not only a longer version) is not super-nice.
with this change, everything is "Info", making also the "i"-icon fit. this is also consistent with WhatsApp.
Signal has the same mess as we before, at least on iOS.
once this is merged, `./scripts/tx-update-changed-sources.sh` needs to be run

consolidate wording for "Message Info"

---

src/main/java/org/thoughtcrime/securesms/ConversationListFragment.java
src/main/res/layout/conversation_list_fragment.xml

the string is deprecated and also no longer used on desktop/iOS.
the 'empty state view' where the string could appear is anyways not shown often
(usually, there is 'saved messages' and 'device messages'), so it also does not make sense to think over a replacement.
the string as such can be removed in a subsequent PR when we cleanup unused strings.

remove deprecated hint 'chat with any email'

---

src/main/java/com/b44t/messenger/DcContext.java
src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java
src/main/java/org/thoughtcrime/securesms/WelcomeActivity.java
src/main/java/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java
src/main/java/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java
src/main/java/org/thoughtcrime/securesms/qr/BackupProviderFragment.java
src/main/java/org/thoughtcrime/securesms/qr/BackupReceiverFragment.java
src/main/res/values/arrays.xml
src/main/res/values/strings.xml

this PR aims to help saving disk space on chatmail servers by deleting messages _at once after download_ for new profiles (new profiles are usually not multi device, and multi device is the only reason to keep messages longer).
when we later get a hint that the user _might_ set up a second device, we go back to _automatic/never_ - which was the default up to now.
we assume that we will save 90% or more space by that as many user never set up a second device.
this PR also makes the available options a bit clearer (only two are left for chatmail, normal server still have opions as week/month/year) and adds a warning when an option may break multi device:
moreover, for chatmail the the alarming confirmation dialog is removed - there is anyways an auto-deletion and  hints as "Do not use this …

save chatmail diskspace by tweaking autodelete-from-server

---

src/main/java/org/thoughtcrime/securesms/qr/QrActivity.java

QrShowFragment is used by some menu entries
available also when the fragment is not displayed; therefore, creation on displaying is too late.
(the crash is present only on some android versions, as many android versions seem to create "neighboured tabs" anyways - so there should also not be much performance loss)
closes #3156 
nb: i could not reproduce the issue, fix just by checking log

create QrShowFragment in time

---

src/main/java/org/thoughtcrime/securesms/util/MailtoUtil.java

if the value part is missing,
it otherwise crashes when calling MailtoUtil.getText() and the exception is not handled there (it is not in at least one case).
therefore, just catch the exception in this cornercase (same for bad encoding) and return an empty string.
nb: i could not reproduce, however, the reported crash is pretty obvious
closes #3157

fix crash on some mailto: links

---

src/main/java/org/thoughtcrime/securesms/ConversationTitleView.java
src/main/java/org/thoughtcrime/securesms/ProfileActivity.java
src/main/res/menu/profile_common.xml
src/main/res/menu/profile_title_context.xml

copying email addresses to the clipboard
is not proper way to get in contact in the light of chatmail - even if the account is non-chatmail, the receiver may use chatmail. or the copied contact.
it is better to point ppl to use 'Share' or 'Attach Contact' therfore and not offer failing/corner-case things in the primary menu.
therefore, we do basically the same what desktop is doing all the years: no special function, however, if you select text (desktop) or long tap it (android now), you can copy it.
nb: for whatever reason, we're not using context menu before, so it makes sense to double check if things are working as expected
_left: long-tap the address text, right: the cleaned up "main options"_
(i was also considering [removing copying the address …

tune down copying email address

---

src/main/java/org/thoughtcrime/securesms/RegistrationActivity.java

this helps avoid issues like user changing email address and password and pressing "configure" button without realizing they have custom imap, smpt, etc. settings
this already happened to a friend when I was trying to help them to migrate to a chatmail address, it was really confusing because address was changed and configuration succeed but it took me a while realize that the client was actually connecting to a different IMAP/SMTP server without even using the new set address and password because it was using the manual configuration set in advanced

expand advanced settings if they are modified

---

src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java
src/main/res/values/strings.xml

this PR remove old 'read receipt' stock string, it is questionable if we want to have translations for the new one, cmp #3145 
closes #3179

read receipt stock string

---

src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
src/main/java/org/thoughtcrime/securesms/util/Util.java
src/main/res/menu/conversation.xml
src/main/res/menu/conversation_archive.xml
src/main/res/menu/conversation_clear.xml
src/main/res/menu/conversation_delete.xml
src/main/res/menu/conversation_push_group_options.xml

this PR removes less often used and dangerous options of a chat to a new "more" menu - the old menu was just a little big.
- "Archive" is not considered less often used, it is often used as a common pattern to handle chats
- "Add Attachment" could also be removed completely, however, better done in another PR/discussion (it is needed only for the rare usecase where ppl write first - while Delta  Chat is praised for never forgetting attachments by forcing adding them first if one really writes first accidentally, one could fix that by copy+paste)
- ~~would be nice to have the "dangerous" items red, but that can be figured out in another PR (at least there is no obvious option)~~ EDIT: found an easy-enough solution
nb: this should also fix/mitigate the - hopefully rare - issue of …

cleanup menu

---

src/main/java/org/thoughtcrime/securesms/ProfileActivity.java

one can argue that 'unblock' is more or even less dangerous than 'block', however, the reason to leave it in 'red' is that it makes it easier to find the option again if the color does not change by state
successor of https://github.com/deltachat/deltachat-android/pull/3182

show '(un)block contact' in red as well

---

src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java
src/main/java/org/thoughtcrime/securesms/NewConversationActivity.java
src/main/java/org/thoughtcrime/securesms/ShareActivity.java
src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java
src/main/java/org/thoughtcrime/securesms/qr/QrCodeHandler.java
src/main/java/org/thoughtcrime/securesms/util/LongClickCopySpan.java
src/main/res/values/strings.xml

prevent creating contact without encryption in chatmail account

---

src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListFragment.java
src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListItem.java
src/main/res/menu/account_item_context.xml

this PR adds a "toggle mute" to the submenu added in https://github.com/deltachat/deltachat-android/pull/3191 (which needs to be merged before)

toggle mute from account switcher

---

src/main/java/com/b44t/messenger/DcChat.java
src/main/java/org/thoughtcrime/securesms/ConversationActivity.java

there are not really reasons to not allow sending videochat invitations to the self chat:
- it is useful for testing
- one may forward them from there to somewhere else
- it is allowed on desktop and ios as well
in fact, i was very confused that it is not possible when playing around with https://github.com/deltachat/deltachat-android/issues/3187 . might be a relict where we did _only_ allow videochat in normal one-to-one chats.

send a videochat invitation to self chat

---

src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListItem.java
src/main/java/org/thoughtcrime/securesms/reactions/ReactionRecipientItem.java
src/main/res/layout/reaction_recipient_item.xml

as at other places,
we should tune down showning email addresses
also in the primary reaction UI.
ppl will recognize name and avatar,
and if in doubt, you can always tap a reaction to go to the full profile.
this also makes the dialog easier to read, brings things to the point
and adds consistency to iOS, that never showed the address.

remove email address from primary reaction UI

---

src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListAdapter.java

as on other places,
hide chatmail email address from primary UI as well in the account switcher.
non-chatmail addresses will stay for now;
we are considering to add a "tag" or sth. like that for the user to differenciate between accounts if they're using same name+avatar.
this also makes the dialog more on-point and easier to read:
closes #3208

profile switcher: hide email for chatmail profiles

---

src/main/java/org/thoughtcrime/securesms/MediaPreviewActivity.java
src/main/res/menu/media_preview.xml

On enlarged images, delete is not a primary action many ppl want to go for, it is more intuitive in the menu.
this is also what other messengers are doing.
(this commit was extracted from https://github.com/deltachat/deltachat-android/pull/3212

delete is no primary action from enlarged images

---

jni/dc_wrapper.c
src/main/java/com/b44t/messenger/DcContact.java
src/main/java/org/thoughtcrime/securesms/ConversationTitleView.java
src/main/java/org/thoughtcrime/securesms/ProfileActivity.java
src/main/res/values/strings.xml

- in chat titles, show "Bot" instead of the email address of an empty line
- in profiles, show "Bot" instead of "Contact" in the corresponding tab
there are several ideas  for further iterations, but that seems to be a good start, that can also be done on other platforms very easily

mark bots in chat title and profile as such

---

src/main/java/org/thoughtcrime/securesms/BaseConversationListFragment.java
src/main/java/org/thoughtcrime/securesms/ContactSelectionListFragment.java
src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
src/main/java/org/thoughtcrime/securesms/MediaPreviewActivity.java
src/main/java/org/thoughtcrime/securesms/MessageSelectorFragment.java
src/main/java/org/thoughtcrime/securesms/ProfileActivity.java
src/main/java/org/thoughtcrime/securesms/ProfileSettingsFragment.java
src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListFragment.java
src/main/java/org/thoughtcrime/securesms/util/Util.java

this PR tints immediately destructive buttons with a red color. the idea is to make visually more clear that there is some irreversible action taking place; this is also what other apps are doing.
i was also thinking about subclassing `AlertDialog`, however, that would result in more complex code at the first glance 
the color is the same as for the menu entries, which works nicely in dark as well as light mode.
this PR is a replacement for https://github.com/deltachat/deltachat-android/pull/3212 and a successor of https://github.com/deltachat/deltachat-android/pull/3182 and https://github.com/deltachat/deltachat-android/pull/3183

tint destructive buttons in red

---

build.gradle
src/gplay/AndroidManifest.xml
src/main/AndroidManifest.xml

this PR increases sdk to 34 and adds foreground services as needed.
to be done:
- check our usage of intents (maybe someone else is in the mindset of explicit/implicit intents more than me :)
<details>
</details>
- there are also some warnings about forground-service-type declarations needed somewhere deep in androidx dependencies - not sure, if they are used during runtime. **upgrading androidx seem to require us to bump minSdkVersion from 16 to 21** or to add quite some exceptions as for emojipicker
<details>
</details>
- in general, someone else should read and check "Tools / Android SDK Upgrade Assistent" additionally, i do not get all the points, just started with some :) feel free to push to this PR directly
in general, we have 6 weeks left, so compared to other issues, this is not …

upgrade to api 34

---

src/main/java/com/b44t/messenger/DcContext.java
src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java
src/main/java/org/thoughtcrime/securesms/RegistrationActivity.java

this PR adds a device message for existing gmail-oauth2 users, telling them how to fix log in problems.
new gmail profiles won't be created using gmail-oauth2
closes #3233 
~~need to update the hints in the provider-db now~~ EDIT: done: https://github.com/deltachat/provider-db/pull/299

handle now unsupported oauth2

---

src/main/res/values/strings.xml

these strings are deprecated for a while and should be removed to remove burden from translators.
i additionally checked that these strings are unused using `./scripts/grep-string.sh`
the strings `systemmsg_read_receipt_subject` and `systemmsg_read_receipt_body` are still in use by desktop and stay deprecated until they're removed there as well, this should not block this pr

remove deprecated strings

---

CHANGELOG.md
build.gradle

this release contains required dependency and api updates, affecting potentially all aspects of the apps, resulting in everythings needs to be tested to avoid regressions :)
(this testrun is still in the 1.46 series as we may continue the series when this version is tested some time)

prepare 1.46.11 (testrun)

---

src/main/res/values-night/colors.xml
src/main/res/values/colors.xml
src/main/res/values/themes.xml

use same color as the app bar to give a more "modern" feeling to the app, other apps like Telegram, Signal, etc. use the same color for the app bar and status bar these days

tweak colors of the status bar

---

src/main/java/org/thoughtcrime/securesms/LogViewFragment.java

for performance and to avoid crashes with potential +250MB in logs when there are unexpected errors resulting in the same lines logging over and over several times per second
close #3194

limit number of lines to fetch from logcat

---

jni/dc_wrapper.c
src/main/java/com/b44t/messenger/DcContact.java
src/main/java/org/thoughtcrime/securesms/ProfileActivity.java
src/main/res/values/strings.xml

this PR improves the "Edit Name" dialog.
inspired by [this forum post](https://support.delta.chat/t/ux-for-setting-alias-name-for-contacts-is-not-obvious/3224) - indeed, there was just nothing. thanks a lot for the hints!
after some internal discussions, we went for placeholder+description. using radio buttons looks to complex for a comparable easy task, also in relation to comparable dialogs in-app and in other apps.
moreover, the PR uses the string "Edit Name" instead of "Edit" in the menu. i was thinking about renaming that even to "Nickname", however, that may be confusing on other levels,  we can always iterate.
finally, the dialog is no longer closed by one wrong tap, avoiding potential loss of typed names.
once this is merged, desktop and iOS can pick up these strings.
_before / …

improve nickname dialog

---

scripts/clean-core.sh

explicitly list the content to be deleted,
to have some more general protection in case sth. goes wrong accidentally ...

clean content of obj and build folders

---

jni/Application.mk

now the minimum SDK is 21, not 16

update APP_PLATFORM to android-21

---

jni/dc_wrapper.c
src/main/java/com/b44t/messenger/DcAccounts.java
src/main/java/org/thoughtcrime/securesms/RegistrationActivity.java
src/main/java/org/thoughtcrime/securesms/WelcomeActivity.java
src/main/java/org/thoughtcrime/securesms/connect/AccountManager.java
src/main/res/layout/registration_activity.xml

this PR removes options to create encrypted database. existing encrypted databases will continue working for now.
the 'encrypted database' experiment started some years ago was never finished and already stopped working partly, eg. importing backups as encrypted accounts stopped working some years ago for newer android.
in the light of Signal's "encryption key flaw",
but also recent issues with worsending core things in Delta Chat, it seems wise to concentrate on the core things ("you have one job!"), and not on side topics comparable few persons are interested in.
also, it will become harder to maintain that path on upcoming api changes, leaving the database open as opening is slow is needed but will become harder, this will make notifications tricy,
may need additional effort to run in …

stop 'encrypted database' experiment

---

src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java
src/main/res/layout/conversation_list_activity.xml

The hitbox for the account switcher was only the own avatar in and the title, so when you tapped a bit too low or too high, nothing happened.
This PR changes it to be the whole title bar.
The area where you can now tap to open the account switcher but you couldn't before:
(the slim area above and below the menu items on the very right is a bit unnecessary, but I don't know an easy way to avoid it. Before this PR, nothing happened when you tapped there, so I think it's fine)
Anyway, I find it quite a bit easier to open the account switcher now, just try it for yourself if you want :)

Increase account switcher hitbox

---

src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java

with #3262 now clicking in the self-avatar doesn't open the profile switcher

fix on-click in profile switcher button

---

src/main/AndroidManifest.xml
src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java
src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java
src/main/java/org/thoughtcrime/securesms/ProxySettingsActivity.java
src/main/java/org/thoughtcrime/securesms/RegistrationActivity.java
src/main/java/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
src/main/res/layout/proxy_settings_activity.xml
src/main/res/layout/registration_activity.xml
src/main/res/menu/instant_onboarding_menu.xml
src/main/res/menu/text_secure_normal.xml
src/main/res/values/strings.xml
src/main/res/xml/preferences_advanced.xml

Add separate view for proxy settings

---

src/main/java/org/thoughtcrime/securesms/mms/AttachmentManager.java

close #3288 
not sure this will solve the problem completely, there are other places where ScribbleActivity is launched: to crop an avatar, however, if for some reason the URI is null there, then there is another bigger problem there, I tried both ways and couldn't reproduce the problem

check that getSlideUri() is not null before passing it to ScribbleActivity

---

src/main/java/com/b44t/messenger/rpc/Rpc.java
src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListFragment.java
src/main/res/drawable/delete_account_item_background.xml
src/main/res/layout/contact_selection_list_item.xml
src/main/res/layout/dialog_delete_profile.xml
src/main/res/values-night/colors.xml
src/main/res/values/colors.xml

improve profile deletion dialog

---

src/main/java/org/thoughtcrime/securesms/notifications/RemoteReplyReceiver.java

when replying from within a notification,
the corresponding chat should be marked as being noticed as well.
otherwise, it looks wrong that one has replied to a chat, but still the chat is shown as being "unread".
the 'reply' from a notification should leave the chat in the same state as 'dismiss' resp. 'mark read' - plus the added message.

marked chat replied to as being noticed

---

src/main/res/values/strings.xml

- shorter, less cluttering
- we usually do not say 'Settings' inside 'Settings', also having several 'Settings' menu entries in the main menu us not so nice
- same as telegram is doing
once merged, this needs a `./scripts/tx-push-source.sh`

simplify 'Proxy Settings' to just 'Proxy'

---

src/main/java/org/thoughtcrime/securesms/notifications/MarkReadReceiver.java
src/main/java/org/thoughtcrime/securesms/notifications/NotificationCenter.java
src/main/java/org/thoughtcrime/securesms/notifications/RemoteReplyReceiver.java
src/main/res/values/strings.xml

'Dismiss' is a bit unclear - even though introduced at #2083 to make things clearer, i do not think this has happened :) -
i also needed to dive into the source code to see what exactly 'Dismiss' is doing.
meanwhile, we're anyway using 'Mark Read' to remove unread counter from chats, and this is basically the same. good to be consistent. finally, this is also the term WhatsApp/Telegram are using.
closes https://support.delta.chat/t/what-does-dismiss-button-on-notifications-do/3261/3
nb: we also change the english 'short' term from 'Read' to 'Mark Read' - this is sill shorter than many translations
and removes the ambiguousness 'Mark Read' vs 'Open for Reading" - esp. in the notification without much context, this is better, but also on iOS, where the term was introduced for, it is good to …

'Mark Read' instead 'Dismiss' notifications

---

src/main/java/org/thoughtcrime/securesms/LogViewFragment.java

saying post-notifications-granted=false on API that do not need this grant is misleading as it looks as some error or if the user has rejected sth.
just stumbled upon that and was irritated when trying out things wrt https://github.com/deltachat/deltachat-android/issues/3281 on android7

refine post-notifications-granted logging

---

src/gplay/java/org/thoughtcrime/securesms/notifications/FcmReceiveService.java

See https://firebase.google.com/docs/cloud-messaging/android/receive#override-ondeletedmessages
Shouldn't happen very often, but if it does, it's good to connect, too.
Follow-up for https://github.com/deltachat/deltachat-android/issues/3281

Also start the FetchForegroundService in onDeletedMessages()

---

src/main/java/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java

this PR makes the help - that describes key format, supported keys etc. - accessible directly from the "manage keys" section.
before, these information were harder to find.
the learn more buttons links to https://delta.chat/en/help#can-i-reuse-my-existing-private-key in the offline help (which is shipped with the app, no internet required)
came over this by the desktop issue  https://github.com/deltachat/deltachat-desktop/issues/4155

add 'learn more' button for managing keys

---

jni/dc_wrapper.c
src/main/java/com/b44t/messenger/DcContext.java

https://github.com/deltachat/deltachat-core-rust/pull/6016/ removed this function. We didn't use it, but it was still present in the bindings.

Remove getNextMedia() to make compilation succeed again

---

src/main/java/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java

With https://github.com/deltachat/deltachat-core-rust/pull/6027, when exporting a backup, the counter stays at 0% while running housekeeping and vacuuming the database, which takes 10 seconds on my device. (note that before https://github.com/deltachat/deltachat-core-rust/pull/6027, the progress stayed at 1% while exporting the database, which can take multiple minutes, so the core PR is definitely an improvement already)
Showing "One moment... 0%" for 10 seconds (or longer on slower devices / with bigger accounts) might make users think that it's not working and abort the process. So, instead, simply show "One moment..." until the progress reaches 1%.

Don't show "0%" at the beginning when exporting/importing backups

---

src/main/java/org/thoughtcrime/securesms/components/SearchToolbar.java
src/main/res/menu/conversation_list_search.xml
src/main/res/values/strings.xml

this PR adds a menu item beside the search field that easily allows to filter the chatlist by showing only unread chats.
https://github.com/user-attachments/assets/5b1dcd9b-f64c-4037-bb64-e38b5a9f9e42
the functionality itself was added to the core [a while ago](https://github.com/deltachat/deltachat-core-rust/pull/4824) already; the menu entry only adds the string `is:unread` to the search field, if not already present 
(this is probably good enough; the item is more a hint, for what can be entered. i was also thinking about a toggle, however, this adds complexity, and probably no one would expect to remove the string that way; the search is ended easily using "back" or "clear")
we were also thinking about adding this to the main menu, however, that would clutter UI with more advanced …

add shortcut for `is:unread`

---

src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListFragment.java

this is needed to show 'Delta Chat' in case only one profile is left
i think, this is simple enough to go for closing #3342 accordingly

update chatlist title on profile deletion

---

src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListItem.java

do not show 'Add Profile' in bold.
this looks less cluttered
and makes the "bold" of the selected account more outstanding:
before, there were two types of "boldness",
the add profile button (using bold only)
and the selected profile (using bold and a background), this results in a bit cluttered, unsteady look,
esp. when there are few accounts and more bold than normal is shown.
also, this makes "bold" more outstanding,
as this attribute is given to one line only.
there is no need for the "add profile" to be that outstanding (in contrast to eg. the "add chat" dialog)
("Add Profile" is clearly less often used that an temporarily unselected profile and should stand back also from that point of view)
the "Add Profile" button with its "+" is still recognisable enough and is not really mixed …

cleanup account switcher

---

src/main/java/org/thoughtcrime/securesms/BaseConversationListFragment.java
src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
src/main/java/org/thoughtcrime/securesms/util/SendRelayedMessageUtil.java
src/main/res/values/strings.xml

this PR adapts the warning messages when multiple files are attached (via "Share To Delta Chat") to what actually happens.
it is on purpose, that things are recoded by default, esp. when sharing-one-image recodes, sharing-multiple-images should recode as well - and this is what happens since quite some years :)
for videos, however, recoding is not done in that flow; this is the only thing left to warn about (changing the flow is out of scope and would be a feature request)

fix the warning when attaching multiple files

---

src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListFragment.java

having 'add profile' at the end of the list is more natural, and more consisten with desktop/iOS -
as well as internally, eg. proxy also has 'add' at its end.
also, this paves the way to have a consistent layout when it comes to profile-switching from forward/share dialogs,
where one probably does not want to have a 'add' button (so, the first lines are not different :)
the profile list is usually not super-large,
and even if - when ppl have managed to add 10+ profiles, they'll know how to do this, even with scrolling :) also, adding is a rare function, in contrast to switching, so even then it makes sense as there is room for one more item without scrolling.
in contrast,
for 'create chat' we show 'add' at the beginning,
as these lists can contain several hundreds of entries _and_ add is …

move 'add profile' to end of list

---

src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
src/main/java/org/thoughtcrime/securesms/mms/AttachmentManager.java
src/main/java/org/thoughtcrime/securesms/providers/PersistentBlobProvider.java
src/main/java/org/thoughtcrime/securesms/util/SendRelayedMessageUtil.java
src/main/res/values/strings.xml

this PR allows to select and send multiple images directly from within the app's gallery.
after confirmation, the images are send as separated messages then - similar to images selected from the system gallery.
sending single images is done as usual and unchanged.
this should make the usecase of "sharing quite some holiday images" much easier - even though more advanced things as per-image comment or mini-galleries are not there, let alone sending the images in a single mail. all that would be _much_ more effort and is out of scope currently
https://github.com/user-attachments/assets/874e237e-1cdf-41ff-aec2-db0800a82cc2

attach multiple images

---

src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java
src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java
src/main/res/drawable/baseline_proxy_24.xml
src/main/res/drawable/ic_proxy_disabled_24.xml
src/main/res/drawable/ic_proxy_enabled_24.xml
src/main/res/menu/instant_onboarding_menu.xml
src/main/res/menu/text_secure_normal.xml

the icon is also shown in the onboarding screen to remind the user that they have the proxy enabled to help troubleshooting
I think the icons could probably be replaced at some point but this is the best I could find and it is pretty similar to the one used by Telegram, in some way you are protecting the connection against blocking etc. and if you are using shadowsocks it is even encrypted
close #3364

reflect status of the proxy (enable/disabled) in the proxy icon

---

src/main/java/org/thoughtcrime/securesms/qr/QrCodeHandler.java

this was forgotten by the move to BACKUP2 in #3173
targets #3369, however, indeed "paste" should be added to "add second device scanner" as well

support BACKUP2 in chatlist-qr-code scanner, 

---

src/main/java/org/thoughtcrime/securesms/qr/QrActivity.java
src/main/java/org/thoughtcrime/securesms/qr/QrShowActivity.java
src/main/java/org/thoughtcrime/securesms/qr/QrShowFragment.java
src/main/res/drawable/ic_link_24.xml
src/main/res/drawable/ic_qr_code_scanner_24.xml
src/main/res/layout/dialog_share_invite_link.xml
src/main/res/layout/qr_show_fragment.xml
src/main/res/menu/qr_show.xml
src/main/res/values/strings.xml

improve "show QR" screen

---

src/main/java/com/b44t/messenger/DcContext.java
src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListFragment.java
src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListItem.java
src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java
src/main/res/layout/account_selection_list_item.xml
src/main/res/menu/account_item_context.xml
src/main/res/values/strings.xml

see https://support.delta.chat/t/chat-folders-to-collect-chats-by-context/2201

allow to set tags on profiles

---

src/main/java/org/thoughtcrime/securesms/service/FetchForegroundService.java

the foreground service was introduced unconditionally in #3312, however turns out to be annoying and flickering
if the app is actually in foreground.
the service _might_ be needed in this case only
if the app is about going to background during fetch, but in this case, we assume,
that we have some 10 seconds time still.
@Hocuri iirc, you wanted to double check that :)
in any case,
this is still an improvement to the released apps, that _never_ show a foreground service.
(for the naming, it could also be maybeStart() or so, but this was also the case before as it checks if already started, so i do not mind. moving the check outside will add code, and makes tweaking harder. also, as the service will potentially be used also from other places, eg. when it comes to huawei, so i'd be pragmatic …

do not start foreground service in foreground

---

src/main/java/org/thoughtcrime/securesms/notifications/NotificationCenter.java

close #3378 
before - quite some noise in the notification:
after - on a default installation with one account we do not need to show anything:
after - using multiple accounts and label set (if not label is set, the displayname is used):

Use tag or display name for notifications instead address

---

CHANGELOG.md

from the view of the user, this is just the 'file name'. calling it 'original file name' there is maybe correct internally, as we add a random number for $reasons.
however, some users were alarmed about what the heck is transferred here.

'message info' just shows the file name

---

src/main/java/org/thoughtcrime/securesms/connect/DcEventCenter.java

That "global"(accid=0) account manager events where never logged at all was a bug
This PR also log other accounts' events if the developer mode is enabled, his can be useful to debug multi-account problems like backgroundFetch()

improve logging: always log events for accId=0

---

src/main/java/org/thoughtcrime/securesms/RegistrationActivity.java
src/main/res/layout/registration_activity.xml
src/main/res/values/arrays.xml

fix #3408 by automatically changing a 3 to 2.
3 is a [deprecated alias for 2](https://github.com/deltachat/deltachat-core-rust/blob/37ca9d7319dabcf1cd3cf0bb75c2b4c062aa3bf0/src/login_param.rs#L18-L41), so all UIs now need to handle both values. I think it wasn't a good idea to deprecate 3 in the first place, but it's not worth it going back now.
I tested this PR like this:
- Without this PR:
- Set certificate checks to "Accept invalid Certificates" in the settings -> `imap_certificate_checks` is 2
- Import a backup from Desktop with "Accept invalid Certificates"
- Open "Password and Account" in the settings -> the app crashes
- With this PR:
- Open "Password and Account" in the settings -> the app doesn't crash anymore
- -> `imap_certificate_checks` is 3
- Save the settings
-  -> …

fix: Accept the deprecated 3 as an alias for 2

---

src/main/java/org/thoughtcrime/securesms/qr/BackupReceiverFragment.java

Mitigation for https://github.com/deltachat/deltachat-android/issues/3392, follow-up for https://github.com/deltachat/deltachat-android/pull/3337.
When creating a chatmail account, when logging in to an existing email account, and when importing a backup from the Welcome Activity, we're still showing "0%" even after this PR. So, an alternative to this PR would be to make `percent > 0 ? String.format(Util.getLocale(), " %d%%", percent) : "";` into a function and call it from all these places, too, and never show "0%" anywhere ever again.

Don't show "0%" at the beginning when being added as second device

---

src/main/res/xml/preferences_chats.xml

A backup contains more than just the chats, and it's not true that the backup will be exported to "external storage". (the backup will be exported to the Downloads folder, which may well be on the internal storage rather than the SD card).
Old/New:

Rename "Back up Chats to External Storage" to "Export Backup"

---

src/main/java/org/thoughtcrime/securesms/RegistrationActivity.java
src/main/java/org/thoughtcrime/securesms/util/ViewUtil.java

_can be merged to #3410 or later to main_
Spinner is very picky about bad selections,
this is an accident waiting to happen -
eg. if new values are introduced
or someone thinks, the "deprecated" case can be removed.
better do not trust incoming data.
nb: first i did a "clip to bounds", so that larger values get the "maximum", however, although anything is better than _always_ crashing,  i think it is better to for for "default" in this case. however, this requires the "deprecated" check introduced by #3410 for the next time at least (iOS and desktop always write a `3`, probably also DeltaTouch)

check spinner bounds

---

src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListFragment.java

calculation may take a moment,
do this in background.
it is totally fine to just display nothing before, that avoids flickering (WHAT was this? i cannot look so fast!) - and in most cases, it is close to instant.
closes #3308

calculate account size in background

---

src/main/java/org/thoughtcrime/securesms/components/emoji/AutoScaledEmojiTextView.java

Not sure why, but `setText()` seems to be called with an empty string very often - for this case it's nice if getTextScale() returns early.
If the text starts with a letter, we can also return early.

perf: Return early in getTextScale() if text is empty or starts with a letter

---

src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java

fix https://github.com/deltachat/deltachat-android/issues/3433
The problem was that in line 114, rollbackAccountCreation() is called so that the previously selected profile is selected again. Then, afterwards, in onPause() the display name (and avatar, if it was changed) of this profile is changed.
I tested both #3433 and #3063 are fixed after this PR.

fix: Don't change display name when starting to create a new account and going back

---

src/main/java/org/thoughtcrime/securesms/qr/QrCodeHandler.java

see discussion at https://support.delta.chat/t/in-the-new-android-client-it-is-not-possible-to-click-to-open-urls-with-port-numbers/3327

allow to open in browser http links that look like proxies

---

src/main/java/com/b44t/messenger/DcContext.java
src/main/java/org/thoughtcrime/securesms/connect/DcEventCenter.java
src/main/java/org/thoughtcrime/securesms/notifications/NotificationCenter.java

this PR shows notifications for reactions to one's own messages.
the notifications are added unconditionally, assuming, this is also known from other messengers. also, only reaction to _own_ messages are notified  - compared to that otherwise _all_ messages of others are notified, this usually won't add much  - either one cares or not (and in the latter case, you have muted the chat). we can always iterate :)
for the "mark read": there is nothing to mark as read for reactions, however, i still think, it makes sense to keep the button as it marks the chat as noticed - and it is maybe more confusion if it is sometimes not there.
counterpart of https://github.com/deltachat/deltachat-ios/pull/2331

notify reactions added

---

jni/dc_wrapper.c
src/main/java/com/b44t/messenger/DcMsg.java
src/main/java/org/thoughtcrime/securesms/ConversationFragment.java
src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
src/main/res/raw/webxdc_wrapper.html

allow to open deep-link to webxdc

---

src/main/java/org/thoughtcrime/securesms/notifications/NotificationCenter.java

When someone sends you 4 messages "1", "2", "3", "4" (in this order), this now looks like this (unexpanded/expanded):
Before, the unexpanded notification looked the same, the expanded notification had the other direction.
This PR here makes DC show the same behavior as Signal and WhatsApp.

Reverse order of the tiny inbox in notifications

---

src/main/java/com/b44t/messenger/DcMsg.java
src/main/java/org/thoughtcrime/securesms/ConversationFragment.java
src/main/java/org/thoughtcrime/securesms/ConversationItem.java
src/main/java/org/thoughtcrime/securesms/components/QuoteView.java
src/main/java/org/thoughtcrime/securesms/notifications/NotificationCenter.java

When we introduced this, I assume that we weren't sure whether we should do it and only showed it in some places. But I think it's nicer to show the same sender name everywhere, i.e. always add the "~".
Before this PR, the "~" was _not_ shown:
- in quotes
- when copying messages of multiple senders at once (when copying just one message / messages of just one sender, the sender is not included in the copied text, anyway)
- In the "Forwarded by..." text of a forwarded message
- in notifications
Context: When the sender of a message is not part of the chat (in mailing lists or because they were sending from an alias), the name is prepended with a "~".
This PR needs to be merged after #3441.

Always show the "~" before the sender name if it's overridden

---

jni/dc_wrapper.c
src/main/java/com/b44t/messenger/DcContext.java
src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
src/main/res/raw/webxdc.js

the 'description' parameter is about to be deprecated, see https://github.com/deltachat/deltachat-core-rust/issues/6245

remove 'description' parameter from webxdc's sendUpdate()

---

src/main/java/com/b44t/messenger/DcMsg.java
src/main/java/org/thoughtcrime/securesms/ConversationFragment.java
src/main/java/org/thoughtcrime/securesms/ConversationItem.java
src/main/java/org/thoughtcrime/securesms/components/QuoteView.java
src/main/java/org/thoughtcrime/securesms/notifications/NotificationCenter.java

In 1:1 chats, don't prepend the sender name to every line. The exception is when the display name is not equal to the chat name (i.e. there is an OverwriteSenderDisplayname), in this case we still prepend it.
This is how it looks when Bob2 sends 4 messages, and then I get 1 message from Hocuri4 that is assigned to the same chat:

Don't always show the sender in notifications

---

src/main/java/org/thoughtcrime/securesms/notifications/RemoteReplyReceiver.java

this PR lets  the actions "Reply" and "Mark Read" refer to the chat, not to the message.
this fixes reaction/webxdc notifications as well as unclear grouping of android (android shows the messages combined, so it is unclear what "Reply" would quote). 
this is also what eg. signal is doing.
in a subsequent PR, we can go for adding a "Start" button that opens the webxdc-app directly

reply/mark-read actions refer to chat, not to message

---

src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java

now even if internet access is enabled, the index.html is wrapped in an iframe

fix WebxdcActivity.callJavaScriptFunction()

---

src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
src/main/res/raw/webxdc_wrapper.html

always prefix href with baseURL to avoid working accidentally if developer pass full URL which will work locally but will not work in other devices / platforms

always prefix href with baseURL

---

src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java

the issue is that unset `EXTRA_HREF` is passed around as an empty string, however `Bundle.getString(href, "index.html")` returns `index.html` only when `href` is `NULL`, which is mostly never the case.
this results in webxdc never started with index.html, and then not started at all

fix starting of webxdc

---

src/main/java/com/b44t/messenger/DcContext.java
src/main/java/org/thoughtcrime/securesms/notifications/NotificationCenter.java
src/main/java/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java
src/main/res/values/strings.xml
src/main/res/xml/preferences_notifications.xml

even if group is muted:
* notify quote-reply to own messages
* notify reactions to own messages
* notify webxdc notifications
what is still unsolved:
if webxdc sends notification while the chat is open, there is no notification, if there is no info message there is no hint that there was a notification at all, and if there is info message that doesn't warranties that the notification was the same

notify webxdc events, replies and reactions to own messages even if chat is muted

---

src/main/java/org/thoughtcrime/securesms/components/AttachmentTypeSelector.java
src/main/res/layout/attachment_type_selector.xml

this PR centers the icons in the attachment selector, the right-aligned ones looks esp. odd when no experiments are enabled.
the default now looks good,
and when all experiments are enabled, things are perfect as well. but even if only one experiment is enabled, things are better imo (but we anyway should optimize for default and not for experimental options):
i know there are disucssions about changing that at all, but this PR is an easy fix i could not resist :)
@adbenitez i like the new app-icon, btw 👌

center attachment icons

---

jni/dc_wrapper.c
src/main/java/com/b44t/messenger/DcContext.java
src/main/java/com/b44t/messenger/DcMsg.java
src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
src/main/java/org/thoughtcrime/securesms/video/recode/VideoRecoder.java

This PR removes prepareMsg, which put messages into the OUT_PREPARING state and was used while videos were recoded:
- It was buggy because when you forwarded a message while it was InPreparation, or when the app was killed while a message is InPreparation, the message would stay InPreparation forever.
- Android is the only UI using this InPreparation (according to @r10s, I didn't check this myself), so we can simplify some things in core, which will also make it easier to deduplicate blob files.

Remove prepareMsg (and OUT_PREPARING message state)

---

src/main/java/org/thoughtcrime/securesms/ConversationActivity.java

The activity may be  finishing/destroyed by the time the async task finishes and tries to dismiss the progress dialog, so just avoid calling `progressDialog.dismiss()` if activity is finishing/destroyed
close #3498

avoid IllegalArgumentException dismissing dialog

---

src/main/java/org/thoughtcrime/securesms/ConversationTitleView.java

it is regarded as a bug
and esp. weird in translations.
it was regarded to be a bit 'nerdy' that time to write it lowercase, but it seems we have to get more serious now.
via https://support.delta.chat/t/two-typos-in-dc/3396 , but tbh, i was also stumbling upon that more than once. better use correct casing, don't make me think.

do not lowercase string 'Bot'

---

src/main/java/org/thoughtcrime/securesms/service/FetchForegroundService.java

fix: Fetch synchronously in the background if no foreground service is allowed

---

src/main/java/org/thoughtcrime/securesms/ConversationFragment.java

Mark messages as seen in a background thread instead of on the UI thread in order to fix #3504.

fix(ANR): Mark messages as seen asynchronously

---

src/main/java/org/thoughtcrime/securesms/ConversationTitleView.java

_this was discussed in-person with various ppl  on the last physical gathering :)_
the email-address was removed for guaranteed-e2ee chats quite a while ago (https://github.com/deltachat/deltachat-android/pull/2916) reason was, among others, that these addresses are often chatmail and therefore random. (despite expecting otherwise, that was fine for most users).
this PR removes the email-adress unconditionally:
- having the email-address sometimes shown and sometimes not is confusing, and easily looks like a bug. this has become worse with the added vcard-support (before, there were rare non-guaranteed chats in chatmail) - resulting in more random addresses being shown
- _always_ protect against over-the-shoulder attacks
- better privacy in screenshots sent around without thinking much …

remove email-address unconditionally from title

---

src/main/java/org/thoughtcrime/securesms/reactions/AddReactionView.java
src/main/java/org/thoughtcrime/securesms/reactions/ReactionsDetailsFragment.java

when there is no reactions yet for a message `Rpc.getMsgReactions` returns `null`, checking for this explicitly instead of putting noise in the logs with stack traces

avoid NullPointerException when using result of Rpc.getMsgReactions

---

src/main/res/layout/webxdc_view.xml

Everytime I attached an image, I got a super long stacktrace in the logcat. I found it to be [this problem](https://stackoverflow.com/questions/71746801/getting-failed-to-inflate-colorstatelist-leaving-it-to-the-framework-when-usi) and applied the fix described there.

fix: Remove long stacktrace that flooded the logcat

---

.github/workflows/preview-apk.yml
src/main/java/org/thoughtcrime/securesms/service/FetchForegroundService.java

use synchronized block to avoid IllegalMonitorStateException

---

scripts/upload-beta.sh

as Android releases are atm done more frequently by @adbenitez (thaaaaanks for that!), it does not make sense to point to iOS, which may be totally async. 
instead, on iOS releasing, and additional message could be added to the chats (which, however, is less important as testflight user get informed automatically)

detach Android and iOS releases

---

src/androidTest/java/com/b44t/messenger/uitests/offline/SharingTest.java
src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
src/main/java/org/thoughtcrime/securesms/MediaPreviewActivity.java
src/main/java/org/thoughtcrime/securesms/components/MediaView.java
src/main/java/org/thoughtcrime/securesms/connect/AttachmentsContentProvider.java
src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java
src/main/java/org/thoughtcrime/securesms/mms/AttachmentManager.java
src/main/java/org/thoughtcrime/securesms/mms/GifSlide.java
src/main/java/org/thoughtcrime/securesms/mms/ImageSlide.java
src/main/java/org/thoughtcrime/securesms/mms/VideoSlide.java

In preparation for https://github.com/deltachat/deltachat-core-rust/pull/6332, use the original name of the file (as returned by getFilename()) instead of the current filename on disk.
Most of the commits are cherry-picked from #3513.
What I did:
- Grep for usages of DcMsg.getFile(), check where it's passed, and make sure that all it's never used to check the file extension, to pass it to an external application, or to show it to the user.
- Look at places in the code where a filename is user-visible, like when viewing it in the UI or passing it to an external application (especially when sharing or opening it). Check where the filename comes from, and make sure that it comes from getFilename(), not from getName().
- Test that 
1. sharing to and from DC
2. opening
3. saving ("Export …

fix: Use getFilename() instead of the actual filename on disk

---

src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java
src/main/java/org/thoughtcrime/securesms/RegistrationActivity.java
src/main/java/org/thoughtcrime/securesms/WebViewActivity.java
src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
src/main/java/org/thoughtcrime/securesms/WebxdcStoreActivity.java
src/main/java/org/thoughtcrime/securesms/qr/QrCodeHandler.java
src/main/java/org/thoughtcrime/securesms/util/IntentUtils.java
src/main/java/org/thoughtcrime/securesms/util/LongClickCopySpan.java
src/main/java/org/thoughtcrime/securesms/videochat/VideochatUtil.java

fix IntentUtils.showBrowserIntent(), rename to `showInBrowser` and use it everywhere instead of having duplicate code 
close #3534

fix IntentUtils.showBrowserIntent() and use it everywhere

---

src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
src/main/java/org/thoughtcrime/securesms/audio/AudioRecorder.java
src/main/java/org/thoughtcrime/securesms/providers/PersistentBlobProvider.java

avoid null in attachment filename

---

src/main/java/org/thoughtcrime/securesms/LocalHelpActivity.java
src/main/res/menu/local_help.xml
src/main/res/values/strings.xml

this PR tweaks the menu atop of the offline help a bit:
- use clear "Delta Chat Homepage" for opening our homepage (instead of unclear "Learn more about Delta Chat", which is esp. weird, when used from inside the help)
- do not "promote" GitHub in our menu entry, instead of "Contribute on GitHub", just say "Contribute". destination URL is our contribute page then - that is also more useful for ppl doing eg. translations
came over that when using more modern help menu on ios as a finger exercise at https://github.com/deltachat/deltachat-ios/pull/2545/files :)
this is how it looks like with this PR:

streamline help menu

---

jni/dc_wrapper.c
src/main/java/com/b44t/messenger/DcMsg.java
src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
src/main/java/org/thoughtcrime/securesms/attachments/Attachment.java
src/main/java/org/thoughtcrime/securesms/components/MediaView.java
src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java
src/main/java/org/thoughtcrime/securesms/mms/AttachmentManager.java
src/main/java/org/thoughtcrime/securesms/util/SendRelayedMessageUtil.java
src/main/java/org/thoughtcrime/securesms/video/recode/VideoRecoder.java

Depends on https://github.com/deltachat/deltachat-core-rust/pull/6332.
Remaining bugs:
- ~~When sharing an image to DC (or when drafting and re-entering a chat), the dimensions aren't calculated correctly~~ Fixed thanks to adb
- ~~When sharing a video to DC (or when drafting and re-entering a chat) and then clicking on the draft to preview it, I only get a black screen~~ Works fine with https://github.com/deltachat/deltachat-core-rust/pull/6463

File deduplication, Android part

---

src/main/java/org/thoughtcrime/securesms/qr/QrActivity.java
src/main/java/org/thoughtcrime/securesms/qr/QrCodeHandler.java
src/main/java/org/thoughtcrime/securesms/qr/QrShowActivity.java
src/main/java/org/thoughtcrime/securesms/qr/QrShowFragment.java
src/main/java/org/thoughtcrime/securesms/util/Util.java
src/main/res/values/strings.xml

this PR streamlines resetting QR codes, mitigating lots of confusion we encountered on testing.
- use "reset", as known from other messengers - and which is also more accurate as a new QR code will be created immediately as needed
- simpler "activate" wording, tbh, i am not sure if that is even a thing that will ppl do
- incorporate "invite link" wording, at least partly 
to make adaption easier, it does not split strings for so (eg. use different strings for scanning and button), so other OS will benefit without doing additional things.
moreover, the PR adapts the layout, uses colors and uses "reset" only as primary button when selected via menu entry. this is how it looks like.
the weird primary button was also often cause of confusion.

refine QR reset wording

---

src/main/java/org/thoughtcrime/securesms/ProfileDocumentsFragment.java
src/main/res/values/strings.xml

before, if there were no "apps" or "files", the hint was a bit off, saying "Media shared in any chat will appear here.". now it looks like the following:
for the other tabs, "media" is fitting enough for now :)

tweak wording in empty "all apps" and "all files" views

---

src/main/res/values/strings.xml

this PR is about  to improve the wording of the dialog shown when a contact is blocked, aligning that more with the status quo
ftr, as @adbenitez just reconfirmed, telegram also shows messages of blocked contacts in groups, i think, idea is to make discussions possible - otherwise there are lots of "i did not read the message" from various ppl. if the issue with a user is that serious, one should leave shared groups

be more clear about the impact of blocked contacts

---

src/androidTest/java/com/b44t/messenger/uitests/offline/SharingTest.java
src/main/java/org/thoughtcrime/securesms/connect/AttachmentsContentProvider.java
src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java

The problem was that we returned `null` from `getType()`.
fix #3517

fix: Opening files in external apps always works now

---

src/main/java/org/thoughtcrime/securesms/ProfileActivity.java

before, 'clone chat' was hidden for contacts having a one-to-one-chats, but not for contacts _without_ a one-to-one-chat
opening a contact's profile for contacts without a chat, is not so unusual when eg. tapping the avatar of unknown members in a group
good news is that there was no crash or so, only an empty group was created :)

fix: hide 'clone chat' if there is no chat

---

build.gradle
src/main/java/org/thoughtcrime/securesms/glide/webp/WebpDrawableTranscoder.java
src/main/java/org/thoughtcrime/securesms/glide/webp/WebpLoader.java
src/main/java/org/thoughtcrime/securesms/mms/SignalGlideModule.java

instead of using a glide plugin that messes also with GIF, APNG and AVIF, create a small glide plugin on-point only for awebp (animated webp)
the more complex glide plugin is causing problems with big PNG not being displayed, already got reports from users and also is happening for me all the time when attaching certain big resolution images taken with camera (in the staged preview a transparent image is shown, when sending gets fixed by re-sizing of core, but can happen if image is sent unmodified via File attachment button)
close #2957

direcly use awebp lib instead of broad glide plugin

---

src/main/java/org/thoughtcrime/securesms/BaseConversationListFragment.java
src/main/java/org/thoughtcrime/securesms/connect/DirectShareUtil.java
src/main/res/menu/conversation_list.xml

currently we already allow to add some chats to the home screen, but in a limited way, with the launchers that support some "quick actions" when long-pressing app icon and it only displays the 3 more resent chats + the "Saved Messages" chat, with this PR people can add to home screen any chat without the mentioned limitations:

allow to add any chat to the home screen

---

gradle.properties
src/main/java/org/thoughtcrime/securesms/BaseConversationListFragment.java
src/main/java/org/thoughtcrime/securesms/ContactMultiSelectionActivity.java
src/main/java/org/thoughtcrime/securesms/ContactSelectionListFragment.java
src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
src/main/java/org/thoughtcrime/securesms/ConversationFragment.java
src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java
src/main/java/org/thoughtcrime/securesms/ConversationListArchiveActivity.java
src/main/java/org/thoughtcrime/securesms/CreateProfileActivity.java
src/main/java/org/thoughtcrime/securesms/FullMsgActivity.java
src/main/java/org/thoughtcrime/securesms/GroupCreateActivity.java
src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java
src/main/java/org/thoughtcrime/securesms/LocalHelpActivity.java
src/main/java/org/thoughtcrime/securesms/LogViewActivity.java
src/main/java/org/thoughtcrime/securesms/MediaPreviewActivity.java
src/main/java/org/thoughtcrime/securesms/ProfileActivity.java
src/main/java/org/thoughtcrime/securesms/ProfileDocumentsFragment.java
src/main/java/org/thoughtcrime/securesms/ProfileGalleryFragment.java
src/main/java/org/thoughtcrime/securesms/ProfileSettingsFragment.java
src/main/java/org/thoughtcrime/securesms/WebViewActivity.java
src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListFragment.java
src/main/java/org/thoughtcrime/securesms/contacts/NewContactActivity.java
src/main/java/org/thoughtcrime/securesms/qr/BackupProviderFragment.java
src/main/java/org/thoughtcrime/securesms/qr/BackupTransferActivity.java
src/main/java/org/thoughtcrime/securesms/qr/QrActivity.java
src/main/java/org/thoughtcrime/securesms/qr/QrShowActivity.java
src/main/java/org/thoughtcrime/securesms/qr/RegistrationQrActivity.java

according to Google they moved to dynamic IDs because it makes it faster to compile, etc.
the `switch` statements got converted to `if` automatically by AndroidStudio

fix warning about non-final resource IDs

---

jni/dc_wrapper.c
src/main/java/com/b44t/messenger/DcContext.java
src/main/java/com/b44t/messenger/DcMsg.java
src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
src/main/java/org/thoughtcrime/securesms/ConversationFragment.java
src/main/java/org/thoughtcrime/securesms/ConversationItem.java
src/main/java/org/thoughtcrime/securesms/components/ConversationItemFooter.java
src/main/java/org/thoughtcrime/securesms/components/InputPanel.java
src/main/java/org/thoughtcrime/securesms/components/QuoteView.java
src/main/java/org/thoughtcrime/securesms/util/views/ConversationAdaptiveActionsToolbar.java
src/main/res/layout/conversation_item_footer.xml
src/main/res/menu/conversation.xml
src/main/res/menu/conversation_context.xml
src/main/res/values/strings.xml

allow to edit message

---

src/main/java/com/b44t/messenger/DcContext.java
src/main/java/org/thoughtcrime/securesms/WelcomeActivity.java
src/main/java/org/thoughtcrime/securesms/qr/QrCodeHandler.java
src/main/res/values/strings.xml

this PR shows a warning if the user scans a backup QR code from a too new Delta Chat version.
the user has to update their device first.

add a warning when scanning a too new backup QR code

---

src/main/res/values/strings.xml

when a core with https://github.com/deltachat/deltachat-core-rust/pull/5007 is used, chats will be deleted across devices; then we should merge this PR to clarify the impact

clarify chat deletion impact

---

src/main/java/com/b44t/messenger/DcContext.java
src/main/java/org/thoughtcrime/securesms/ConversationListFragment.java

this needs new core with `DC_EVENT_CHAT_DELETED` to actually work as expected

remove notifications from chat that was deleted from other device

---

.github/mergeable.yml

this PR checks if `CHANGELOG.md` is updated in case any `.java` file is modified. the condition can probably be more advanced, but in practise, the extension check went very well for iOS
inspiration taken from https://github.com/deltachat/deltachat-ios/pull/2515, https://github.com/deltachat/deltachat-core-rust/pull/2999 and https://github.com/deltachat/deltachat-desktop/pull/4357
documentation: https://mergeable.readthedocs.io/en/latest/configuration.html
"mergeable" needs to be added/enabled at https://github.com/deltachat/deltachat-android/settings/installations EDIT: i added it there

check for CHANGELOG in PRs changing .java files

---

CHANGELOG.md
src/main/java/org/thoughtcrime/securesms/MediaPreviewActivity.java
src/main/java/org/thoughtcrime/securesms/MessageSelectorFragment.java
src/main/res/values/strings.xml

do not say "Delete on all your devices"
when deleting a message in the "Device Messages" chat.
while this is a minor,
it is one of the first things the user may see,
better be correct there to not give a false first impression of correctness :)

no 'delete on all devices' for device messages

---

README.md

add instructions about decoding symbols in core crash

---

CHANGELOG.md
src/main/java/com/b44t/messenger/DcMsg.java
src/main/java/org/thoughtcrime/securesms/ConversationAdapter.java
src/main/java/org/thoughtcrime/securesms/ConversationFragment.java
src/main/java/org/thoughtcrime/securesms/ConversationItem.java
src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java
src/main/java/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
src/main/res/values/strings.xml
src/main/res/xml/preferences_advanced.xml

close #3591, similar to https://github.com/deltachat/deltachat-ios/pull/2636
- Remove "Prefer end-to-end encryption"
- Remove option to import key by file or autocrypt setup message (ASM), targets targets https://github.com/deltachat/interface/issues/80
- Remove option to export key file, which doesn't really make sense on mobile because it was exporting the key file without any passphrase to the world-readable Downloads folder
- Remove receiving ASM
- Deprecate unused strings
Sending ASM stays for now.

hide some option in Encryption category

---

src/main/java/org/thoughtcrime/securesms/qr/BackupProviderFragment.java
src/main/res/layout/activity_registration_2nd_device_qr.xml
src/main/res/layout/backup_provider_fragment.xml
src/main/res/values/strings.xml

add-second-device is arguably no longer experimental, we're pointing to that options officially and often.
#skip-changelog as rewordings usually do not make it to the changelog

remove 'experimental, 1.36 required' hint from add-second-device

---

src/main/res/values/strings.xml

~~what is a "QR url"? thanks for a translator's hint (to avoid retranslation of all translations, once merged, ./scripts/tx-update-changed-sources.sh needs to be run)~~
EDIT: did the following and changed the string on desktop at https://github.com/deltachat/deltachat-android/pull/3697:
alternatively, we can deprecated the string (it is used as a toast on desktop), and just go for `copied_to_clipboard`, maybe that's better, don't make me think, it only matters that whatever was pasted can be copied to the app later

improve copy-qr-code success wording

---

CHANGELOG.md
src/main/java/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
src/main/res/xml/preferences_advanced.xml

moreover for non-chatmail the option is moved to the other questionable (shared account) options as "watch sent"
first item at advanced is now "Show Log" - same as on desktop and iOS
when this is merged, we should file corresponding issues/pr for desktop/ios

hide 'show classic email' for chatmail

---

src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java
src/main/res/values/strings.xml

this PR is to make the string needed  for https://github.com/chatmail/core/pull/6722 translatable
there were some previous discussions about the wording at https://github.com/chatmail/core/pull/6722/files#r2022229455
the string shows up only when the securejoin process takes more than 15 seconds, here, see the second message in the screenshots:
once this is merged, the string should be pushed to transifex and used on desktop/ios as well
ftr: i did not change the existing string as a new ID is anyway needed and to avoid confusion and to allow smooth transition in other clients
#skip-changelog as the visible change comes from core update

add stock string needed when securejoin takes longer than expected

---

src/main/res/values/strings.xml
src/main/res/xml/preferences_advanced.xml

'App Access' is not about webxdc as the other options few lines above, therefore quite misleading.
i tried first a rewording, only to have _some_ headline, but i think, it is better to not try to get an artificial headline, layout is okay, no one will care :)
nb: for non-chatmail, also "read address book" goes there

remove misleading 'App Access' headline

---

src/main/res/values/strings.xml

this PR tunes down "e-mail"  in the primary UI,  main left overs are "classic login" and the welcome message that referenced email on purpose (we may want to change that, however)
moreover, where appropriate, we go already for "routing" instead of "server"
i also changed the translator hints and some wordings not in the primary UI, where not strictly needed - it makes a difference how we talk about that :)
largest part left, is  the "Show Classic E-Mail" option, that we should probably just hide in case of chatmail (it anyway defaults to "all") EDIT: did a PR: https://github.com/deltachat/deltachat-android/pull/3708

tune down email wording

---

CHANGELOG.md
src/main/java/org/thoughtcrime/securesms/RegistrationActivity.java
src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java
src/main/res/values/strings.xml

Based on #3676. AEAP is disabled in core until it is replaced by multi-transport; this PR removes the (now-wrong) info message.

feat: Remove AEAP message

---

src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java

The NPE (NullPointerException) was caught in `handleEvent()`, so it wasn't user-visible, it just polluted the logs.

fix: Avoid polluting logs because of progressDialog NPE

---

scripts/ndk-make.sh

Running ndk-make.sh triggers a complete rust rebuild, because some compiler flags are changed. Then when you run a normal cargo command again (`cargo check` etc.), there is another rebuild. My solution is to locally change the target directory. This PR makes ndk-make.sh support such custom target directories.
If others are bugged by the same problem as me, we could consider to even always set `CARGO_TARGET_DIR=.cache/ndkmake`.
<details><summary>Details</summary>
<p>
This is how I quickly build&install core for Android:
```bash
nmake () {
(
cd ../..
nix develop --command bash -c "CARGO_TARGET_DIR=.cache/ndkmake scripts/ndk-make.sh --debug arm64-v8a && ./gradlew installFossDebug"
notify-send "Install finished"
)
}
```
</p>
</details>

feat: In ndk-make.sh, support custom CARGO_TARGET_DIR

---

src/main/res/values/strings.xml

this PR adds a hint to "Add Second Device" to the confirmation dialog when sending ASM.
counterpart of https://github.com/chatmail/core/pull/6777

add a hint to 'Add Second Device' for ASM

---

CHANGELOG.md
src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java

classic onboarding allows not setting a displayname on purpose, however, that results in broken webxdc layouts
as the name is then replaced by a 40-or-so-chars-hash-without-spaces.
one can argue, that apps should handle that gracefully, but most do not and just look buggy.
it seems reasonable,
to use the email address in that case,
same as we do at other places if the name is unknwon. (tbh, i thought it was like that, but i mixed sth up in OS comparison). this was also the situation before we changed selfAddr calculation, btw. it is anyway a cornercase, webxdc cannot send the address somewhere nor can correlate reasonably, and if the user sets a name, things are fine (and more often than not we nudge user to set one :)
cmp https://github.com/deltachat/deltachat-desktop/issues/5022

fix selfName if displayname is not set, avoid breaking apps layout

---

src/main/res/values/strings.xml

i think, it is even an improvement for android, as the hint is now also anchored by 'System Settings' which is more in focus by casual users than 'App Settings' (long tap icon). also, some android derivates may have different order,  which is captured better by a broader hint.
the hint is only shown when the access was initially denied.
i was first considering to have different hints, but that's a lot of work, now and to track in the future. i think, it is good enough that way
targets https://github.com/deltachat/deltachat-desktop/pull/4986#issuecomment-2824531972

make 'microphone' hint fitting for desktop as well 

---

CHANGELOG.md
src/main/java/com/b44t/messenger/rpc/Rpc.java

the fix could have been avoid by checking for null or not being overly specific with the exception.
as this is a very sensible area,
where any failure is dramatic,
we do both.
as said, this error pops up on monikas device,
unclear if related to an app update (she is on 1.58.2) or by some message.
~~did not test yet, still trying to get this patch on the phone~~ EDIT: tested, it fixes the issue at hand

fix crash in JSONRPC

---

src/main/res/values/strings.xml

the instructions are shown when there are no Apps, Images etc. in a chat.
while the "shared in this chat" wording
is maybe more correct on an abstract way
(there are other ways than "attach" to have an app), the "attached in this chat" points implicitly better to the new app selector - esp. as the same wording is used for "images",
where the avg user usually knows about how to get that attached.
this little rewording comes from a discussion with @hpk42, surely, there can be more improvements :)

clearer instructions how to add apps&co to a chat

---

CHANGELOG.md
src/main/java/org/thoughtcrime/securesms/ProfileDocumentsAdapter.java
src/main/java/org/thoughtcrime/securesms/components/WebxdcView.java

there is no need to say "App" beside every app in the app list.
moreover, for uncluttered list, the time is removed as well - it is ambigious anyway, see commit message for more reasoning (also  the "Today" header is questionable here, btw. apps may be added months ago and are still super-recent, we are considering to sort the list by recently updated, therefore, let's leave that part unchanged for now)
with icon, name, summary and document name, there are already enough information :)
counterpart of https://github.com/deltachat/deltachat-ios/pull/2721

remove redundant subtitle

---

src/main/res/layout/attachment_type_selector.xml

also otherwise, we say "[attach] Contact", "[attach] File", "[attach] Video" etc. - so it should be "[attach] App" as well.
this is also what desktop/iOS are doing.
the title in the app picker itself, however,
is fine with reading "Apps" - it shows multiple ones

unify singular/plural in attach menu

---

CHANGELOG.md
src/main/java/com/b44t/messenger/rpc/Rpc.java
src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListFragment.java
src/main/res/menu/account_item_context.xml

this uses the new `set_accounts_order` JSON-RPC API introduced in https://github.com/chatmail/core/pull/6993

allow to "move to top" accounts in the accounts list

---

src/main/res/values/strings.xml

as discussed with @hpk42, we want to simplify the terms used in UI, as there is no switch-forth-and-back, the "from now on" is superfluous, and the "guaranteed" is related, at least noisy and raises questions.
also, this allows us to use the same string when establishing via vcard contacts (core PR needs to be done), which is a good thing to move forward just now.
the faq will explain nuances then

simplify e2ee strings

---

CHANGELOG.md
src/main/java/org/thoughtcrime/securesms/ConversationListItem.java
src/main/java/org/thoughtcrime/securesms/ConversationTitleView.java
src/main/java/org/thoughtcrime/securesms/ConversationUpdateItem.java
src/main/java/org/thoughtcrime/securesms/ProfileAdapter.java
src/main/java/org/thoughtcrime/securesms/ProfileAvatarItem.java
src/main/java/org/thoughtcrime/securesms/ProfileTextItem.java
src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java
src/main/java/org/thoughtcrime/securesms/contacts/ContactSelectionListItem.java
src/main/java/org/thoughtcrime/securesms/util/SelectedContactsAdapter.java
src/main/res/layout/conversation_item_update.xml
src/main/res/layout/profile_text_item_small.xml
src/main/res/values/strings.xml

tune down green checkmark

---

src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java

the comment is also removed instead adapted; it is kind of obvious, and we do not have comments on that detail level usually

remove stock strings no longer in use

---

flake.nix

Since buildToolsVersion is not specified in `build.gradle`, default version is set by Android Gradle Plugin.
Gradle plugin was updated in a77b1a5dd66fd30267e01c9ee97152d53240cc62, so build tools version should be updated in flake.nix to the corresponding version, otherwise building
fails while trying to install 35.0.0 into
read-only path managed by Nix.

Update Android SDK Build Tools to 35.0.0 in flake.nix

---

CHANGELOG.md
src/main/res/values/themes.xml

this improves readability of info messages
by setting the foreground to while.
`universal_overlay` was made for that;
it is in use like that on iOS/desktop since a long time.
moreover, other parts using the combination of
`conversation_item_update_bg_color`/`conversation_item_update_text_color` are improved equally, eg. the day titles.
before / after using the standard background:
before after using a harder background:

improve info messages for dark theme

---

CHANGELOG.md
src/main/java/org/thoughtcrime/securesms/ShareActivity.java
src/main/java/org/thoughtcrime/securesms/connect/DirectShareUtil.java

close #3853 
this problem was introduced in https://github.com/deltachat/deltachat-android/pull/3558 (in [this lines](https://github.com/deltachat/deltachat-android/pull/3558/files#diff-676161241c610355e67385e50f4acb3aba922047a8161cd134062739315f2754L211-L214))
the problem is that, at least in some devices, when the shortcut is opened from direct share, it doesn't contains the custom extras we set, but the shortcut's ID, which we need to parse then

fix direct share shortcuts

---

CHANGELOG.md
src/main/java/com/b44t/messenger/DcAccounts.java
src/main/java/org/thoughtcrime/securesms/components/reminder/DozeReminder.java
src/main/java/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java
src/main/java/org/thoughtcrime/securesms/util/Prefs.java
src/main/res/xml/preferences_notifications.xml

default to permanent notification if push is not possible

---

src/main/res/values/strings.xml

the string can be used for the action to put a message to 'Saved Messages'.
it will be useful esp. on desktop,
where plain 'Save' often has the mindset of 'Files', esp. for older ppl :)
the added noun tries to break that.
additionally, desktop can resort menu items,
but that alone would not solve the issue.
android/ios does not really have that issue as it is far less about "Files" there, still, they can use the new string at some point.
there are also thoughs about renaming that alltogether, eg. to bookmark, but that is a larger and more breaking change, also the messages are not just 'bookmarked' on purpose, to eg. survive auto deletion.
once this is merged, we can pick the new string on desktop (maybe give it a bit time to be translated)

add 'Save Message' string
