deltachat/deltachat-android

MessengerProj/src/main/res/values/strings.xml
Hi @r10s,
Please review and merge the PR.
*Fixed some typos and grammatical errors that are displayed during intro in English.
=> Fix some typos in english intro

MessengerProj/src/main/res/values-fr/strings.xml
Added new translations
Corrected my and other's mistaken translations.
=> French translation

MessengerProj/src/main/res/values-de/strings.xml
To align with (coming) web updates
=> Intro5 Message updates in strings.xml (de)

MessengerProj/src/main/java/com/b44t/messenger/KeepAliveService.java
Click on Notification opens Delta Chat
=> Notification clickable

MessengerProj/src/main/java/com/b44t/messenger/DocumentSelectActivity.java
Fixes #209. I tested it shortly and it worked.
=> Do not send messages when there is an access error

MessengerProj/src/main/java/com/b44t/messenger/LaunchActivity.java
Fixes #83 and partly #236. What do you think?
=> Show the PermissionContact dialog only once

MessengerProj/jni/mrwrapper.c, MessengerProj/src/main/java/com/b44t/messenger/Cells/ChatMessageCell.java, MessengerProj/src/main/java/com/b44t/messenger/ChatActivity.java, MessengerProj/src/main/java/com/b44t/messenger/ChatlistActivity.java, MessengerProj/src/main/java/com/b44t/messenger/MrMailbox.java, MessengerProj/src/main/java/com/b44t/messenger/ProfileActivity.java
this PR just uses the functions from the core PR https://github.com/deltachat/deltachat-core/pull/115
=> Use new function to create groups directly from the Contact requests

.github/ISSUE_TEMPLATE.md
* commented out our statements so we don't have them visible in issues if ppl. don't remove them
* created a `details` section so long logs are expandable
=> updated ISSUE_TEMPLATE.md

res/layout/attachment_type_selector.xml, res/layout/conversation_activity_attachment_editor_stub.xml, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/attachments/Attachment.java, src/org/thoughtcrime/securesms/components/AttachmentTypeSelector.java, src/org/thoughtcrime/securesms/components/location/SignalMapView.java, src/org/thoughtcrime/securesms/components/location/SignalPlace.java, src/org/thoughtcrime/securesms/mms/AttachmentManager.java, src/org/thoughtcrime/securesms/mms/LocationSlide.java
restore the code for the location for future use, but hide it from the sharing area.
=> Hide share location

res/values/arrays.xml, res/values/strings.xml, res/xml/preferences_notifications.xml, src/org/thoughtcrime/securesms/preferences/widgets/LEDColorListPreference.java
This should be tested by people whose phone supports purple LED. (Mine does not)
=> allowing the LED color to be purple.

res/layout/registration_activity.xml
=> disable autocorrection on server input fields

res/drawable-v21/conversation_list_item_background.xml, res/drawable-v21/conversation_list_item_background_dark.xml, res/drawable/conversation_item_background.xml, res/drawable/conversation_item_background_animated.xml, res/drawable/conversation_list_item_background.xml, res/drawable/conversation_list_item_background_dark.xml, res/drawable/progress_button_state.xml, res/drawable/reminder_background_normal.xml, res/drawable/touch_highlight_background.xml, res/layout/activity_select_chat_background.xml, res/layout/contact_selection_list_divider.xml, res/layout/conversation_input_panel.xml, res/layout/conversation_list_fragment.xml, res/layout/group_create_activity.xml, res/layout/media_overview_activity.xml, res/layout/permissions_rationale_dialog.xml, res/layout/preference_right_summary_widget.xml, res/layout/profile_create_activity.xml, res/layout/scribble_select_sticker_activity.xml, res/layout/transport_selection_list_item.xml, res/layout/welcome_activity.xml, res/values/colors.xml, res/values/styles.xml, res/values/themes.xml, src/org/thoughtcrime/securesms/ConversationListFragment.java, src/org/thoughtcrime/securesms/TransportOptions.java, src/org/thoughtcrime/securesms/notifications/MultipleRecipientNotificationBuilder.java, src/org/thoughtcrime/securesms/notifications/SingleRecipientNotificationBuilder.java
this pr makes the buttons slighly lighter; although they were using the same color as the title bar before, due to their size the look too dark.
moreover, this pr cleans up some color names.
=> tweak buttons

AndroidManifest.xml, src/org/thoughtcrime/securesms/ShareActivity.java
See #464 for more information.
=> Can't share with pattern set #464

build.gradle, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java, src/org/thoughtcrime/securesms/connect/KeepAliveService.java, src/org/thoughtcrime/securesms/connect/ScreenReceiver.java
this pr not just increases the targetSdkVersion but also does changes required wrt background execution, see https://developer.android.com/about/versions/oreo/android-8.0-changes
closes #436
=> change targetSdkVersion from 25 to 26

src/org/thoughtcrime/securesms/RecipientPreferenceActivity.java
=> No feedback when blocking contact #699

src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/notifications/MessageNotifier.java
Please test if the reduced importance also reduces the annoyance.
=> Notification issue 451

src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/notifications/AndroidAutoHeardReceiver.java, src/org/thoughtcrime/securesms/notifications/AndroidAutoReplyReceiver.java, src/org/thoughtcrime/securesms/notifications/MarkReadReceiver.java, src/org/thoughtcrime/securesms/notifications/MessageNotifier.java, src/org/thoughtcrime/securesms/notifications/MultipleRecipientNotificationBuilder.java, src/org/thoughtcrime/securesms/notifications/NotificationState.java, src/org/thoughtcrime/securesms/notifications/SingleRecipientNotificationBuilder.java, src/org/thoughtcrime/securesms/util/Prefs.java
=> fix crash wrt notifications

AndroidManifest.xml, jni/Android.mk, jni/dc_wrapper.c, res/layout/registration_activity.xml, res/values/arrays.xml, res/values/strings.xml, src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/RegistrationActivity.java, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java, src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java, standards.md
requires https://github.com/deltachat/deltachat-core/pull/578 to be merged first
=> implement OAuth2

src/org/thoughtcrime/securesms/NewConversationActivity.java
Fix for #716.
- Subject and body are now handled
- To avoid bigger changes the created share text is added as extra to the intent, as this is already handled by the app
- Tested for existing and new contacts
- Should also work for a combination of mail + subject + body
=> mailto:-links without address should work as "share" #716

src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
this results in sth. as `X-Mailer: Delta Chat Core 0.1/Android 0.2`; cmp. https://github.com/deltachat/deltachat-core/pull/576
=> add version to X-Mailer

res/layout/profile_create_activity.xml, res/layout/registration_activity.xml, res/values/strings.xml
- add "no delta servers" hint
- move "advanced" button more to the top, hint below (this way it should not happen that you click the button and nothing is changed on the screen without scrolling)
- left align text
- tweak spacing
=> tweak onboarding

store/text.md
@r10s please upload it -- i didn't change content, just formatting which doesn't look good on gplay.
=> fix formatting for gplay store

res/layout/registration_activity.xml, res/values/strings.xml, src/org/thoughtcrime/securesms/LogViewActivity.java, src/org/thoughtcrime/securesms/RegistrationActivity.java
Added link to Logview at the end of advanced settings on the registration page
=> log should be reachable during onboarding #744

src/org/thoughtcrime/securesms/ShareActivity.java
@Boehrsi this pr should fix #762, maybe you can have a look
=> fix crash when sharing link, closes #762

src/org/thoughtcrime/securesms/ShareActivity.java
closes #764, also here, @Boehrsi would be great if you can have a quick look at this
=> fix handling mailto:-share-links

src/org/thoughtcrime/securesms/ContactSelectionListFragment.java
Added the updating of the counter also when selecting all entries via the menu.
=> [UI] Selecting all contacts but counter still not updated #753

src/org/thoughtcrime/securesms/contacts/avatars/SystemContactPhoto.java
Just set the requested image quality to high.
=> Low quality contact picture #463

src/org/thoughtcrime/securesms/ConversationListItem.java
Moved the actual group check from the recipient to the chat.
=> Group with 1 member not shown as group #732

build.gradle, res/layout/bottom_map_sheet.xml, res/values/strings.xml, res/values/styles.xml, src/org/thoughtcrime/securesms/ApplicationContext.java, src/org/thoughtcrime/securesms/components/rangeslider/RangeSliderView.java, src/org/thoughtcrime/securesms/components/rangeslider/TimeRangeSlider.java, src/org/thoughtcrime/securesms/map/GenerateInfoWindowCallback.java, src/org/thoughtcrime/securesms/map/GenerateInfoWindowTask.java, src/org/thoughtcrime/securesms/map/MapActivity.java, src/org/thoughtcrime/securesms/map/MapDataManager.java, src/org/thoughtcrime/securesms/map/model/FilterProvider.java, src/org/thoughtcrime/securesms/map/model/MapSource.java, src/org/thoughtcrime/securesms/util/DateUtils.java
* fixes crashes on layout change
* reduce the amount of layers
* reduce the amount of used RAM
* implement filtering for traces
* show last positions of the last 24 hours
* add LeakCanary - it will help us to detect memory leaks during the development
=> Location streaming stabilization

build.gradle, src/org/thoughtcrime/securesms/ApplicationContext.java
=> disable leak canaray for now

src/org/thoughtcrime/securesms/components/ComposeText.java
=> set landscape full-screen-editor button-label

src/org/thoughtcrime/securesms/components/rangeslider/TimeRangeSlider.java, src/org/thoughtcrime/securesms/map/MapActivity.java, src/org/thoughtcrime/securesms/map/MapDataManager.java, src/org/thoughtcrime/securesms/map/model/FilterProvider.java
* fixes location updates on the map
* white character on markers
* avoid collisions with info window when character markers are shown
=> Location updates

src/org/thoughtcrime/securesms/notifications/AbstractNotificationBuilder.java
=> catch color parsing errors

res/layout/fragment_view_log.xml
=> tweak log view

jni/dc_wrapper.c, src/com/b44t/messenger/DcArray.java, src/com/b44t/messenger/DcMsg.java
requires https://github.com/deltachat/deltachat-core/pull/667 to be merged first
=> add api for independent markers

src/org/thoughtcrime/securesms/ShareActivity.java
I'm just closing the ShareActivity after creating the new one, which fixes the problem for me.
=> Bad behavior by forwarding a message #867

build.gradle, src/org/thoughtcrime/securesms/map/MapActivity.java, src/org/thoughtcrime/securesms/map/MapDataManager.java
* a little dot and a bearing indicator on the map show the user's current device position
* update of mapbox sdk required
=> show own device location independent of location streaming

res/drawable/ic_location_poi_dot.xml, res/values/strings.xml, src/org/thoughtcrime/securesms/map/DataCollector.java, src/org/thoughtcrime/securesms/map/MapActivity.java, src/org/thoughtcrime/securesms/map/MapDataManager.java, src/org/thoughtcrime/securesms/map/model/MapSource.java
* delete pois (DC_LOCATION_UPDATE event on core side missing yet)
* add labels below POIs if they have a longer description than 1 character
* add labels below last position marker showing the user's display name
* fix disappearing markers when info windows appears
* slight differentiation between POI markers and message markers
=> Poi improvements

AndroidManifest.xml, res/layout/log_view_activity.xml, res/menu/view_log.xml, res/values/strings.xml, src/org/thoughtcrime/securesms/LogViewActivity.java, src/org/thoughtcrime/securesms/LogViewFragment.java
=> Enhance log with scroll and zoom possibility

README.md
Will do the other ones if this is accepted.
=> Fix typos and words in Readme

res/values/arrays.xml, res/values/strings.xml, res/xml/preferences_advanced.xml, res/xml/preferences_chats.xml, src/org/thoughtcrime/securesms/audio/AudioCodec.java, src/org/thoughtcrime/securesms/audio/AudioRecorder.java, src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java, src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java, src/org/thoughtcrime/securesms/video/recode/VideoRecoder.java
=> resort some advanced options

src/org/thoughtcrime/securesms/geolocation/DcLocationManager.java
=>  try to stop location-engine more gracefully

src/org/thoughtcrime/securesms/notifications/SingleRecipientNotificationBuilder.java
at least prevents crashes as #938
=> do not crash on loading failures

src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/ConversationListFragment.java, src/org/thoughtcrime/securesms/notifications/AbstractNotificationBuilder.java, src/org/thoughtcrime/securesms/notifications/MessageNotifier.java, src/org/thoughtcrime/securesms/notifications/MessageNotifierCompat.java, src/org/thoughtcrime/securesms/notifications/MessageNotifierPreApi23.java, src/org/thoughtcrime/securesms/notifications/MultipleRecipientNotificationBuilder.java, src/org/thoughtcrime/securesms/notifications/SingleRecipientNotificationBuilder.java, src/org/thoughtcrime/securesms/util/Util.java
improvements:
- android sound settings are considered
- related notifications get deleted if chat with unread messages gets deleted
- guarantee thread safety, different threads can change the notification state
=> Notification review

res/layout/conversation_item_last_seen.xml, res/values/attrs.xml, res/values/strings.xml, res/values/themes.xml, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationAdapter.java, src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/ConversationListActivity.java, src/org/thoughtcrime/securesms/ConversationListArchiveActivity.java, src/org/thoughtcrime/securesms/ConversationListFragment.java, src/org/thoughtcrime/securesms/map/MapActivity.java, src/org/thoughtcrime/securesms/search/SearchFragment.java
* shows the 'x unread messages' header if 
1. the user has entered a chat, but the app is in background / the screen went off / another activity like the profile is on top of the chat
2. and a new message arrived
* the header disappears if:
1. the user sends a new message
2. a new message arrives while the user has opened the chat and the chat is visible
3.  the user goes back to the chat list
* no header appears if:
1. a new message arrived while the user has not entered the chat yet (a notification is visible in the notification bar and the unread message badge in the chat list though)
=> show new message marker #447

src/org/thoughtcrime/securesms/NewConversationActivity.java
Adjusted our checks to avoid the wrong handling of the input.
=> mailto links with a body but no subject #937

res/xml/preferences_advanced.xml, res/xml/preferences_chats.xml, src/org/thoughtcrime/securesms/connect/DcHelper.java, src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java, src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java, src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java, src/org/thoughtcrime/securesms/util/Prefs.java
=> move backup option to settings/chats (#957)

src/org/thoughtcrime/securesms/database/loaders/BucketedThreadMediaLoader.java
=> change order of inserted document/gallery items (#960)

src/org/thoughtcrime/securesms/CreateProfileActivity.java
=> add a hint that self-avatar is not completely working as expected

res/menu/view_log.xml, res/values/strings.xml, src/org/thoughtcrime/securesms/LogViewActivity.java, src/org/thoughtcrime/securesms/LogViewFragment.java
Not sure about the file name and what is the best place to define it.
=> Added saving the log to file

jni/dc_wrapper.c, res/layout/empty_folder_options.xml, res/values/strings.xml, res/xml/preferences_advanced.xml, src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
needs https://github.com/deltachat/deltachat-core/pull/691 to be merged first, closes #966
=> add controls to empty folder on server

AndroidManifest.xml, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationListActivity.java, src/org/thoughtcrime/securesms/ShareActivity.java, src/org/thoughtcrime/securesms/service/DirectShareService.java, src/org/thoughtcrime/securesms/util/RelayUtil.java
=> share to single contacts (#900)

src/org/thoughtcrime/securesms/LogViewActivity.java, src/org/thoughtcrime/securesms/LogViewFragment.java
Code cleanup for saving the Log to file
=> Code cleanup for saving the Log to file

src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java
=> init the show-emails-option with the correct value

src/org/thoughtcrime/securesms/RegistrationActivity.java
looks like the following:
closes #981
=> add a warning when using outlook/hotmail addresses

src/org/thoughtcrime/securesms/notifications/MessageNotifier.java
=> fix notifications

res/drawable/preference_divider_dark.xml, res/drawable/preference_divider_light.xml
Added border definitions to the dark and light preference divider.
Changed the background color for the dark divider.
=> Added border definitions to preference divider

jni/dc_wrapper.c, src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
=> call dc_perform_mvbox|sentbox_jobs()

src/org/thoughtcrime/securesms/ConversationTitleView.java, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
=> hack plurals string for 'N member(s)'

src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
cmp https://github.com/deltachat/deltachat-core-rust/issues/682
=> add hint that empty-server is currently not implemented

jni/dc_wrapper.c, src/com/b44t/messenger/DcChat.java, src/org/thoughtcrime/securesms/ConversationTitleView.java, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java, src/org/thoughtcrime/securesms/recipients/Recipient.java
here are some background-info https://github.com/deltachat/deltachat-desktop/issues/1045
=> remove calls to dc_chat_get_subtitle()

build.gradle
* fixes potential compatibility issues aft sdk update to API 28
* works around jitpack issue https://github.com/jitpack/jitpack.io/issues/4002
=> Tweak build gradle

build.gradle, src/org/thoughtcrime/securesms/QrShowActivity.java
based on #1069 
closes https://github.com/deltachat/deltachat-android/issues/1068
=> Fix leaking receiver

jni/dc_wrapper.c
targets https://github.com/deltachat/deltachat-android/issues/1065 - while the crash is already fixed with https://github.com/deltachat/deltachat-core-rust/pull/728, this pr makes sending emojis & co. _possible_ :)
=> fix utf8 issues for android4

build.gradle, src/org/thoughtcrime/securesms/ConversationItem.java, src/org/thoughtcrime/securesms/audio/AudioSlidePlayer.java, src/org/thoughtcrime/securesms/components/AudioView.java, src/org/thoughtcrime/securesms/mms/AttachmentManager.java, src/org/thoughtcrime/securesms/util/DateUtils.java, src/org/thoughtcrime/securesms/video/VideoPlayer.java, src/org/thoughtcrime/securesms/video/exo/AttachmentDataSource.java, src/org/thoughtcrime/securesms/video/exo/AttachmentDataSourceFactory.java
(based on 80deb301e54c766acd3bfc7edbec400b03a44c4d). 
Closes #1088
=> update audio playing capabilitys to signals current state

res/layout/registration_activity.xml, res/values/arrays.xml, res/values/strings.xml, src/org/thoughtcrime/securesms/RegistrationActivity.java
=> Hostname / certificate validation

jni/dc_wrapper.c, res/values/strings.xml, src/com/b44t/messenger/DcChat.java, src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationTitleView.java, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
should be merged after https://github.com/deltachat/deltachat-core-rust/pull/794
=> adapt to device-messages api

src/org/thoughtcrime/securesms/PassphraseRequiredActionBarActivity.java
i came over that while finding the correct places to add welcome-device-messages.
=> simplify routing to welcome-activity

docs/release-checklist.md
@r10s meant that he doesn't need to upload the apk to github anymore, if it's offered on our download-server anyway.
=> Upload apk to download.delta.chat

AndroidManifest.xml, res/layout/conversation_list_activity.xml, res/values/strings.xml, res/values/untranslatable.xml, src/org/thoughtcrime/securesms/ConversationListActivity.java
This merges #1122 and changes the strings according to the recommendations there.
=> Language updates

AndroidManifest.xml, src/org/thoughtcrime/securesms/ConversationListActivity.java, src/org/thoughtcrime/securesms/qr/QrCodeHandler.java
implement delta chat login show case
=> implement openpgp4fpr url scheme handling

jni/dc_wrapper.c, src/com/b44t/messenger/DcContext.java, src/com/b44t/messenger/DcProvider.java
usage eg. 
```
DcProvider provider = getProviderFromEmail("ola@gmail.com");
if(provider!=null) {
String name = provider.getName();
Log.i(TAG, name);
int status = provider.getStatus();
Log.i(TAG, String.format("%d", status));
String statusDate = provider.getStatusDate();
Log.i(TAG, statusDate);
String markdown = provider.getMarkdown();
Log.i(TAG, markdown);
String overviewPage = provider.getOverviewPage();
Log.i(TAG, overviewPage);
}
```
=> add provider-info api

res/values/strings.xml, src/org/thoughtcrime/securesms/ConversationAdapter.java, src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
make device messages translatable, adapt empty-chat-hints
=> adapt locale things

docs/release-checklist.md
some more explanation and fixes to the commands.
=> Release Checklist: fix upload to dl.delta.chat

src/org/thoughtcrime/securesms/CreateProfileActivity.java
can be merged after https://github.com/deltachat/deltachat-core-rust/pull/982 is merged
=> remove hint that user-avatars are not implemented

src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
=> better message if a media-type cannot be handled

src/org/thoughtcrime/securesms/notifications/MessageNotifierPreApi23.java
esp. for the welcome-messages, this is too much noise.
fixed #1182
=> do not add system-notifications on new device messages

src/org/thoughtcrime/securesms/LogViewActivity.java
esp. needed when not yet configured.
fixes #1180
=> check disk-write-permissions on saving logs

res/values/strings.xml, src/org/thoughtcrime/securesms/util/SaveAttachmentTask.java
This fix introduces a message to be displayed to the user that says where a file has been stored.
I'm uncertain if I got  the strings.xml right or if I need to do anything more so that translations can pick this up.
=> Fix990 saving voice message

AndroidManifest.xml, assets/help/de/help.html, assets/help/en/help.html, assets/help/help.css, res/layout/local_help_activity.xml, res/menu/local_help.xml, res/menu/text_secure_normal.xml, src/org/thoughtcrime/securesms/ApplicationPreferencesActivity.java, src/org/thoughtcrime/securesms/ConversationListActivity.java, src/org/thoughtcrime/securesms/LocalHelpActivity.java
this pr will provide the current online help/faqs as offline pages.
(just an example, with the current online help)
=> local help/faq

res/values-ko/strings.xml, res/values-nb/strings.xml, res/values-sr/strings.xml, res/values-ta/strings.xml, res/values-te/strings.xml, res/values/arrays.xml
add from the old repo, found during transifex cleanup
=> add languages

src/org/thoughtcrime/securesms/ConversationActivity.java
this bug was also introduced with the attempt to fix #743, see #1220 for some details.
it was not present in delta 1.0
closes #1220 again :)
=> fix losing draft when opening  eg. gallery

jni/dc_wrapper.c, res/layout/registration_activity.xml, res/values/colors.xml, src/com/b44t/messenger/DcContext.java, src/com/b44t/messenger/DcProvider.java, src/org/thoughtcrime/securesms/RegistrationActivity.java
this pr will check on login if the used provider needs preparations or is totally broken; in both cases, hints are shown.
the information come from the core, see https://github.com/deltachat/deltachat-core-rust/pull/1207,
needs https://github.com/deltachat/deltachat-core-rust/pull/1207 to be merged first.
(the red-box screenshot looks a bit ugly, but this is an emulator/screenshot thing, in reality it is nice :) (what is reality?)
=> implement provider-db

AndroidManifest.xml, jni/dc_wrapper.c, res/layout/activity_registration_qr.xml, res/layout/welcome_activity.xml, src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/RegistrationActivity.java, src/org/thoughtcrime/securesms/WelcomeActivity.java, src/org/thoughtcrime/securesms/qr/QrActivity.java, src/org/thoughtcrime/securesms/qr/QrCodeHandler.java, src/org/thoughtcrime/securesms/qr/RegistrationQrActivity.java
**before this pr can be merged,  https://github.com/deltachat/deltachat-core-rust/pull/1249 needs to be merged first!**
this pr is about the ui around the new burner-account features.
=> burner accounts, tweak onboarding

res/layout/profile_create_activity.xml, src/org/thoughtcrime/securesms/CreateProfileActivity.java, src/org/thoughtcrime/securesms/WelcomeActivity.java
this pr adds a screen after account-creation, where the user can enter a name and an avatar, counterpart to https://github.com/deltachat/mailadm/pull/2 (cc @hpk42 ;)
=> Enter displayname

res/xml/preferences.xml, res/xml/preferences_advanced.xml, res/xml/preferences_app_protection.xml, res/xml/preferences_appearance.xml, res/xml/preferences_chats.xml, src/org/thoughtcrime/securesms/preferences/AppProtectionPreferenceFragment.java, src/org/thoughtcrime/securesms/preferences/AppearancePreferenceFragment.java, src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java
split from https://github.com/deltachat/deltachat-android/pull/1257
=> re-order settings

assets/help/help.css
use sth. as the accent-color for links in the help.
=> tweak help colors

jni/dc_wrapper.c, res/layout/autodel_confirm.xml, res/values/arrays.xml, res/values/strings.xml, res/xml/preferences_chats.xml, src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java, src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java
this pr is about the ui of https://github.com/deltachat/deltachat-core-rust/pull/1310 (delete-from-server) and can be easily enhanced for targeting https://github.com/deltachat/deltachat-core-rust/issues/1309 (delete-from-device) later. both will be created as independent options.
previous thoughts:
~~i am currently thinking about two options:~~
1. ~~showing two checkboxes and one time-selectors (1hour, 1day, 1week etc, maybe a slider)~~
2. ~~showing two time-selectors~~
~~2 seems easier to implement, also as the core does not have an on/off setting preserving the time. also ui-wise, 2 seems to be easier to understand. 2 also has the advantage, that it has some build-in-protection against accidentally enabling, for 1., we would probably needs some extra-dialog or so, checkboxes are pretty …
=> autodelete messages from server

src/org/thoughtcrime/securesms/service/DirectShareService.java
In direct sharing, propose only chats we can send to, fix #1274
=> In direct sharing, propose only chats we can send to, fix #1274

src/org/thoughtcrime/securesms/RegistrationActivity.java
See https://github.com/deltachat/deltachat-core-rust/issues/1377.
=> Make the links in the dialog clickable (needed for Yandex)

.tx/config, res/values-fa/strings.xml, res/values-in/strings.xml, res/values/arrays.xml
=> add indonesian and persian (farsi)

jni/dc_wrapper.c, res/menu/text_secure_normal.xml, res/values/strings.xml, res/xml/preferences_advanced.xml, src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/ConversationListActivity.java, src/org/thoughtcrime/securesms/ConversationListFragment.java, src/org/thoughtcrime/securesms/WelcomeActivity.java, src/org/thoughtcrime/securesms/connect/AccountManager.java, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java, src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java, src/org/thoughtcrime/securesms/util/Prefs.java
well, finally, this pr brings multi account to android:
adding a new account brings you back to the "welcome screen" from where you can also scan a new account :)
in my tests, this works out pretty nice, however, it is an "exeperimental feature", EDIT: you find it at  "Settings / Advanced / Experimental features / Switch account" - if you have more than one account, you can also long-press the "+" icon ;)
=> multi account

res/values/arrays.xml, res/values/strings.xml
as discussed in the testing group, cc @adbenitez 
@link2xt i think, as there are no more jobs filed, longer timespans should not be an issue any longer.
=> add auto-delete-option 'after 1 year'

CHANGELOG.md, build.gradle, src/org/thoughtcrime/securesms/ConversationListActivity.java
screenshot of the device message:
=> prepare version 1.6

CHANGELOG.md, build.gradle
this version only updates the permantent-notification device-message in english, spanish, swedish
=> prepare 1.6.2

src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java, src/org/thoughtcrime/securesms/connect/DcHelper.java, src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java, src/org/thoughtcrime/securesms/util/Prefs.java
=> use media-quality-option from core

ndk-make.sh
=> clarify that newer ndk versions will likely work

src/org/thoughtcrime/securesms/mms/AttachmentManager.java
Fix #1347 Draft file name "Unknown".
getManuallyCalculatedSlideInfo() in AttatchmentManager sometimes failed to get a file name. Now, in this case, it is just extracted from the uri.
=> Fix #1347 Draft file name "Unknown".

src/org/thoughtcrime/securesms/notifications/NotificationCenter.java
bug reported at https://github.com/deltachat/deltachat-android/pull/1368#pullrequestreview-417683746, thanks @angelo-fuchs
=> respect in-chat-notification setting for outgoing messages

build.gradle, jni/dc_wrapper.c, src/com/b44t/messenger/DcContext.java, src/com/b44t/messenger/DcEvent.java, src/com/b44t/messenger/DcEventEmitter.java, src/org/thoughtcrime/securesms/RegistrationActivity.java, src/org/thoughtcrime/securesms/WelcomeActivity.java, src/org/thoughtcrime/securesms/connect/AccountManager.java, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java, src/org/thoughtcrime/securesms/connect/FetchWorker.java, src/org/thoughtcrime/securesms/connect/ForegroundDetector.java
this pr shifts the android-ui using the new async-core-api - core-threads are handled in the core from now on and the ui will use an event-emmiter-object to get events.
~~the pr requires the core-submodule checked out at https://github.com/deltachat/deltachat-core-rust/pull/1356~~
~~before this can finally be merged, https://github.com/deltachat/deltachat-core-rust/pull/1356 has to be merged first.~~
EDIT: the core is ready :)
=> use async core

Dockerfile
=> get rust-toolchain from core repository

src/org/thoughtcrime/securesms/ProfileActivity.java
Change the enlarged avatar name to the chat name
Do not enlarge avatar if there is none (just a big letter in a circle)
=> Avatars again

src/org/thoughtcrime/securesms/ConversationListActivity.java, src/org/thoughtcrime/securesms/ConversationListFragment.java
Do not show the devicetalk when forwarding or sharing.
=> Do not show the devicetalk when forwarding or sharing.

src/org/thoughtcrime/securesms/connect/ForegroundDetector.java
closes https://github.com/deltachat/deltachat-android/issues/1390
=> call maybeNetwork() when app comes to foreground to catch up the state

src/org/thoughtcrime/securesms/ConversationFragment.java
Fix #1404 Do not truncate copy-pasted text. Also, improve code style a
bit.
=> Fix #1404 Do not truncate copy-pasted text

src/org/thoughtcrime/securesms/ApplicationContext.java, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java, src/org/thoughtcrime/securesms/connect/FetchWorker.java, src/org/thoughtcrime/securesms/connect/ForegroundDetector.java
this should help on finding out what is going on on background network-reconnects etc. and improve reliability when app comes to foreground.
=> streamline rough logging on app-foreground etc.

res/values/strings.xml, src/org/thoughtcrime/securesms/RegistrationActivity.java, src/org/thoughtcrime/securesms/util/task/ProgressDialogAsyncTask.java, src/org/thoughtcrime/securesms/util/views/ProgressDialog.java
=> move getOauth2Url() to an async task

res/values/strings.xml
follow-up of https://github.com/deltachat/deltachat-ios/pull/809
=> add info.plist permission description

docs/release-checklist.md, res/values/strings.xml, src/org/thoughtcrime/securesms/ConversationListActivity.java
=> add device message for 1.10

src/org/thoughtcrime/securesms/ConversationListActivity.java
i think, it makes some sense to link from the release-message to the blog-entry - however, this should only be merged when the https://github.com/deltachat/deltachat-pages/pull/354 is merged (all these dependencies ...)
=> add link to blog-entry to device-message

jni/dc_wrapper.c, src/com/b44t/messenger/DcContext.java
Adds API from https://github.com/deltachat/deltachat-core-rust/pull/1540 to JNI
=> Add ephemeral message timer API

res/values/arrays.xml, res/values/strings.xml
fixes duplicated strings in strings.xml
=> avoid redundant strings in strings.xml

src/org/thoughtcrime/securesms/scribbles/ImageEditorHud.java
=> fix blurring of images after using highlighting pencil

res/values/strings.xml, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
=> Ephemeral systemmessage strings

res/menu/conversation.xml, res/values/strings.xml, res/xml/preferences_advanced.xml, src/org/thoughtcrime/securesms/EphemeralMessagesDialog.java
this pr introduces the term "Disappearing messages"  and also moves the function more to focus (up in the menu).
not sure, if that get's merged, see irc for some discussion :)
=> disappearing messages

src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/util/BitmapUtil.java
allow sending images uncompressed, remove recoding code that is in the core now, closes #1485
=> fix image recompression

res/layout/dialog_extended_options.xml, res/values/strings.xml, src/org/thoughtcrime/securesms/EphemeralMessagesDialog.java
...showing a hint about the implications of this feature
closes #1497
=> implement custom view for ephemeral messages dialog 

src/org/thoughtcrime/securesms/ConversationActivity.java
=> fix messageType for drafted gifs

AndroidManifest.xml, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
=> ask for install permission if on an attached apk was tapped

jni/dc_wrapper.c, res/drawable/ic_map_white_24dp.xml, res/drawable/ic_videocam_white_24dp.xml, res/layout/conversation_item_videochat.xml, res/layout/single_line_input.xml, res/menu/conversation.xml, res/values/attrs.xml, res/values/strings.xml, res/values/themes.xml, res/xml/preferences_advanced.xml, src/com/b44t/messenger/DcChat.java, src/com/b44t/messenger/DcContext.java, src/com/b44t/messenger/DcMsg.java, src/org/thoughtcrime/securesms/BaseActionBarActivity.java, src/org/thoughtcrime/securesms/BindableConversationItem.java, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationAdapter.java, src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/ConversationVideochatItem.java, src/org/thoughtcrime/securesms/LocalHelpActivity.java, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java, src/org/thoughtcrime/securesms/connect/DcHelper.java, src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java, src/org/thoughtcrime/securesms/qr/QrCodeHandler.java, src/org/thoughtcrime/securesms/videochat/VideochatUtil.java
this pr adds sending and receiving videocall invitations as provided by the new api from https://github.com/deltachat/deltachat-core-rust/pull/1735
the call itself is done in a browser or in apps as "jitsi meet".
to use jitsi for video calls, you can scan the following qr-code:
=> handle videocall invitations

res/layout/conversation_item_videochat.xml, res/layout/single_line_input.xml, src/org/thoughtcrime/securesms/videochat/VideochatUtil.java
=> tweak videocalls

CHANGELOG.md, build.gradle
i'd like to have a look at bug #1523 before doing an update.
=> prepare 1.12.2

res/layout/registration_activity.xml
=> no word suggestions for imap and smtp login name

build.gradle
* fixes #1283
I could reproduce the crash on an android 5 emulator, the dependency update fixes the crash (tested)
also updates other androidx compat libraries
=> update androidx dependencies

src/org/thoughtcrime/securesms/ConversationFragment.java
=> Make links in info messages clickable

res/layout/conversation_item_update.xml
=> Make even more links clickable

res/values/strings.xml
=> reword login errors as suggested in #1313

AndroidManifest.xml, build.gradle, src/org/thoughtcrime/securesms/mms/AttachmentManager.java
=> Update target sdk

src/org/thoughtcrime/securesms/ConversationFragment.java
=> update list every minute so that time labels are updated correctly

src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationItem.java, src/org/thoughtcrime/securesms/util/LongClickCopySpan.java
@link2xt, @adbenitez Some suggestions for your pr #1567
=> Linkify cmds2

src/org/thoughtcrime/securesms/map/MapActivity.java, src/org/thoughtcrime/securesms/map/MapDataManager.java
=> remove pois from map

res/layout/registration_activity.xml, src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
=> Improve keyboard layouts

src/org/thoughtcrime/securesms/notifications/NotificationCenter.java
=> set notification group only for Android API 24+

src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationItem.java, src/org/thoughtcrime/securesms/util/LongClickCopySpan.java
This makes bot commands similar to `/echo` clickable.
Patch from @adbenitez
=> Linkify commands

res/layout/map_bubble_layout.xml, res/values/attrs.xml, src/org/thoughtcrime/securesms/components/emoji/EmojiProvider.java, src/org/thoughtcrime/securesms/components/emoji/EmojiTextView.java, src/org/thoughtcrime/securesms/components/emoji/parsing/EmojiPageBitmap.java
reintroduce 4707efb26ae48be2087c0a175efde33bc6b1fb11 in order to fix app crash on map #793
=> fix regression caused by diversied emoji update. 

src/org/thoughtcrime/securesms/WelcomeActivity.java, src/org/thoughtcrime/securesms/notifications/NotificationCenter.java, src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java, src/org/thoughtcrime/securesms/service/GenericForegroundService.java
=> close generic foreground-service when hitting 'cancel' button

src/org/thoughtcrime/securesms/ConversationListFragment.java, src/org/thoughtcrime/securesms/components/reminder/DozeReminder.java, src/org/thoughtcrime/securesms/util/Prefs.java
This fixes, well, one part of https://github.com/deltachat/deltachat-android/issues/1477, also because it was easier to implement only this for now.
=> Already ask the user to disable doze on the first start.

AndroidManifest.xml, src/org/thoughtcrime/securesms/ProfileActivity.java
see commit descriptions for detailed reasoning.
closes #1606
=> hide keyboard when leaving edit-name

src/org/thoughtcrime/securesms/ConversationListFragment.java
this pr adds a timer that redraws the chatlist every minute so that the relative times do update.
closes #1571 again
=> add chatlist time to update relative times

src/com/b44t/messenger/DcEventCenter.java, src/org/thoughtcrime/securesms/BlockedAndShareContactsActivity.java, src/org/thoughtcrime/securesms/ContactSelectionListFragment.java, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/ConversationListFragment.java, src/org/thoughtcrime/securesms/GroupCreateActivity.java, src/org/thoughtcrime/securesms/ProfileActivity.java, src/org/thoughtcrime/securesms/ProfileDocumentsFragment.java, src/org/thoughtcrime/securesms/ProfileGalleryFragment.java, src/org/thoughtcrime/securesms/ProfileSettingsFragment.java, src/org/thoughtcrime/securesms/RegistrationActivity.java, src/org/thoughtcrime/securesms/WelcomeActivity.java, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java, src/org/thoughtcrime/securesms/map/MapDataManager.java, src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java, src/org/thoughtcrime/securesms/qr/QrCodeHandler.java, src/org/thoughtcrime/securesms/qr/QrShowFragment.java
see commit messages for details, closes #1628
=> tweak event handling

jni/dc_wrapper.c, src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/ConversationListFragment.java
=> catch new DC_EVENT_MSGS_NOTICED as needed

src/org/thoughtcrime/securesms/ContactSelectionListFragment.java
fix https://github.com/deltachat/deltachat-android/issues/1639
=> Just catch weird security exception

src/org/thoughtcrime/securesms/ConversationAdapter.java, src/org/thoughtcrime/securesms/ConversationFragment.java
=> Add "go to last seen"

src/com/b44t/messenger/DcChat.java
successor of https://github.com/deltachat/deltachat-core-rust/pull/1965
=> remove unsued starred api

jni/dc_wrapper.c, src/com/b44t/messenger/DcChat.java, src/org/thoughtcrime/securesms/ConversationListItem.java, src/org/thoughtcrime/securesms/ConversationTitleView.java, src/org/thoughtcrime/securesms/MediaPreviewActivity.java, src/org/thoughtcrime/securesms/ProfileActivity.java, src/org/thoughtcrime/securesms/ProfileSettingsFragment.java, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java, src/org/thoughtcrime/securesms/database/model/ThreadRecord.java
=> adapt to new protect-api

res/values/strings.xml, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
there are some more missing eg. for protection-enabled, however, i am pretty sure we will refine the english wording, so it makes some sense to wait until that gets translated.
=> add latest stock strings

res/values/strings.xml
I sorted them and only pushed the ones that are used and not unclear form more info see https://github.com/deltachat/deltachat-desktop/issues/1935
=> add translation strings from desktop

jni/dc_wrapper.c, src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/ConversationListActivity.java
(see https://github.com/deltachat/deltachat-core-rust/pull/1957)
=> Remove updateDeviceChats 

res/layout/quote_view.xml, res/values/strings.xml, src/com/b44t/messenger/DcChat.java, src/com/b44t/messenger/DcMsg.java, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/MyLayoutManager.java, src/org/thoughtcrime/securesms/SetStartingPositionLinearLayoutManager.java, src/org/thoughtcrime/securesms/map/MapActivity.java, src/org/thoughtcrime/securesms/search/SearchFragment.java, src/org/thoughtcrime/securesms/util/AccessibilityUtil.java
See individual commits
fix https://github.com/deltachat/deltachat-android/issues/1653
fix #1654
=> Things that came up in testing group while testing quotes

src/org/thoughtcrime/securesms/util/MediaUtil.java
See https://github.com/deltachat/deltachat-core-rust/pull/1973/
=> Use viewtype instead of mimetype for presenting messages

res/values/strings.xml, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
=> make protection-message translatable

res/values/attrs.xml, src/org/thoughtcrime/securesms/ContactSelectionListFragment.java, src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/util/views/ConversationAdaptiveActionsToolbar.java
=> "forward" should not go to overflow menu, fix #1656

res/menu/conversation_context.xml, src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/util/views/ConversationAdaptiveActionsToolbar.java
this pr just fixes some things in the chat-action-bar, it does not reorder or hide items.
see commits for details.
=> tweak chat-action-bar menu

res/values-de/strings.xml, res/values-it/strings.xml, res/values-nl/strings.xml, res/values-sq/strings.xml, res/values-tr/strings.xml, res/values-zh-rCN/strings.xml, res/values/strings.xml
more than one `%s` needs to be `%1$s`, `%2$s` and so on, cc @Simon-Laux 
already merging this as transifex is also already updated and we want to keep things in sync.
=> placeholders in strings need to be uniquely addressable

src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/ConversationItem.java, src/org/thoughtcrime/securesms/ConversationSwipeAnimationHelper.java
Swipe-to-reply already was disabled for them, now quoting by long-press
is disabled, too.
=> Don't allow quoting system messages and voice message invites

src/org/thoughtcrime/securesms/ConversationListFragment.java
=> Allow forwarding to multiple archived chats

src/org/thoughtcrime/securesms/ConversationFragment.java
=> Copying does not contain the names or "Image - " for single messages

Dockerfile, docker/cargo-config
Having everything in a single file is easier to manage.
=> Move docker/cargo-config into Dockerfile ENV directives

res/layout/contact_selection_list_item.xml, res/layout/conversation_list_item_view.xml, res/layout/conversation_title_view.xml
=> Fix parts of group names missing

CHANGELOG.md, build.gradle, src/org/thoughtcrime/securesms/ConversationListActivity.java
before that gets merged/released, the reference blog-post, https://github.com/deltachat/deltachat-pages/pull/389, should be online (or close to come online :)
=> prep 1.14.1

src/org/thoughtcrime/securesms/ConversationItem.java
=> Remove rounded corners if the message has a quote

jni/dc_wrapper.c, src/com/b44t/messenger/DcMsg.java, src/org/thoughtcrime/securesms/ConversationItem.java
=> Directly show error on msg tap

jni/dc_wrapper.c, src/com/b44t/messenger/DcContext.java
the api is about to be removed from core as well,
see https://github.com/deltachat/deltachat-core-rust/pull/2139
=> remove unused isIoRunning() api

src/org/thoughtcrime/securesms/ProfileActivity.java, src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java
this pr shall be merged to #1643, not to `master`:
this pr are just some minor tweaks i came over while first reviewing-and-play-around round:
- change name of tab and subtitle in profile
- hide "Edit group name and image" for mailing lists
=> minor mailing lists tweaks

jni/dc_wrapper.c, src/com/b44t/messenger/DcContact.java, src/org/thoughtcrime/securesms/ConversationVideochatItem.java, src/org/thoughtcrime/securesms/map/GenerateInfoWindowTask.java, src/org/thoughtcrime/securesms/notifications/NotificationCenter.java
use `dc_contact_get_display_name()` instead
see https://github.com/deltachat/deltachat-core-rust/pull/2165 and https://github.com/deltachat/deltachat-core-rust/issues/2162 for reasoning.
=> adapt to removed dc_contact_get_first_name() api

jni/dc_wrapper.c, res/values/strings.xml, src/com/b44t/messenger/DcChat.java, src/com/b44t/messenger/DcContext.java, src/com/b44t/messenger/DcMsg.java, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationItem.java, src/org/thoughtcrime/securesms/ConversationListAdapter.java, src/org/thoughtcrime/securesms/ConversationListFragment.java, src/org/thoughtcrime/securesms/ConversationListItem.java, src/org/thoughtcrime/securesms/ConversationTitleView.java, src/org/thoughtcrime/securesms/ProfileActivity.java, src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java, src/org/thoughtcrime/securesms/ProfileSettingsFragment.java, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java, src/org/thoughtcrime/securesms/contacts/ContactSelectionListAdapter.java, src/org/thoughtcrime/securesms/notifications/NotificationCenter.java
needs https://github.com/deltachat/deltachat-core-rust/pull/1964 to be merged first.
rebased and submodule-free successor of #1643
=> mailinglists3

src/org/thoughtcrime/securesms/geolocation/LocationBackgroundService.java
Restricts the initial location fix to 2 minutes before user started the location streaming. 
closes #1787
=> Fix cached location fix

res/values-km/strings.xml, res/values/arrays.xml
second part of #1812, closes #1812
=> add Khmer language

res/values/arrays.xml
comparison with ios (that shows english names in xcode) otherwise gets harder and harder ...
for review: do split view.
=> add english language names to comments

jni/dc_wrapper.c, src/com/b44t/messenger/DcContext.java
the number of blocked contacts is just the size of the array returned by getBlockedContacts()
=> remove dead code

src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java
should ideally be merged before https://github.com/deltachat/deltachat-core-rust/pull/2255
I tested key import/export and backup import/export, all work fine.
=> Call stop_io()/start_io() before/after backup export

src/org/thoughtcrime/securesms/LogViewActivity.java, src/org/thoughtcrime/securesms/LogViewFragment.java
these are pretty useful information for debugging.
=> add selected language and rtl to log

src/org/thoughtcrime/securesms/ConversationActivity.java
As discussed in the Testing group
=> Make the upper left back button return to conversation list even if the keyboard is open

jni/dc_wrapper.c
we usually do not use a header in the source files at all
=> remove outdated header

res/drawable/ic_chevron_up.xml, res/drawable/ic_lock.xml, res/drawable/recording_lock_background.xml, res/layout/conversation_input_panel.xml, res/layout/microphone_recorder_view.xml, res/layout/recording_layout.xml, res/values/dimens.xml, res/values/strings.xml, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/components/InputPanel.java, src/org/thoughtcrime/securesms/components/MicrophoneRecorderView.java, src/org/thoughtcrime/securesms/util/ViewUtil.java
allow to lock recording so you don't have to keep your finger pushing
(adapted from Signal code)
=> add lock recording feature

res/drawable/recording_lock_background_dark.xml, res/drawable/recording_lock_background_light.xml, res/layout/microphone_recorder_view.xml, res/values/attrs.xml, res/values/themes.xml
fix compatibility issues with android 4
close #1841
=> don't reference attribute in XML drawable

Dockerfile, README.md
A version where the in-document links work (they don't work in GitHubs `Files changed` view): https://github.com/deltachat/deltachat-android/blob/podman-setup/README.md
=> Explain Podman setup better for new users

src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java
=> show show_emails state in settings summary

res/values-cs/strings.xml, res/values-de/strings.xml, res/values/arrays.xml
https://github.com/deltachat/deltachat-android/commit/25bcd9223dffd3a3437e086372267b0ff80013ac added Czech to local help and we also have a [Czech homepage](https://delta.chat/cs/), but the recent app-translation was missed ...
=> add Czech translation, update translations

assets/help/zh_CN/help.html, docs/release-checklist.md, scripts/create-local-help.sh, src/org/thoughtcrime/securesms/LocalHelpActivity.java, src/org/thoughtcrime/securesms/LogViewFragment.java
targets https://github.com/deltachat/deltachat-pages/issues/432
requires https://github.com/deltachat/deltachat-pages/pull/433 to be merged; otherwise `./script/create-local-help.sh` won't work.
=> Add Chinese to local help

src/org/thoughtcrime/securesms/MediaPreviewActivity.java
=> hidde share button in media preview of draft image or avatar

res/menu/profile_context.xml, src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/ConversationItem.java, src/org/thoughtcrime/securesms/MessageSelectorFragment.java, src/org/thoughtcrime/securesms/ProfileActivity.java, src/org/thoughtcrime/securesms/ProfileDocumentsAdapter.java, src/org/thoughtcrime/securesms/ProfileDocumentsFragment.java, src/org/thoughtcrime/securesms/ProfileGalleryAdapter.java, src/org/thoughtcrime/securesms/ProfileGalleryFragment.java
=> add more options to Gallery and Documents profile tabs

src/org/thoughtcrime/securesms/MessageSelectorFragment.java, src/org/thoughtcrime/securesms/ProfileActivity.java, src/org/thoughtcrime/securesms/ProfileSettingsFragment.java
after struggling to find "the right way to do it" this is the best I could come with.
close #1869
=> finish action mode on tab switch

CHANGELOG.md, build.gradle, scripts/upload-testrun.sh
this uses core53 with the latest sqlx-speedup.
=> prepare 1.19.1 preview release

src/org/thoughtcrime/securesms/components/BorderlessImageView.java
avoid cropping stickers, scale them as appropriate
=> fix sticker scaling

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml
=> make repo's local issue template work

res/layout/conversation_item_update.xml, src/org/thoughtcrime/securesms/ConversationUpdateItem.java
=> show system message status while sending and on errors

src/org/thoughtcrime/securesms/ConversationFragment.java
=> disable "reply privately" in contact requests chat

CHANGELOG.md, build.gradle
a device message is still missing.
=> prepare 1.19.2 preview release

src/org/thoughtcrime/securesms/ConversationActivity.java
=> don't collapse search menu on group changes

CHANGELOG.md, res/values/strings.xml, src/org/thoughtcrime/securesms/ConversationListActivity.java
this is the device message, focusing on email-compat, but trying to not raise too many expectations:
blog-post with much more details ~~is up to come~~ drafted at https://github.com/deltachat/deltachat-pages/pull/439, so please do not merge yet.
cmp. https://github.com/deltachat/deltachat-ios/pull/1195
=> prepare device message

CHANGELOG.md, build.gradle, src/org/thoughtcrime/securesms/ConversationListActivity.java
=> prepare 1.20.0

res/values/strings.xml, src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
follow-up of https://github.com/deltachat/deltachat-core-rust/pull/2310 to make the new string translatable.
=> add missing 'Forwarded' string

src/org/thoughtcrime/securesms/components/InputPanel.java
=> request composer's focus after recording is done

src/org/thoughtcrime/securesms/BaseConversationItem.java, src/org/thoughtcrime/securesms/ConversationItem.java, src/org/thoughtcrime/securesms/ConversationUpdateItem.java
=> highlight system messages in search results

src/org/thoughtcrime/securesms/mms/AttachmentManager.java
=> adapt attached audio's background to theme

src/org/thoughtcrime/securesms/ResolveMediaTask.java
=> use fallback value for fileName

res/values/themes.xml
=> set navigation bar color in dark mode

res/values/strings.xml
fix `res/values/strings.xml` so CI is green again
=> escape apostrophe

CHANGELOG.md, build.gradle
before that can be merged, we have to update the core as or https://github.com/deltachat/deltachat-core-rust/pull/2472
this is a bugfix release, quite an impressive list, special thanks to @adbenitez for taking care!
=> prepare 1.20.5

src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/components/ComposeText.java
see https://developer.android.com/guide/topics/text/image-keyboard
closes #1945
=> send images from 'Image keyboard' as stickers

res/layout/profile_status_item.xml
=> unify appearance of user-generated links

src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java
=> URL-encode file name in openForViewOrShare()

src/org/thoughtcrime/securesms/util/LongClickCopySpan.java
=> don't open chat directly if user clicks in blocked addresses

src/org/thoughtcrime/securesms/WebViewActivity.java
=> handle openpgp4fpr schema in WebView

res/values/strings.xml
this pr shall only contain typo fixes so that they can be pushed without forcing retranslations.
thanks a lot @comradekingu for the suggestions at https://github.com/deltachat/deltachat-android/pull/1960
=> fix some typos

src/org/thoughtcrime/securesms/geolocation/DcLocationManager.java
=> unbind service in stopLocationEngine()

build.gradle, src/org/thoughtcrime/securesms/WebViewActivity.java
=> Apply app/system theme to WebView

src/com/b44t/messenger/DcMsg.java
=> avoid NullPointerException in DcMsg.msgSetToIds()

res/xml/preferences_advanced.xml
this was just forgotten somehow ...
=> use translated string for 'Video chat instance'

src/org/thoughtcrime/securesms/RegistrationActivity.java
related core PR: https://github.com/deltachat/deltachat-core-rust/pull/2112
related issue: https://github.com/deltachat/deltachat-core-rust/issues/2540
=> add yggmail support: allow dotless email address and localhost server

res/layout/conversation_list_activity.xml
=> allow only one line of text in title bar

src/org/thoughtcrime/securesms/audio/AudioSlidePlayer.java
When working on
https://github.com/deltachat/deltachat-android/pull/1975, I noticed that
synchronisation takes quite some time here
=> Speedup returning to chatlist a bit

src/org/thoughtcrime/securesms/ConversationActivity.java
if needed we can do something more specific in the future.
(in did not changed the layout to avoid shifting around constraints)
targets #1990
=> hide question from request panel for now

res/drawable/badge_divider.xml, res/layout/conversation_list_item_view.xml, src/org/thoughtcrime/securesms/ConversationListItem.java
=> Separate request and archive badges

src/org/thoughtcrime/securesms/ConversationListFragment.java
this should fix the race condition mentioned at #2000 (and in the source code)
by synchronizing getters/setters of the booleans.
also, this unifies code to one loop, nothing special is done anymore for the first load; the 100ms sleep is always done after loading, so, first loading is still instant.
@link2xt as you are much more experienced with that - do you still see a race condition here? or was it okay even before?
=> fix potential race condition in chatlist loading

src/org/thoughtcrime/securesms/ConversationListArchiveActivity.java
=> update archived chatlist when contact request is blocked

src/org/thoughtcrime/securesms/WelcomeActivity.java
=> set dynamic theme in welcome activity

CHANGELOG.md, build.gradle
1.21 will be a testing release.
if possible, i'd like to get https://github.com/deltachat/deltachat-android/pull/2007 in before merging.
=> prepare 1.21.0

CHANGELOG.md, build.gradle
this will again be a testrun release.
=> prepare 1.21.1 testrun 🏃

src/org/thoughtcrime/securesms/ConversationListFragment.java
=> avoid NullPointerException in loadChatlist()

src/org/thoughtcrime/securesms/ApplicationContext.java, src/org/thoughtcrime/securesms/ApplicationPreferencesActivity.java, src/org/thoughtcrime/securesms/BlockedAndShareContactsActivity.java, src/org/thoughtcrime/securesms/ConnectivityActivity.java, src/org/thoughtcrime/securesms/ContactSelectionListFragment.java, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/ConversationListFragment.java, src/org/thoughtcrime/securesms/GroupCreateActivity.java, src/org/thoughtcrime/securesms/ProfileActivity.java, src/org/thoughtcrime/securesms/ProfileDocumentsFragment.java, src/org/thoughtcrime/securesms/ProfileGalleryFragment.java, src/org/thoughtcrime/securesms/ProfileSettingsFragment.java, src/org/thoughtcrime/securesms/RegistrationActivity.java, src/org/thoughtcrime/securesms/WelcomeActivity.java, src/org/thoughtcrime/securesms/connect/DcEventCenter.java, src/org/thoughtcrime/securesms/map/MapDataManager.java, src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java, src/org/thoughtcrime/securesms/qr/QrCodeHandler.java, src/org/thoughtcrime/securesms/qr/QrShowFragment.java
This was in an attempt to find the cause for #2026. I didn't succeed,
but this is an improvement, anyway.
=> Add some @NonNull annotations, remove unused method

CHANGELOG.md, build.gradle
release-candidate with brand-new core59 engine ⚙️⚙️⚙️
=> prepare 1.22.0

res/values/strings.xml
pull in most recent strings from https://github.com/deltachat/deltachat-desktop/blob/master/_locales/_untranslated_en.json
i left out two strings that are hard to translate/explain and more debugging/testing information and will not last in that form anyway (and are probably outdated before translated significantly :)
=> pull in translatable/lasting strings from desktop

res/values/strings.xml, src/org/thoughtcrime/securesms/connect/DcHelper.java
this adds translations recently needed by the core.
=> update core translations

res/values/arrays.xml
at some point, the key could be renamed to just `.all`, but well, that is some work on all platforms. also, we have several such weird keys, maybe sth. for a cleanup when we all sit together and everything else is done ;) at least, new ones are nicer most of the time :)
=> prefer 'All' over 'No Limit'

src/com/b44t/messenger/DcChat.java, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/ConversationItem.java, src/org/thoughtcrime/securesms/ConversationTitleView.java, src/org/thoughtcrime/securesms/ProfileActivity.java, src/org/thoughtcrime/securesms/ProfileSettingsFragment.java, src/org/thoughtcrime/securesms/components/AvatarImageView.java, src/org/thoughtcrime/securesms/notifications/NotificationCenter.java, src/org/thoughtcrime/securesms/recipients/Recipient.java
as discussed at https://github.com/deltachat/deltachat-android/pull/2060#discussion_r717901663
=> rename isGroup() to isMultiUser()

README.md, androidTest/com/b44t/messenger/EnterChatsBenchmark.java, androidTest/com/b44t/messenger/OnboardingTest.java, androidTest/com/b44t/messenger/SharingTest.java, androidTest/com/b44t/messenger/TestUtils.java, build.gradle, src/org/thoughtcrime/securesms/connect/AccountManager.java
When fixing https://github.com/deltachat/deltachat-android/issues/2040, I'll try to create a failing test first. This PR here is the foundation for this.
=> Add very basic onboarding and sharing test

src/org/thoughtcrime/securesms/ProfileActivity.java, src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java, src/org/thoughtcrime/securesms/ProfileSettingsFragment.java
=> Disable group editing actions if user can't edit group (ex. self not in group)

res/layout/selected_recipient_list_item.xml, src/org/thoughtcrime/securesms/util/SelectedRecipientsAdapter.java
=> show verified-checkmark in memberlist in group creation

src/org/thoughtcrime/securesms/ConversationListActivity.java
=> make toolbar's avatar visible if needed

CHANGELOG.md, build.gradle
just bumping the version, main change is core63. 1.24.0 was never released but the version number is burned by nightlies etc :)
=> prepare 1.24.1

src/org/thoughtcrime/securesms/util/SaveAttachmentTask.java
=> fix NullPointerException in SaveAttachmentTask.onPostExecute()

CHANGELOG.md, build.gradle
ios counterpart: https://github.com/deltachat/deltachat-ios/pull/1388
=> prepare 1.24.3

.github/workflows/artifacts.yml, .github/workflows/preview-apk.yml
remove deprecated action and make the generated APK more visible
=> CI: fix and improve apk preview workflows

CHANGELOG.md, build.gradle
ios counterpart: https://github.com/deltachat/deltachat-ios/pull/1390
=> prepare 1.24.4

res/values/strings.xml, src/org/thoughtcrime/securesms/connect/DcHelper.java
fix https://github.com/deltachat/deltachat-core-rust/issues/2793
Also see https://github.com/deltachat/deltachat-core-rust/pull/2805
=> Don't set draft after creating group, instead improve group creation hint

res/layout/conversation_list_activity.xml
Fix https://github.com/deltachat/deltachat-android/issues/2127
=> Fix layout bug in chatlist title

build.gradle, src/org/thoughtcrime/securesms/map/MapActivity.java, src/org/thoughtcrime/securesms/map/MapDataManager.java
Turns out it's pretty easy to switch to Maplibre, except obviously if there will be problems that didn't turn up yet. My gut feeling is that it should be fine.
Supersedes https://github.com/deltachat/deltachat-android/pull/2141 (except if we say that we don't want to switch to Maplibre now but want a quick fix)
Fix #2140
=> Switch from Mapbox to Maplibre

jni/dc_wrapper.c, res/values/strings.xml, src/com/b44t/messenger/DcContact.java, src/org/thoughtcrime/securesms/ConversationTitleView.java, src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java, src/org/thoughtcrime/securesms/util/DateUtils.java
=> Display last-seen info in profile

build.gradle, jni/dc_wrapper.c, res/layout/qr_show_fragment.xml, src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/qr/QrShowFragment.java
related core pull request: https://github.com/deltachat/deltachat-core-rust/pull/2815
=> [WIP] use the new SVG QR images generated in core

res/values/strings.xml, src/org/thoughtcrime/securesms/connect/DcHelper.java
see commit messages for details
successor of https://github.com/deltachat/deltachat-android/pull/2138
=> "scan qr code" wordings

jni/dc_wrapper.c, src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/WelcomeActivity.java, src/org/thoughtcrime/securesms/connect/DcEventCenter.java, src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java, src/org/thoughtcrime/securesms/qr/QrCodeHandler.java
the old `getCapturedError()` has races, see https://github.com/deltachat/deltachat-core-rust/issues/2787
better merge that after 1.24 is finally in the stores.
closes #2108
=> use `dc_get_last_error()` api

src/org/thoughtcrime/securesms/contacts/avatars/GeneratedContactPhoto.java
to make it fit with the new QRs and also that is how they are shown in Desktop
=> make avatar letter bold and transform it to uppercase

CHANGELOG.md, build.gradle, docs/release-checklist.md
maybe we should get https://github.com/deltachat/deltachat-android/pull/2157 in, however, i am not deep in these things, maybe  @Hocuri can have a look at it. however, it seem not to be that critical and is probably not a regression.
=> bump to 1.26.2

src/org/thoughtcrime/securesms/ConversationActivity.java
=> avoid NullPointerException when selecting thumbnail image

res/values/strings.xml
that string is missing somehow.
currently needed for desktop, https://github.com/deltachat/deltachat-desktop/pull/2455#discussion_r765261269
=> add 'Download failed' string

res/layout/conversation_fragment.xml
this bit was forgotten in https://github.com/deltachat/deltachat-android/pull/2165
=> update layout placeholder

res/values-bg/strings.xml, res/values/arrays.xml
this is just appearing on transifex, already quite lots of strings translated :)
once this is merged here, we should file corresponding pr/issues for ios/desktop.
thanks a lot, Jivko!
=> add Bulgarian translation

res/xml/preferences_advanced.xml, src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
=> remove inbox_watch and mvbox_watch options from advanced settings

jni/dc_wrapper.c, src/com/b44t/messenger/DcMsg.java, src/org/thoughtcrime/securesms/ConversationFragment.java
=> move up when tapping webxdc info messages

res/values/strings.xml, res/xml/preferences_advanced.xml, src/org/thoughtcrime/securesms/WebxdcActivity.java, src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java, src/org/thoughtcrime/securesms/util/Prefs.java
=> add "developer mode" preference

CHANGELOG.md, build.gradle
fixing the backup-import-issue introduced in 1.27.0
=> prepare 1.27.1

src/org/thoughtcrime/securesms/WebxdcActivity.java
closes #2204 
did not test that yet ...
=> avoid caching resources between webxdc apps

res/raw/webxdc.js
cmp https://github.com/deltachat/webxdc-dev/pull/17
=> adapt to new webxdc api

src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationItem.java, src/org/thoughtcrime/securesms/components/WebxdcView.java, src/org/thoughtcrime/securesms/mms/AttachmentManager.java
see commit messages for details.
closes #2211
=> tweak default summaries

res/values/strings.xml, res/xml/preferences_advanced.xml, src/org/thoughtcrime/securesms/connect/DcHelper.java, src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
Depends on ~~https://github.com/deltachat/deltachat-core-rust/pull/3014~~ https://github.com/deltachat/deltachat-core-rust/pull/3028
=> Add OnlyFetchMvbox option

CHANGELOG.md, build.gradle
this updates the translations :)
i'll push this version to the stores then ...
=> prepare 1.28.1

jni/dc_wrapper.c, res/raw/webxdc.js, src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/WebxdcActivity.java
ui part of https://github.com/deltachat/deltachat-core-rust/pull/3081
=> adapt js to new webxdc-update-api

README.md
@rezazarchi do you think this would have helped with #2230 ?
=> Better build instructions in Readme

src/org/thoughtcrime/securesms/WebxdcActivity.java
=> add account id to webxdc-fake-url

src/org/thoughtcrime/securesms/components/emoji/EmojiEditText.java
=> Do not disable fullscreen keyboard

res/layout/conversation_list_activity.xml, res/values/styles.xml
=> use the same size for the app title and conversation title

res/raw/webxdc.js
and show the deprecation notice of `getAllUpdates` to the user with console.error
=> fix setting `update_listener`

androidTest/com/b44t/messenger/uibenchmarks/EnterChatsBenchmark.java
This will make it easier to benchmark how much our speed efforts improve.
Unfortunately, there still is no benchmark framework used, so all statistics have to be done by hand in LibreOffice. This e.g. looks like this:
=> Create enterFilledChat and createAndEnterEmptyChats benchmarks

src/org/thoughtcrime/securesms/util/MediaUtil.java
=> avoid null mime type

src/org/thoughtcrime/securesms/components/QuoteView.java
previously the file/document icon was show
=> show webxdc icon in quotes

src/org/thoughtcrime/securesms/notifications/NotificationCenter.java, src/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java
=> fix sound notifications, allow to set to "silent"

src/org/thoughtcrime/securesms/BaseActionBarActivity.java, src/org/thoughtcrime/securesms/connect/DirectShareUtil.java
See individual commit messages.
=> Very small speed improvements

src/org/thoughtcrime/securesms/search/SearchFragment.java, src/org/thoughtcrime/securesms/search/SearchViewModel.java
=> Update search results when the chatlist changes

res/layout/profile_document_item.xml, res/layout/webxdc_compact_view.xml, res/values/attrs.xml, src/org/thoughtcrime/securesms/ProfileDocumentsAdapter.java, src/org/thoughtcrime/securesms/ProfileDocumentsFragment.java, src/org/thoughtcrime/securesms/components/WebxdcView.java
and allow to open webxdc directly from the list in the Docs tab
=> improve display of webxdc items in Docs tab

res/values/strings.xml, src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
=> Warn when enabling config "only_fetch_mvbox"

src/org/thoughtcrime/securesms/connect/DcHelper.java
successor of https://github.com/deltachat/deltachat-core-rust/pull/3222 , see there for details.
=> update core stock strings

jni/dc_wrapper.c, res/menu/conversation_context.xml, res/values/strings.xml, src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/util/views/ConversationAdaptiveActionsToolbar.java
requires https://github.com/deltachat/deltachat-core-rust/pull/3238 to be merged before.
https://github.com/deltachat/deltachat-core-rust/pull/3238 is pretty limited, however, even if we revamp most of the internals, the ffi and the UI will probably stay the same - a "Resend" button seems to have advantages in many situations.
see commit messages for some details and reasoning.
=> resend messages

jni/dc_wrapper.c, src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/RegistrationActivity.java
see https://github.com/deltachat/deltachat-core-rust/pull/3256 for details, this pr only changes the api call so that everything is as before. 
closes https://github.com/deltachat/deltachat-android/issues/2282
=> use new dc_provider_new_from_email_with_dns() api

CHANGELOG.md, build.gradle, res/values/strings.xml, src/org/thoughtcrime/securesms/ConversationListActivity.java
before merging, i think, we should get https://github.com/deltachat/deltachat-core-rust/pull/3281 in. EDIT: done :)
=> prepare 1.30.0

src/org/thoughtcrime/securesms/ApplicationContext.java
=> set translations before starting I/O

res/values/strings.xml
relates to https://github.com/deltachat/deltachat-ios/pull/1570#pullrequestreview-964380090 and https://github.com/deltachat/deltachat-ios/pull/1571
=> iOS strings: add accessibility hint for the connectivity details

AndroidManifest.xml, src/org/thoughtcrime/securesms/WebxdcActivity.java, src/org/thoughtcrime/securesms/components/WebxdcView.java, src/org/thoughtcrime/securesms/util/JsonUtils.java
requires current core-master checked out, otherwise, `document` is just never set.
closes https://github.com/deltachat/deltachat-android/issues/2297
=> Webxdc document names

res/values/strings.xml
This pull request will add changes that will be explained on each commit.
=> Add missing translations

docs/f-droid.md
see https://github.com/deltachat/deltachat-android/pull/2303#issuecomment-1137014443
=> update some f-droid links and information

res/values/strings.xml
related ﻿desktop pr: https://github.com/deltachat/deltachat-desktop/pull/2794
=> add desktop strings

src/org/thoughtcrime/securesms/WebxdcActivity.java, src/org/thoughtcrime/securesms/connect/DcHelper.java, src/org/thoughtcrime/securesms/providers/PersistentBlobProvider.java, src/org/thoughtcrime/securesms/util/MediaUtil.java
fix #2306
Credits & thanks to @webratte for finding this bug and [reminding](https://github.com/deltachat/deltachat-android/issues/2306#issuecomment-1172358177) me of it!
=> Also identify media type if there are unknown characters in the filename

src/org/thoughtcrime/securesms/WebxdcActivity.java
=> allow to open mailto links inside webxdc documents

CHANGELOG.md, build.gradle, src/org/thoughtcrime/securesms/ConversationListActivity.java
this will be a testrun release.
=> prepare 1.31.0

res/values/strings.xml
I want to look over all the English strings. Here are just a few, should we try merging a small amount to see what happens in Transifex (in terms of causing / minimizing notifications for other languages) first? Or should I go through the whole file?
=> Revise English

res/values/strings.xml
taken from https://github.com/deltachat/deltachat-android/pull/2343, thanks @OzancanKaratas
=> fix upper lowercase

res/drawable/ic_circle_status.xml, res/layout/avatar_view.xml, res/layout/contact_selection_list_item.xml, res/layout/conversation_list_item_view.xml, res/layout/conversation_title_view.xml, src/com/b44t/messenger/DcContact.java, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationListItem.java, src/org/thoughtcrime/securesms/ConversationTitleView.java, src/org/thoughtcrime/securesms/components/AvatarView.java, src/org/thoughtcrime/securesms/contacts/ContactSelectionListItem.java, src/org/thoughtcrime/securesms/recipients/Recipient.java, src/org/thoughtcrime/securesms/util/DateUtils.java
<details>
<summary>Screenshots</summary>
</details>
=> add "seen recently" indicator

AndroidManifest.xml, src/org/thoughtcrime/securesms/WelcomeActivity.java
=> handle DCACCOUNT and DCLOGIN schemes on new intents

src/org/thoughtcrime/securesms/ConversationActivity.java
this should solve the issue reported by @gerryfrancis in the testing group
=> load contact from database before calling wasSeenRecently()

src/org/thoughtcrime/securesms/ProfileActivity.java, src/org/thoughtcrime/securesms/ProfileDocumentsFragment.java
picks up the idea from https://github.com/deltachat/deltachat-android/pull/2386#pullrequestreview-1116030385
=> add 'Audio' tab to profile

res/layout/avatar_view.xml
=> use Start/End instead of Left/Right in avatar layout

CHANGELOG.md, build.gradle
a bugfix release.
this should be rebased+merged **after** https://github.com/deltachat/deltachat-android/pull/2407
=> prepare 1.34.2

CHANGELOG.md, build.gradle
this [fixes bugs](https://github.com/deltachat/deltachat-android/pull/2411) for android12 introduced with [1.34.2](https://github.com/deltachat/deltachat-android/pull/2406)
=> prepare 1.34.3

res/values/strings.xml
this came out of transifex discussions, depending on the language there may be quite different words that need this clarification.
=> clarify meaning of 'left'

src/org/thoughtcrime/securesms/LogViewFragment.java
that may get handy esp. if the code is patched, cmp https://github.com/deltachat/deltachat-android/issues/2426#issuecomment-1315393104
=> add versionCode to debug info

CHANGELOG.md, build.gradle
this mainly updates to recent core with several fixes
=> prepare 1.34.7

res/menu/archived_list.xml, res/values/strings.xml, src/org/thoughtcrime/securesms/ConversationListArchiveActivity.java
as we have the unread counter there now,
we should have an easy way to reset it.
requires https://github.com/deltachat/deltachat-core-rust/pull/3919 to be merged first.
=> add function 'mark all as read' to archive

src/org/thoughtcrime/securesms/ConversationListActivity.java, src/org/thoughtcrime/securesms/ConversationListArchiveActivity.java
this is similar to opening a chat and feels more natural. settings/connectivity/help etc. still appear from the bottom as being "something little different".
=> fade left/right animation when opening the archive

CHANGELOG.md, build.gradle, metadata/en-US/changelogs/6454.txt, metadata/en-US/changelogs/6464.txt, src/org/thoughtcrime/securesms/ConversationListActivity.java
=> prepare 1.34.10

res/layout/registration_activity.xml, src/org/thoughtcrime/securesms/RegistrationActivity.java, src/org/thoughtcrime/securesms/connect/DcHelper.java
closes #2405
closes #2234
closes #406
(also related: #1066)
=> add socks5 settings to registration activity

res/raw/webxdc_wrapper.html, src/org/thoughtcrime/securesms/WebxdcActivity.java
This fixes all the checks in the `test webxdc`, see the group on Delta Chat
=> Webxdc fixes

src/org/thoughtcrime/securesms/WebxdcActivity.java
i'd like to have some more meaningful names, btw; this is just the fix :)
and yes, we should have a test for this roundtrip, cmp https://github.com/webxdc/webxdc-test/issues/4
=> fix receiving updates during runtime

CHANGELOG.md, build.gradle, scripts/upload-beta.sh
=> prepare 1.34.13

docs/release-checklist.md
refine and update release checklist and add things that were done more implicitly before.
this pr is only about documenting the current status quo and sharing some more knowledge.
=> refine release checklist

CHANGELOG.md, README.md, build.gradle, docs/f-droid.md, scripts/codespell.sh, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/connect/KeepAliveService.java, src/org/thoughtcrime/securesms/geolocation/LocationBackgroundService.java, src/org/thoughtcrime/securesms/imageeditor/renderers/MultiLineTextRenderer.java, src/org/thoughtcrime/securesms/map/DCMapFragment.java, src/org/thoughtcrime/securesms/mms/AttachmentManager.java, src/org/thoughtcrime/securesms/notifications/NotificationCenter.java, src/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java, src/org/thoughtcrime/securesms/video/recode/VideoRecoder.java
inspired by https://github.com/deltachat/deltachat-core-rust/pull/4103
=> add codespell, fix typos

src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java
=> Removed create group button from contact info screen

res/layout/qr_show_fragment.xml, src/org/thoughtcrime/securesms/qr/QrShowFragment.java
the current "QR Show" fragment looks a bit ugly/empty with the white background, this PR sets the nicer default chat background
=> set background image for QrShowFragment

jni/dc_wrapper.c, res/layout/conversation_item_update.xml, src/com/b44t/messenger/DcMsg.java, src/org/thoughtcrime/securesms/ConversationUpdateItem.java
=> add app icon to webxdc info messages

src/org/thoughtcrime/securesms/accounts/AccountSelectionListFragment.java
=> remove notifications from closed accounts

CHANGELOG.md, build.gradle, res/values/strings.xml, src/org/thoughtcrime/securesms/ConversationListActivity.java
=> prepare 1.36

AndroidManifest.xml, res/values-night/themes_splash.xml, res/values/themes_splash.xml
=> start with light/dark theme depending on system theme

src/org/thoughtcrime/securesms/WebxdcActivity.java
We use our own DNS implementation everywhere, this is not needed.
=> Set "X-DNS-Prefetch-Control: off" header

src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/qr/QrCodeHandler.java
depends on https://github.com/deltachat/deltachat-core-rust/pull/3492
=> set draft from mailto data in QR

src/org/thoughtcrime/securesms/WebViewActivity.java
this is what i did to check out the effort, works on first tests, alternative to https://github.com/deltachat/deltachat-android/pull/2574
@adbenitez feel free to commit on top of this pr or close it
=> implement onShowFileChooser based on AdvancedWebView

res/raw/webxdc.js, src/org/thoughtcrime/securesms/WebxdcActivity.java, src/org/thoughtcrime/securesms/connect/DcHelper.java
=> add webxdc.sendToChat() API

res/raw/webxdc.js
cleaning up a bit, see commit messages for details. came over that while working on https://github.com/deltachat/deltachat-ios/pull/1886 ...
=> unify and shorten sendToChat() errors

res/raw/webxdc.js
=> add webxdc.importFiles() API

CHANGELOG.md, build.gradle, src/org/thoughtcrime/securesms/ConversationListActivity.java
closes https://github.com/deltachat/deltachat-android/issues/2582
https://github.com/deltachat/deltachat-ios/pull/1897
=> prepare 1.37.0

src/org/thoughtcrime/securesms/WebViewActivity.java, src/org/thoughtcrime/securesms/WebxdcActivity.java
successor of https://github.com/deltachat/deltachat-android/pull/2575
close #2585
=> move the file chooser implementation to WebxdcActivity class

build.gradle
fixes #1915 
likely also fixes #2439
=> update dependency com.github.penfeizhou.android.animation:glide-plugin

res/values/strings.xml
this is needed for https://github.com/deltachat/deltachat-desktop/pull/3271 and https://github.com/deltachat/deltachat-ios/pull/1904
=> add select_chat string

res/values/themes.xml
this somehow fixes: https://github.com/webxdc/calendar/issues/74
but I don't understand that properties, or the impact in other views, the removal of that line, at first glance after some testing it seems to have no adverse effects,
@Hocuri, @r10s  maybe you can tell
=> try to fix popup/dialog background in webview

build.gradle, src/org/thoughtcrime/securesms/CreateProfileActivity.java, src/org/thoughtcrime/securesms/GroupCreateActivity.java, src/org/thoughtcrime/securesms/profiles/AvatarHelper.java, src/org/thoughtcrime/securesms/scribbles/ImageEditorFragment.java, src/org/thoughtcrime/securesms/scribbles/ScribbleActivity.java
also update old android-crop dependency needed for SDK <19
close #1566
=> use image editor for avatar selection when possible

README.md
On my first time build on this project (or any open source GitHub project) I made some mistakes. This PR tries to clarify the documentation such that the next person might not make the same mistakes.
=> Propose clarification based on first time build experience

src/org/thoughtcrime/securesms/WebxdcActivity.java
csp taken from https://github.com/deltachat/deltachat-desktop/pull/3322 - @adbenitez can you please check if "Audio Dash" works for you now?
=> webxdc: allow media from blob: and data:

androidTest/com/b44t/messenger/uitests/offline/SharingTest.java, src/org/thoughtcrime/securesms/NewConversationActivity.java, src/org/thoughtcrime/securesms/ShareActivity.java, src/org/thoughtcrime/securesms/util/MailtoUtil.java
=> improve mailto Intent handling in ShareActivity

res/values/strings.xml
needed for https://github.com/deltachat/deltachat-desktop/pull/3362
=> add 'Close Window' string needed for desktop

res/values-land/attrs.xml, res/values-sw600dp/attrs.xml, res/values/attrs.xml, src/org/thoughtcrime/securesms/WebxdcActivity.java
=> improve landscape mode for webxdc

src/org/thoughtcrime/securesms/WebxdcActivity.java
=> fix title refreshing on webxdc document name changes

src/org/thoughtcrime/securesms/ConversationFragment.java
=> only jump to message if info message is from webxdc

src/org/thoughtcrime/securesms/ConversationListActivity.java, src/org/thoughtcrime/securesms/ShareActivity.java, src/org/thoughtcrime/securesms/WebxdcActivity.java, src/org/thoughtcrime/securesms/connect/DcHelper.java, src/org/thoughtcrime/securesms/util/RelayUtil.java
=> add more context to dialog title shown after sendToChat()

src/org/thoughtcrime/securesms/audio/AudioSlidePlayer.java
=> keep screen on while playing voice message

src/org/thoughtcrime/securesms/ApplicationPreferencesActivity.java, src/org/thoughtcrime/securesms/BaseActionBarActivity.java, src/org/thoughtcrime/securesms/BlockedAndShareContactsActivity.java, src/org/thoughtcrime/securesms/ContactSelectionActivity.java, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationListActivity.java, src/org/thoughtcrime/securesms/ConversationListArchiveActivity.java, src/org/thoughtcrime/securesms/CreateProfileActivity.java, src/org/thoughtcrime/securesms/GroupCreateActivity.java, src/org/thoughtcrime/securesms/LogViewActivity.java, src/org/thoughtcrime/securesms/MediaPreviewActivity.java, src/org/thoughtcrime/securesms/PassphraseRequiredActionBarActivity.java, src/org/thoughtcrime/securesms/ProfileActivity.java, src/org/thoughtcrime/securesms/ShareActivity.java, src/org/thoughtcrime/securesms/WebViewActivity.java, src/org/thoughtcrime/securesms/preferences/ChatBackgroundActivity.java, src/org/thoughtcrime/securesms/qr/BackupTransferActivity.java, src/org/thoughtcrime/securesms/qr/QrActivity.java, src/org/thoughtcrime/securesms/qr/RegistrationQrActivity.java, src/org/thoughtcrime/securesms/util/DynamicLanguage.java
=> set current locale on orientation changes

res/values/strings.xml, res/xml/preferences_advanced.xml, src/org/thoughtcrime/securesms/reactions/ReactionsConversationView.java
see commit messages for details
=> tweak translations

res/layout/reaction_recipient_item.xml, res/layout/reactions_details_fragment.xml, res/values/strings.xml, src/org/thoughtcrime/securesms/BindableConversationItem.java, src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/ConversationItem.java, src/org/thoughtcrime/securesms/reactions/ReactionRecipientItem.java, src/org/thoughtcrime/securesms/reactions/ReactionRecipientsAdapter.java, src/org/thoughtcrime/securesms/reactions/ReactionsDetailsFragment.java
=> display reactions details

res/values/strings.xml, src/org/thoughtcrime/securesms/mms/AttachmentManager.java, src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java, src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java
=> allow to select key to import instead of using Download folder

res/layout/reactions_pill.xml, src/org/thoughtcrime/securesms/reactions/ReactionsConversationView.java
=> display text in reaction pill

src/org/thoughtcrime/securesms/WelcomeActivity.java
this was overseen at #2671
closes #2682
=> fix welcome title bar

src/org/thoughtcrime/securesms/components/AudioView.java
=> pause background music when playing voice messages

src/org/thoughtcrime/securesms/ConversationListFragment.java
closes https://github.com/deltachat/deltachat-android/issues/2029, see #2029 for details
=> improve chatlist timers and add logging

src/org/thoughtcrime/securesms/mms/AttachmentManager.java, src/org/thoughtcrime/securesms/video/recode/VideoRecoder.java
closes #1358 by picking up ideas from #1358
this pr does not translate error messages, let's first settle them in english by practise ... also, which ones really appear in the wild
=> improve video error handling and logging

src/org/thoughtcrime/securesms/connect/DcHelper.java, src/org/thoughtcrime/securesms/util/FileUtils.java
=> sanitize filename before creating it in the blobs dir

src/com/b44t/messenger/DcChat.java, src/com/b44t/messenger/DcChatlist.java, src/com/b44t/messenger/DcContext.java, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationListAdapter.java, src/org/thoughtcrime/securesms/recipients/Recipient.java, src/org/thoughtcrime/securesms/search/model/SearchResult.java
this is needed to avoid refactoring of Recipient, @adbenitez feel free to merge or to close as needed
=> add DcChat.getAccountId()

src/org/thoughtcrime/securesms/ConversationListFragment.java, src/org/thoughtcrime/securesms/recipients/Recipient.java
- when switching accounts by clicking in a notification, it sometimes happens that the chatlist is not refreshed
- notification sometimes display wrong avatar
close #2611
=> fix account switching issues

res/menu/profile_context.xml, src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/MessageSelectorFragment.java, src/org/thoughtcrime/securesms/ProfileDocumentsFragment.java, src/org/thoughtcrime/securesms/ProfileGalleryFragment.java, src/org/thoughtcrime/securesms/ProfileSettingsFragment.java
=> allow to resend attachments from chat profile

src/org/thoughtcrime/securesms/scribbles/ScribbleActivity.java
=> use DynamicNoActionBarTheme in ScribbleActivity

src/org/thoughtcrime/securesms/WebxdcActivity.java
=> switch account if needed when opening webxdc app from home shortcut

src/org/thoughtcrime/securesms/ApplicationContext.java, src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/preferences/AppearancePreferenceFragment.java, src/org/thoughtcrime/securesms/preferences/ChatBackgroundActivity.java, src/org/thoughtcrime/securesms/util/Prefs.java
=> allow to set chat background per-account

res/values/strings.xml, src/org/thoughtcrime/securesms/ConversationListActivity.java
stop adding 1.38 device message, remove 1.36 device message strings
=> remove old device messages

res/layout/audio_view.xml, src/org/thoughtcrime/securesms/ConversationItem.java, src/org/thoughtcrime/securesms/ProfileDocumentsAdapter.java, src/org/thoughtcrime/securesms/components/AudioView.java
also allow to long-press in play button to select message
close #2725
=> allow to properly click in audio messages in multi-select mode

res/layout/registration_activity.xml
=> registration screen: make checkbox use acent color

src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
=> use more permissive mime type in key selection

src/org/thoughtcrime/securesms/ConversationListFragment.java
=> avoid NullPointerException in ConversationListFragment.updateReminders()

res/values-night/colors.xml, res/values/themes.xml
=> tweak action bar theme for dark mode

src/org/thoughtcrime/securesms/ConversationListAdapter.java, src/org/thoughtcrime/securesms/search/SearchListAdapter.java
=> update dcContext in ConversationListAdapter.changeData()

res/layout/conversation_fragment.xml, res/values/colors.xml, res/values/text_styles.xml, res/xml/preferences_advanced.xml, src/com/b44t/messenger/rpc/Rpc.java, src/org/thoughtcrime/securesms/ConversationAdapter.java, src/org/thoughtcrime/securesms/ConversationFragment.java, src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java, src/org/thoughtcrime/securesms/reactions/AddReactionView.java
next steps, roughly:
closes #2402
=> sending reactions

jni/dc_wrapper.c, src/com/b44t/messenger/DcAccounts.java, src/org/thoughtcrime/securesms/ApplicationContext.java, src/org/thoughtcrime/securesms/connect/DcHelper.java
These commits were left in the `feat/verified-1to1` branch, and they adapt DC Android to core-rust main.
I created this PR here so that we can merge it when core-rust main becomes the new stable.
=> Commits that adapt to the next core version

res/values-tr/strings.xml
(it is added by transifex ui,
however, the translator seems to use a different tool that messed that up)
=> fix missing abostrophe

src/org/thoughtcrime/securesms/qr/QrShowFragment.java
=> fix avatar letter misplacement

res/menu/qr_show.xml, src/org/thoughtcrime/securesms/qr/QrActivity.java, src/org/thoughtcrime/securesms/qr/QrShowActivity.java, src/org/thoughtcrime/securesms/qr/QrShowFragment.java
=> allow to deactivate QR codes

src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java
only address is easily confusing, only name may be tricked :)
cmp https://github.com/deltachat/deltachat-ios/pull/1949
=> show verifier name+address

res/values/strings.xml
we do no longer regard them as experimental.
they are here to stay.
=> 'verified chats' are no longer experimental

res/values/strings.xml
it does not really make sense to say what a member needs to be to become a member :)
=> an added contact becomes a member

res/layout/group_create_activity.xml, src/org/thoughtcrime/securesms/GroupCreateActivity.java
=> remove QR button in group creation screen

res/values/strings.xml, src/org/thoughtcrime/securesms/ContactSelectionListFragment.java, src/org/thoughtcrime/securesms/contacts/ContactSelectionListItem.java
=> see all contact list in verified groups "add member", explain why they can't be added

res/values/colors.xml, res/values/strings.xml, src/com/b44t/messenger/DcContact.java, src/org/thoughtcrime/securesms/GroupCreateActivity.java, src/org/thoughtcrime/securesms/NewConversationActivity.java, src/org/thoughtcrime/securesms/connect/DcContactsLoader.java, src/org/thoughtcrime/securesms/contacts/ContactSelectionListAdapter.java, src/org/thoughtcrime/securesms/contacts/ContactSelectionListItem.java
=> offer to create verified group

res/layout/group_create_activity.xml, res/layout/selected_contact_list_item.xml
=> improve create group screen (part 2)

src/org/thoughtcrime/securesms/GroupCreateActivity.java
=> fix bugs in GroupCreateActivity

res/values-night/colors.xml, src/org/thoughtcrime/securesms/accounts/AccountSelectionListItem.java
=> make "+ add account" bold and tweak button color in dark mode

res/values/strings.xml
checked with `./scripts/grep-string.sh` on all three main platforms
after merging, strings should be pushed+pulled
=> remove unused strings 

src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java, src/org/thoughtcrime/securesms/ProfileSettingsFragment.java
counterpart of https://github.com/deltachat/deltachat-ios/pull/1955
see https://github.com/deltachat/deltachat-core-rust/pull/4922 for reasoning
=> calculate 'introduced by' string accordingly

res/values/arrays.xml
=> remove 40KB option from download limits

res/values/dimens.xml, src/org/thoughtcrime/securesms/components/KeyboardAwareLinearLayout.java, src/org/thoughtcrime/securesms/util/ViewUtil.java
=> update KeyboardAwareLinearLayout from upstream

CHANGELOG.md, build.gradle
before merging this pr, #2817 and #2825 should be merged
=> prepare 1.41.4

AndroidManifest.xml, res/layout/new_contact_activity.xml, res/menu/new_contact.xml, src/org/thoughtcrime/securesms/BlockedContactsActivity.java, src/org/thoughtcrime/securesms/ContactSelectionListFragment.java, src/org/thoughtcrime/securesms/NewConversationActivity.java, src/org/thoughtcrime/securesms/connect/DcContactsLoader.java, src/org/thoughtcrime/securesms/contacts/ContactSelectionListAdapter.java, src/org/thoughtcrime/securesms/contacts/NewContactActivity.java
=> add new-contact activity

src/org/thoughtcrime/securesms/ConversationActivity.java
=> hide toolbar onStop and show it again onResume to avoid bug with keyboard

CHANGELOG.md, build.gradle
version needs to be bumped and core needs to be updated, but the CHANGLOG can already be reviewed
=> prepare 1.41.6

res/values/strings.xml, src/org/thoughtcrime/securesms/connect/DcHelper.java
=> Add stock string 173 (Member added)

CHANGELOG.md, build.gradle
this mainly pulls in core 1.131.1
=> prepare 1.41.7

src/org/thoughtcrime/securesms/ContactSelectionListFragment.java, src/org/thoughtcrime/securesms/LocalHelpActivity.java, src/org/thoughtcrime/securesms/connect/DcHelper.java, src/org/thoughtcrime/securesms/qr/BackupTransferActivity.java
to test change the fragment/section to something like "#groups" since the linked sections don't exist yet in the offline help
close #2829
=> use internal help instead of external links for "learn more" buttons

CHANGELOG.md, build.gradle
k, this will be the first release candidate, makes sense to start with that now, indeed
=> prepare 1.42.0

CHANGELOG.md, build.gradle
ios equivalent: https://github.com/deltachat/deltachat-ios/pull/1992
=> prepare 1.42.3

CONTRIBUTING.md
just to be in sync with https://github.com/deltachat/deltachat-ios/pull/2005
=> add 'point' to points to make them more a statement.

CHANGELOG.md, build.gradle
replaces https://github.com/deltachat/deltachat-android/pull/2890
=> prepare 1.42.6

src/org/thoughtcrime/securesms/EphemeralMessagesDialog.java
~~a help update to get https://github.com/deltachat/deltachat-pages/pull/765 in needs to be done before merging this makes sense.~~ ~~also, #2883 should be fixed before.~~ EDIT: both are done
however, it can already be approved :)
=> add 'learn more' to ephemeral messages dialog

src/org/thoughtcrime/securesms/WelcomeActivity.java
=> display title bar and back button in welcome screen

.github/workflows/preview-apk.yml, build.gradle, gradle.properties
=> upgrade some dependencies

res/xml/preferences_advanced.xml, src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java, src/org/thoughtcrime/securesms/reactions/AddReactionView.java
the reactions support being added to desktop, ubuntu-touch and iOS ends the experimental time on android :)
=> reactions are no longer experimental

src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/ConversationFragment.java
=> hide AddReactionView when user clicks on the attachments buttons

res/values-night/colors.xml, res/values/colors.xml
=> tweak reactions style

res/values/strings.xml
needed for desktop's context menu
=> add string 'React'

res/layout/conversation_list_activity.xml, src/org/thoughtcrime/securesms/ConversationListActivity.java, src/org/thoughtcrime/securesms/ConversationListFragment.java, src/org/thoughtcrime/securesms/connect/DcEventCenter.java
=> add global unread messages badge counter

res/menu/qr_scan.xml, src/org/thoughtcrime/securesms/ConversationListActivity.java, src/org/thoughtcrime/securesms/qr/QrActivity.java, src/org/thoughtcrime/securesms/qr/QrShowActivity.java, src/org/thoughtcrime/securesms/qr/QrShowFragment.java, src/org/thoughtcrime/securesms/util/Util.java
=> copy invite links to clipboard

AndroidManifest.xml
=> declare hasFragileUserData

res/menu/registration_qr_activity.xml, src/org/thoughtcrime/securesms/qr/RegistrationQrActivity.java
=> add troubleshooting menu option on the scanner side

src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
this is done by core as needed since https://github.com/deltachat/deltachat-core-rust/pull/5117
counterpart of https://github.com/deltachat/deltachat-ios/pull/2076
=> start/stop IO no longer needed on config changes

metadata/en-US/changelogs/6804.txt
f-droid changelog created according to [RELEASE.md](https://github.com/deltachat/deltachat-android/blob/main/RELEASE.md#release-on-f-droid)
if this is merged to master, and nothing else has happend on master in between, do ...
```
git tag v1.44.0; git push --tags
```
... to tag a release for f-droid
=> add f-droid changelog & release instructions

res/values/strings.xml
explicitly say that the string will be truncated often.
this PR is the outcome of real-world translation discussions
=> refine translator hint wrt reaction summary

src/org/thoughtcrime/securesms/FullMsgActivity.java, src/org/thoughtcrime/securesms/WebViewActivity.java, src/org/thoughtcrime/securesms/WebxdcActivity.java
due to recent changes to fix the "allow internet" mode, this part in `handleEvent()` was forgotten
=> fix bug in WebxdcActivity: don't try to get iframe in "allow internet" mode

src/org/thoughtcrime/securesms/WebViewActivity.java
this PR simplify code by following linter hints; initially i only wanted to remove the unused return value
=> simplify code

src/org/thoughtcrime/securesms/WelcomeActivity.java, src/org/thoughtcrime/securesms/qr/QrCodeHandler.java
DCLOGIN: is same as DCACCOUNT: and differ only wrt confirmation message.
this PR unifies flows to avoid hickup as on (https://github.com/deltachat/deltachat-desktop/pull/3773) on the upcoming onboarding work
=> unify the flows of DCACCOUNT: and DCLOGIN: 

AndroidManifest.xml
funny, how many places pop up that still needs cleanup. mapbox was everywhere :)
=> remove MapActivity from manifest

res/values/strings.xml
this PR syncs the headlines in instant onboarding and settings to "Your Profile" (instead of "Your Profile Info" in the settings)
split of https://github.com/deltachat/deltachat-android/pull/3019 to avoid mixing of new/changed strings; when this PR is merged `./scripts/tx-update-changed-sources.sh` needs to be executed
=> consistent headlines for 'Your Profile'

res/layout/new_contact_activity.xml, res/layout/recording_layout.xml
=> use app:drawableStartCompat instead of android:drawableStart

src/org/thoughtcrime/securesms/ConversationActivity.java, src/org/thoughtcrime/securesms/components/InputPanel.java
=> clear quote if current draft has no quote

CHANGELOG.md, build.gradle, src/org/thoughtcrime/securesms/ConversationListActivity.java
this is only a beta version to get important feedback, esp. for FCM - therefore, i added "What to test" also to the device messages (not only to the final message)
=> prepare 1.45.0

res/layout/welcome_activity.xml, res/values/strings.xml
just that this is not forgotten, cc @hpk42
=> change welcome headline

AndroidManifest.xml, res/menu/view_log.xml, src/org/thoughtcrime/securesms/LogViewActivity.java, src/org/thoughtcrime/securesms/LogViewFragment.java
=> allow to share log instead of copying to clipboard

src/org/thoughtcrime/securesms/InstantOnboardingActivity.java
=> save avatar and name onPause() in InstantOnboardingActivity

res/layout/new_contact_activity.xml, res/values/strings.xml
add a hint to the 'manual contact' activity from https://github.com/deltachat/deltachat-android/pull/3064
=> add hint to 'add manual contact'

src/org/thoughtcrime/securesms/NewConversationActivity.java
=> bugfix: parse results of scanning QR code in NewConversationActivity

src/org/thoughtcrime/securesms/LogViewFragment.java
=> improve logs: use emojis to mark the log level for easier visibility

src/org/thoughtcrime/securesms/geolocation/LocationBackgroundService.java
fixes https://github.com/deltachat/deltachat-android/issues/3098
=> fix location streaming

CHANGELOG.md
do we need a CHANGELOG entry for that change?
=> the button is called 'Create New Profile' meanwhile

jni/dc_wrapper.c, src/com/b44t/messenger/DcContext.java, src/com/b44t/messenger/DcEvent.java
see https://github.com/deltachat/deltachat-core-rust/pull/5608 for discussion. going all-in to jsonrpc seems too early
cc @adbenitez in case you'll adapt the script from desktop :)
=> add getData2Blob() needed for DC_EVENT_WEBXDC_REALTIME_DATA

res/values/strings.xml
Needed for https://github.com/deltachat/deltachat-desktop/pull/3741
=> feat: add stock strings for realtime

RELEASE.md
just uploaded 1.46.2 there and wrote down the steps needed
closes #2982
=> add instructions for releasing for Huawei AppGallery

src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java
setConfigFromQR() involves network and should not block the UI.
(/me in deutsche bahn :)
=> call setConfigFromQR() from background thread

src/main/java/org/thoughtcrime/securesms/LogViewFragment.java
=> only show debug entries if developer mode is enabled

CHANGELOG.md, build.gradle
for f-droid, tag after merging with:
```
git tag v1.46.4; git push --tags 
```
=> prepare 1.46.4

src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java
=> don't go back to welcome screen when pressing back after instant onboarding

src/main/res/values/strings.xml
thanks @link2xt to point to the "Delete this Login" inconsistency. 
i found another one while doing the PR, see diff
=> prefer new 'Profile' over old 'Login' wording

src/main/java/com/b44t/messenger/DcContext.java, src/main/java/org/thoughtcrime/securesms/WelcomeActivity.java
This goes together with https://github.com/deltachat/deltachat-core-rust/pull/5775 but can actually be merged even before updating the core.
=> feat: support backup transfer protocol v2

metadata/en-US/changelogs/6904.txt
moreover, i just tagged f-droid using `git tag v1.46.7 2ca0e1012fcc05d3cd20cf3a8f8d6ccaddb79f33; git push --tags` and added `deltachat-gplay-release-1.46.7.apk` as release asset to [github releases](https://github.com/deltachat/deltachat-android/releases)
=> add v1.46.7 changelog for f-droid

src/main/java/org/thoughtcrime/securesms/qr/QrActivity.java
=> hide "add contact manually" for chatmail accounts

src/main/java/org/thoughtcrime/securesms/audio/AudioSlidePlayer.java, src/main/java/org/thoughtcrime/securesms/connect/DcContactsLoader.java, src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java, src/main/java/org/thoughtcrime/securesms/contacts/ContactSelectionListAdapter.java, src/main/java/org/thoughtcrime/securesms/util/SendRelayedMessageUtil.java, src/main/res/values/attrs.xml, src/main/res/values/themes.xml
wanted to remove stock-translation no. 200 only, looked that this and that then ... :)
=> some cleanup 🧹

src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java, src/main/res/menu/text_secure_normal.xml
=> remove switch account from main menu

src/main/java/org/thoughtcrime/securesms/qr/QrShowFragment.java, src/main/res/layout/qr_show_fragment.xml, src/main/res/values/strings.xml
=> add "copy invite link" button to QrShowFragment

src/foss/java/org/thoughtcrime/securesms/notifications/FcmReceiveService.java, src/gplay/java/org/thoughtcrime/securesms/notifications/FcmReceiveService.java, src/main/java/org/thoughtcrime/securesms/ApplicationContext.java, src/main/java/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java, src/main/java/org/thoughtcrime/securesms/util/Prefs.java, src/main/res/values/strings.xml, src/main/res/xml/preferences_notifications.xml
=> remove push notifications toggle

src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListAdapter.java, src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListFragment.java, src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListItem.java, src/main/res/layout/account_selection_list_item.xml, src/main/res/menu/account_item_context.xml
=> replace trash icon in profile switcher with context menu

src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java, src/main/res/menu/text_secure_normal.xml, src/main/res/values/strings.xml
=> add "Invite Friends" to main menu

src/main/java/org/thoughtcrime/securesms/qr/BackupProviderFragment.java, src/main/res/layout/backup_provider_fragment.xml
=> fix: hide copy to clipboard while QR is not ready

src/main/java/org/thoughtcrime/securesms/ConversationListFragment.java, src/main/java/org/thoughtcrime/securesms/util/Prefs.java
see commit messages for details
=> cleanup log, fix typo

src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListAdapter.java, src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListItem.java, src/main/res/layout/account_selection_list_item.xml
=> tweak account selection style

src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListFragment.java
=> allow to delete selected account

src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java
=> avoid NullPointerException in ConversationListActivity.refreshAvatar

src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
=> revert hack introduced in #2835

src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java, src/main/java/org/thoughtcrime/securesms/WelcomeActivity.java
=> avoid android.view.WindowManager$BadTokenException in maybeShowConfigurationError

src/main/java/org/thoughtcrime/securesms/LogViewFragment.java
=> log notifications permission status

src/main/java/com/b44t/messenger/DcContext.java, src/main/java/org/thoughtcrime/securesms/ApplicationPreferencesActivity.java, src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java, src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java
=> show display name in title bar when user has multiple profiles

src/main/java/com/b44t/messenger/DcContext.java, src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java, src/main/java/org/thoughtcrime/securesms/WelcomeActivity.java, src/main/java/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java, src/main/java/org/thoughtcrime/securesms/qr/BackupProviderFragment.java, src/main/java/org/thoughtcrime/securesms/qr/BackupReceiverFragment.java
=> don't change delete_server_after, let core handle it

src/main/java/com/b44t/messenger/DcContext.java, src/main/java/org/thoughtcrime/securesms/proxy/ProxySettingsActivity.java, src/main/java/org/thoughtcrime/securesms/qr/QrCodeHandler.java, src/main/res/values/strings.xml
=> allow to set proxies from QRs

src/main/java/org/thoughtcrime/securesms/proxy/ProxyListAdapter.java, src/main/res/layout/proxy_list_item.xml
improve buttons' tap area and don't show confusing "not connected" if account is not configured or proxy is disabled
=> improve proxy settings UI

src/main/AndroidManifest.xml, src/main/java/org/thoughtcrime/securesms/components/emoji/EmojiTextView.java, src/main/java/org/thoughtcrime/securesms/proxy/ProxySettingsActivity.java, src/main/java/org/thoughtcrime/securesms/qr/QrCodeHandler.java, src/main/java/org/thoughtcrime/securesms/util/LongClickCopySpan.java
also linkify proxy URLs in text messages
close #3335
=> register app for opening ss:// and socks5:// proxy URLs

src/main/res/layout/group_create_activity.xml
=> auto-focus group name field

src/main/java/org/thoughtcrime/securesms/qr/QrActivity.java
=> Do not remember "New Contact" screen's tab state

src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java, src/main/java/org/thoughtcrime/securesms/WelcomeActivity.java, src/main/java/org/thoughtcrime/securesms/qr/RegistrationQrActivity.java, src/main/res/menu/registration_qr_activity.xml
=> allow to paste from clipboard in RegistrationQrActivity

jni/dc_wrapper.c, src/main/java/com/b44t/messenger/DcContext.java, src/main/java/org/thoughtcrime/securesms/proxy/ProxySettingsActivity.java, src/main/res/layout/dialog_share_proxy.xml, src/main/res/values/strings.xml
add new API DcContext.createQrSvg() and use it to generate proxy QRs for sharing
=> Allow to share proxy via QR

RELEASE.md
this PR adapts the "phased rollout instructions", as a result of internal discussions
=> tweak phased rollout instructions

src/main/java/org/thoughtcrime/securesms/ConversationItem.java, src/main/res/layout/conversation_item_received.xml, src/main/res/layout/conversation_item_sent.xml, src/main/res/values/dimens.xml
=> improve msg_action_button

src/main/java/org/thoughtcrime/securesms/reactions/AddReactionView.java, src/main/res/values/text_styles.xml
also avoid moving the selector horizontally out of screen 
close #3291
=> don't increase reaction selector's font size according to system

src/main/res/layout/proxy_list_item.xml
=> change proxy protocol label position

src/main/java/com/b44t/messenger/DcContext.java, src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java, src/main/java/org/thoughtcrime/securesms/connect/DcEventCenter.java, src/main/java/org/thoughtcrime/securesms/notifications/NotificationCenter.java
=> notify DC_EVENT_INCOMING_WEBXDC_NOTIFY

src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java, src/main/res/menu/webxdc.xml
=> add "show in chat" to webxdc menu

CHANGELOG.md
i've peeked at the android changelog when doing https://github.com/deltachat/deltachat-ios/pull/2428 , and that seemed to be missing :)
=> amend 1.50 changelog

src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java, src/main/res/raw/webxdc.js
=> add missing webxdc api

src/main/java/org/thoughtcrime/securesms/WebxdcStoreActivity.java
=> download .xdc files in background

src/main/java/org/thoughtcrime/securesms/ConversationActivity.java, src/main/res/layout-land/conversation_activity_emojidrawer_stub.xml, src/main/res/layout-land/reaction_picker.xml, src/main/res/layout/conversation_activity.xml
* adapt better to landscape mode
* fix bug: reload emoji picker after orientation changes
close #3490
=> improve emoji pickers

src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java
=> avoid NPE in ConversationListActivity.onNewIntent()

src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
=> try to avoid FILL500 getting stuck in some devices

scripts/ndk-make.sh
=> Update the core submodule so that we can have nightlies again

src/main/java/org/thoughtcrime/securesms/audio/AudioSlidePlayer.java
=> avoid race condition in onPlayerStateChanged inside AudioSlidePlayer.requestDuration

.github/ISSUE_TEMPLATE/config.yml
see https://github.com/deltachat/deltachat-ios/pull/2525 for screenshots and reasoning
=> do not force ppl to create blank issues

src/main/res/values/strings.xml
@nicodh  once this is merged, the string should be pulled on desktop. then the untranslated-file can be cleaned up further
=> add missing desktop strings

build.gradle, src/main/java/org/thoughtcrime/securesms/mms/SignalGlideModule.java
the attempt to fix #2957 introduced a bug, and it was not really solving the problem completely
revert #3035
close #3549
=> fix: make animated webp animated again

src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java, src/main/java/org/thoughtcrime/securesms/NewConversationActivity.java, src/main/java/org/thoughtcrime/securesms/ShareActivity.java, src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java, src/main/java/org/thoughtcrime/securesms/util/LongClickCopySpan.java, src/main/res/values/strings.xml
=> revert #3177

src/main/java/org/thoughtcrime/securesms/MediaPreviewActivity.java
=> avoid crash in MediaPreviewActivity.onPageUnselected

build.gradle, src/main/AndroidManifest.xml, src/main/java/org/thoughtcrime/securesms/CreateProfileActivity.java, src/main/java/org/thoughtcrime/securesms/GroupCreateActivity.java, src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java, src/main/java/org/thoughtcrime/securesms/profiles/AvatarHelper.java
this dependency was necessary only for SDK<19 and not needed anymore that min SDK is 21
=> remove unused com.soundcloud.android:android-crop dependency

src/main/res/layout/conversation_item_received.xml
=> align avatar to message bubble instead of parent bottom

jni/dc_wrapper.c, src/main/java/com/b44t/messenger/DcMsg.java
the corresponding cffi function will be removed soon, see https://github.com/deltachat/deltachat-core-rust/pull/6558
=> removed unused setFile()

src/main/java/org/thoughtcrime/securesms/MediaPreviewActivity.java, src/main/java/org/thoughtcrime/securesms/MessageSelectorFragment.java, src/main/res/values/strings.xml
once this is merged, `./scripts/tx-update-changed-sources.sh` needs to be run
=> remove 'server' part from asking about message deletion

src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListAdapter.java
fix linter/AndroidStudio warnings and cleanup code in AccountSelectionListAdapter
=> cleanup AccountSelectionListAdapter

build.gradle
=> update gson lib that was pinned for android4 compat

src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListFragment.java
`DialogFragment.onActivityCreated` is deprecated
=> fix linter warnings in AccountSelectionListFragment

src/main/res/values/strings.xml
that should get in when using a core with https://github.com/deltachat/deltachat-core-rust/pull/6573
=> reword message deletion string

src/main/java/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java
=> cleanup NotificationsPreferenceFragment

src/main/java/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java
=> cleanup ChatsPreferenceFragment

src/main/java/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
=> cleanup AdvancedPreferenceFragment

src/main/java/org/thoughtcrime/securesms/ConversationFragment.java
=> don't allow editing for now

src/main/res/values/strings.xml
see https://support.delta.chat/t/profile-description-instead-of-private-tag/3386 for reasoning and discussion
once merged, `./scripts/tx-update-changed-sources.sh` should be run
=> reword 'Private Tag' to 'Profile Label'

src/main/java/org/thoughtcrime/securesms/BaseConversationListFragment.java
=> avoid IllegalArgumentException in BaseConversationListFragment.handleAddToHomeScreen

src/main/java/com/b44t/messenger/rpc/Rpc.java, src/main/java/org/thoughtcrime/securesms/ApplicationContext.java
also add measures to avoid same mistake in the future 
close #3665
=> call rpc.start() before it is used

src/main/java/org/thoughtcrime/securesms/ProfileSettingsFragment.java
=> avoid ANR in ProfileSettingsFragment.onActivityResult

src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
=> avoid ANR in ConversationActivity.processComposeControls

src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
#skip-changelog since this was never released
=> avoid NPE in processComposeControls

CHANGELOG.md, flake.nix, src/main/java/org/thoughtcrime/securesms/ConversationFragment.java, src/main/java/org/thoughtcrime/securesms/util/views/ConversationAdaptiveActionsToolbar.java, src/main/res/drawable/baseline_bookmark_border_24.xml, src/main/res/drawable/baseline_bookmark_remove_24.xml, src/main/res/menu/conversation_context.xml
=> add action menu icon option to toggle message bookmark

CHANGELOG.md, src/main/java/org/thoughtcrime/securesms/MuteDialog.java, src/main/res/values/arrays.xml, src/main/res/values/strings.xml
see https://support.delta.chat/t/mute-group-chat-notifications-for-8-hours/3624/6 for discussion and reasoning
=> add mute option for 8 hours

CHANGELOG.md, src/main/java/org/thoughtcrime/securesms/components/ComposeText.java
=> force "paste as plain text" in composer

src/main/java/org/thoughtcrime/securesms/AttachContactActivity.java, src/main/java/org/thoughtcrime/securesms/ContactMultiSelectionActivity.java, src/main/java/org/thoughtcrime/securesms/ContactSelectionActivity.java, src/main/java/org/thoughtcrime/securesms/ContactSelectionListFragment.java, src/main/java/org/thoughtcrime/securesms/GroupCreateActivity.java, src/main/java/org/thoughtcrime/securesms/NewConversationActivity.java, src/main/java/org/thoughtcrime/securesms/ProfileSettingsFragment.java, src/main/java/org/thoughtcrime/securesms/contacts/ContactSelectionListAdapter.java, src/main/java/org/thoughtcrime/securesms/contacts/NewContactActivity.java
move away from using email address as contact identifier, try to use contact ID when possible
#skip-changelog: internal change, not user-visible change
=> don't use email address as contact unique identifier

jni/dc_wrapper.c, src/main/java/com/b44t/messenger/DcContext.java
the API calls were only partly removed at #3594
=> remove unused ASM code

src/main/java/com/b44t/messenger/rpc/Rpc.java, src/main/java/org/thoughtcrime/securesms/ProfileActivity.java
close #3692 
#skip-changelog: internal change from FFI to RPC
=> use Rpc to set contact's name

src/main/java/org/thoughtcrime/securesms/RegistrationActivity.java
=>  refactor: Remove dead 'configure' code 

src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java
=> catch IllegalArgumentException in InstantOnboardingActivity.progressError()

CHANGELOG.md, src/main/java/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java
=> avoid SecurityException in NotificationsPreferenceFragment

src/main/java/org/thoughtcrime/securesms/scribbles/UriGlideRenderer.java
=> avoid NPE in UriGlideRenderer

CHANGELOG.md, src/main/java/org/thoughtcrime/securesms/preferences/widgets/ProfilePreference.java, src/main/res/layout/profile_preference_view.xml
showing the address here prominently results in bad UX as ppl try to pass the address around,
which will not result in e2ee and will often not work.
see https://github.com/deltachat/deltachat-ios/pull/2664 for more resoning and discussion, eg. why remove it unconditionally
cmp https://github.com/deltachat/deltachat-desktop/pull/4970
=> remove address from primary settings UI

build.gradle
=> fix and update PhotoView dependency

CHANGELOG.md, src/main/res/values-nl/strings.xml, src/main/res/values-pl/strings.xml, src/main/res/values-uk/strings.xml
=> update core to 1.159.1

src/main/java/org/thoughtcrime/securesms/ConversationListItem.java
=> fix linter warnings in ConversationListItem

src/main/java/org/thoughtcrime/securesms/ConversationItem.java, src/main/java/org/thoughtcrime/securesms/search/SearchFragment.java
=> fix some linter warnings

src/main/java/org/thoughtcrime/securesms/ProfileActivity.java, src/main/java/org/thoughtcrime/securesms/ProfileSettingsAdapter.java, src/main/java/org/thoughtcrime/securesms/ProfileSettingsFragment.java
=> fix some linter warnings in classes related to profile

src/main/java/com/b44t/messenger/rpc/Rpc.java, src/main/java/org/thoughtcrime/securesms/RegistrationActivity.java
The API was renamed in https://github.com/chatmail/core/pull/6800 (i.e. core v1.159.2)
=> refactor: Rename addTransport -> addOrUpdateTransport()

CHANGELOG.md, src/main/java/org/thoughtcrime/securesms/ApplicationPreferencesActivity.java, src/main/res/drawable/ic_donate_24dp.xml, src/main/res/xml/preferences.xml
=> add "Donate" button to main settings

CHANGELOG.md, src/main/res/values-es/strings.xml, src/main/res/values-it/strings.xml, src/main/res/values-nl/strings.xml, src/main/res/values-zh-rCN/strings.xml
=> Update core to 1.159.3

src/main/java/org/thoughtcrime/securesms/reactions/ReactionRecipientItem.java, src/main/java/org/thoughtcrime/securesms/reactions/ReactionRecipientsAdapter.java, src/main/java/org/thoughtcrime/securesms/reactions/ReactionsDetailsFragment.java, src/main/res/layout/reaction_recipient_item.xml
this allows to easily react with same emoji as others from the reactions details fragment
=> allow to react with same emoji as others

src/main/java/org/thoughtcrime/securesms/ProfileAdapter.java
=> hidde "chats in common" header when no chats in common

src/main/java/org/thoughtcrime/securesms/ConversationTitleView.java, src/main/java/org/thoughtcrime/securesms/ProfileAdapter.java, src/main/java/org/thoughtcrime/securesms/ProfileFragment.java, src/main/java/org/thoughtcrime/securesms/ProfileTextItem.java, src/main/res/layout/profile_divider.xml
follow up for https://github.com/deltachat/deltachat-android/pull/3792 
closes #3799 
#skip-changelog as there was no release with the missing features
see commits for details
EDIT: copying was tuned down on purpose at https://github.com/deltachat/deltachat-android/pull/3175 , this PR just does the same as before, long tapping an address offers to copy it to the clipboard
=> tweak new profile

src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java, src/main/res/values/strings.xml
close #3819 
feel free to tweak or suggest changes
=> add device message

src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java, src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java, src/main/res/values/strings.xml
this also fixes log entries as "Invalid stock message ID 123"
=> deprecate some strings

CHANGELOG.md, src/main/java/org/thoughtcrime/securesms/ConversationListItem.java
=> hide address in search results

CHANGELOG.md, src/main/java/org/thoughtcrime/securesms/ConversationActivity.java, src/main/java/org/thoughtcrime/securesms/ConversationFragment.java, src/main/java/org/thoughtcrime/securesms/ProfileActivity.java
disable non-functional options
=> improve classic email threads/chats UX

CHANGELOG.md, src/main/res/layout/conversation_item_footer.xml
close #3841 
and also fix wrong margins for RTL languages
=> improve footer layout

CHANGELOG.md, src/main/java/org/thoughtcrime/securesms/ProfileActivity.java
=> don't enlarge avatars for special chats

CHANGELOG.md, src/main/java/org/thoughtcrime/securesms/ProfileActivity.java
=> share address for email contacts

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/org/thoughtcrime/securesms/ConversationListItem.java, src/main/java/org/thoughtcrime/securesms/components/QuoteView.java, src/main/java/org/thoughtcrime/securesms/database/loaders/BucketedThreadMediaLoader.java, src/main/java/org/thoughtcrime/securesms/mms/Slide.java, src/main/java/org/thoughtcrime/securesms/permissions/Permissions.java, src/main/java/org/thoughtcrime/securesms/permissions/PermissionsRequest.java, src/main/res/layout/share_activity.xml
=> remove some dependecies and upgrade others

src/main/java/org/thoughtcrime/securesms/MessageSelectorFragment.java
=> call dcContext.deleteMsgs() in background thread

src/main/java/org/thoughtcrime/securesms/ConversationItem.java, src/main/java/org/thoughtcrime/securesms/components/CallItemView.java, src/main/java/org/thoughtcrime/securesms/components/ConversationItemFooter.java, src/main/res/layout/call_item_view.xml, src/main/res/layout/conversation_item_call.xml, src/main/res/layout/conversation_item_received.xml, src/main/res/layout/conversation_item_sent.xml
=> improve displaying of call messages

CHANGELOG.md, src/main/java/org/thoughtcrime/securesms/GroupCreateActivity.java
=> process permissions result in GroupCreateActivity
